package mod.silverwolfs.silverwolfsbuildingblocks.init;

import mod.silverwolfs.silverwolfsbuildingblocks.SilverwolfsBuildingBlocks;
import net.minecraft.block.AbstractBlock;
import net.minecraft.block.Block;
import net.minecraft.block.SoundType;
import net.minecraft.block.material.Material;
import net.minecraft.item.DyeColor;
import net.minecraft.item.Item;
import net.minecraftforge.common.ToolType;
import net.minecraftforge.eventbus.api.IEventBus;
import net.minecraftforge.fml.RegistryObject;
import net.minecraftforge.registries.DeferredRegister;
import net.minecraftforge.registries.ForgeRegistries;

import java.util.ArrayList;

public class ItemInit {
    public static final DeferredRegister<Item> ITEMS = DeferredRegister.create(ForgeRegistries.ITEMS, SilverwolfsBuildingBlocks.MOD_ID);

    public static void init(IEventBus modBus) {
        ITEMS.register(modBus);
    }

    public static final RegistryObject<Item> THATCH = ITEMS.register("thatch", () -> new Item(new Item.Properties().group(SilverwolfsBuildingBlocks.SilverwolfsBlocksItemGroup.instance)));

    public static final RegistryObject<Item> BLACK_LIGHT_CLAY_BALL = ITEMS.register("black_light_clay_ball", () -> new Item(new Item.Properties().group(SilverwolfsBuildingBlocks.SilverwolfsBlocksItemGroup.instance)));
    public static final RegistryObject<Item> BLUE_LIGHT_CLAY_BALL = ITEMS.register("blue_light_clay_ball", () -> new Item(new Item.Properties().group(SilverwolfsBuildingBlocks.SilverwolfsBlocksItemGroup.instance)));
    public static final RegistryObject<Item> BROWN_LIGHT_CLAY_BALL = ITEMS.register("brown_light_clay_ball", () -> new Item(new Item.Properties().group(SilverwolfsBuildingBlocks.SilverwolfsBlocksItemGroup.instance)));
    public static final RegistryObject<Item> CYAN_LIGHT_CLAY_BALL = ITEMS.register("cyan_light_clay_ball", () -> new Item(new Item.Properties().group(SilverwolfsBuildingBlocks.SilverwolfsBlocksItemGroup.instance)));
    public static final RegistryObject<Item> GRAY_LIGHT_CLAY_BALL = ITEMS.register("gray_light_clay_ball", () -> new Item(new Item.Properties().group(SilverwolfsBuildingBlocks.SilverwolfsBlocksItemGroup.instance)));
    public static final RegistryObject<Item> GREEN_LIGHT_CLAY_BALL = ITEMS.register("green_light_clay_ball", () -> new Item(new Item.Properties().group(SilverwolfsBuildingBlocks.SilverwolfsBlocksItemGroup.instance)));
    public static final RegistryObject<Item> LIGHT_BLUE_LIGHT_CLAY_BALL = ITEMS.register("light_blue_light_clay_ball", () -> new Item(new Item.Properties().group(SilverwolfsBuildingBlocks.SilverwolfsBlocksItemGroup.instance)));
    public static final RegistryObject<Item> LIGHT_GRAY_LIGHT_CLAY_BALL = ITEMS.register("light_gray_light_clay_ball", () -> new Item(new Item.Properties().group(SilverwolfsBuildingBlocks.SilverwolfsBlocksItemGroup.instance)));
    public static final RegistryObject<Item> LIME_LIGHT_CLAY_BALL = ITEMS.register("lime_light_clay_ball", () -> new Item(new Item.Properties().group(SilverwolfsBuildingBlocks.SilverwolfsBlocksItemGroup.instance)));
    public static final RegistryObject<Item> MAGENTA_LIGHT_CLAY_BALL = ITEMS.register("magenta_light_clay_ball", () -> new Item(new Item.Properties().group(SilverwolfsBuildingBlocks.SilverwolfsBlocksItemGroup.instance)));
    public static final RegistryObject<Item> ORANGE_LIGHT_CLAY_BALL = ITEMS.register("orange_light_clay_ball", () -> new Item(new Item.Properties().group(SilverwolfsBuildingBlocks.SilverwolfsBlocksItemGroup.instance)));
    public static final RegistryObject<Item> PINK_LIGHT_CLAY_BALL = ITEMS.register("pink_light_clay_ball", () -> new Item(new Item.Properties().group(SilverwolfsBuildingBlocks.SilverwolfsBlocksItemGroup.instance)));
    public static final RegistryObject<Item> PURPLE_LIGHT_CLAY_BALL = ITEMS.register("purple_light_clay_ball", () -> new Item(new Item.Properties().group(SilverwolfsBuildingBlocks.SilverwolfsBlocksItemGroup.instance)));
    public static final RegistryObject<Item> RED_LIGHT_CLAY_BALL = ITEMS.register("red_light_clay_ball", () -> new Item(new Item.Properties().group(SilverwolfsBuildingBlocks.SilverwolfsBlocksItemGroup.instance)));
    public static final RegistryObject<Item> WHITE_LIGHT_CLAY_BALL = ITEMS.register("white_light_clay_ball", () -> new Item(new Item.Properties().group(SilverwolfsBuildingBlocks.SilverwolfsBlocksItemGroup.instance)));
    public static final RegistryObject<Item> YELLOW_LIGHT_CLAY_BALL = ITEMS.register("yellow_light_clay_ball", () -> new Item(new Item.Properties().group(SilverwolfsBuildingBlocks.SilverwolfsBlocksItemGroup.instance)));
    public static final RegistryObject<Item> BLACK_MEDIUM_CLAY_BALL = ITEMS.register("black_medium_clay_ball", () -> new Item(new Item.Properties().group(SilverwolfsBuildingBlocks.SilverwolfsBlocksItemGroup.instance)));
    public static final RegistryObject<Item> BLUE_MEDIUM_CLAY_BALL = ITEMS.register("blue_medium_clay_ball", () -> new Item(new Item.Properties().group(SilverwolfsBuildingBlocks.SilverwolfsBlocksItemGroup.instance)));
    public static final RegistryObject<Item> BROWN_MEDIUM_CLAY_BALL = ITEMS.register("brown_medium_clay_ball", () -> new Item(new Item.Properties().group(SilverwolfsBuildingBlocks.SilverwolfsBlocksItemGroup.instance)));
    public static final RegistryObject<Item> CYAN_MEDIUM_CLAY_BALL = ITEMS.register("cyan_medium_clay_ball", () -> new Item(new Item.Properties().group(SilverwolfsBuildingBlocks.SilverwolfsBlocksItemGroup.instance)));
    public static final RegistryObject<Item> GRAY_MEDIUM_CLAY_BALL = ITEMS.register("gray_medium_clay_ball", () -> new Item(new Item.Properties().group(SilverwolfsBuildingBlocks.SilverwolfsBlocksItemGroup.instance)));
    public static final RegistryObject<Item> GREEN_MEDIUM_CLAY_BALL = ITEMS.register("green_medium_clay_ball", () -> new Item(new Item.Properties().group(SilverwolfsBuildingBlocks.SilverwolfsBlocksItemGroup.instance)));
    public static final RegistryObject<Item> LIGHT_BLUE_MEDIUM_CLAY_BALL = ITEMS.register("light_blue_medium_clay_ball", () -> new Item(new Item.Properties().group(SilverwolfsBuildingBlocks.SilverwolfsBlocksItemGroup.instance)));
    public static final RegistryObject<Item> LIGHT_GRAY_MEDIUM_CLAY_BALL = ITEMS.register("light_gray_medium_clay_ball", () -> new Item(new Item.Properties().group(SilverwolfsBuildingBlocks.SilverwolfsBlocksItemGroup.instance)));
    public static final RegistryObject<Item> LIME_MEDIUM_CLAY_BALL = ITEMS.register("lime_medium_clay_ball", () -> new Item(new Item.Properties().group(SilverwolfsBuildingBlocks.SilverwolfsBlocksItemGroup.instance)));
    public static final RegistryObject<Item> MAGENTA_MEDIUM_CLAY_BALL = ITEMS.register("magenta_medium_clay_ball", () -> new Item(new Item.Properties().group(SilverwolfsBuildingBlocks.SilverwolfsBlocksItemGroup.instance)));
    public static final RegistryObject<Item> ORANGE_MEDIUM_CLAY_BALL = ITEMS.register("orange_medium_clay_ball", () -> new Item(new Item.Properties().group(SilverwolfsBuildingBlocks.SilverwolfsBlocksItemGroup.instance)));
    public static final RegistryObject<Item> PINK_MEDIUM_CLAY_BALL = ITEMS.register("pink_medium_clay_ball", () -> new Item(new Item.Properties().group(SilverwolfsBuildingBlocks.SilverwolfsBlocksItemGroup.instance)));
    public static final RegistryObject<Item> PURPLE_MEDIUM_CLAY_BALL = ITEMS.register("purple_medium_clay_ball", () -> new Item(new Item.Properties().group(SilverwolfsBuildingBlocks.SilverwolfsBlocksItemGroup.instance)));
    public static final RegistryObject<Item> RED_MEDIUM_CLAY_BALL = ITEMS.register("red_medium_clay_ball", () -> new Item(new Item.Properties().group(SilverwolfsBuildingBlocks.SilverwolfsBlocksItemGroup.instance)));
    public static final RegistryObject<Item> WHITE_MEDIUM_CLAY_BALL = ITEMS.register("white_medium_clay_ball", () -> new Item(new Item.Properties().group(SilverwolfsBuildingBlocks.SilverwolfsBlocksItemGroup.instance)));
    public static final RegistryObject<Item> YELLOW_MEDIUM_CLAY_BALL = ITEMS.register("yellow_medium_clay_ball", () -> new Item(new Item.Properties().group(SilverwolfsBuildingBlocks.SilverwolfsBlocksItemGroup.instance)));
    public static final RegistryObject<Item> BLACK_DARK_CLAY_BALL = ITEMS.register("black_dark_clay_ball", () -> new Item(new Item.Properties().group(SilverwolfsBuildingBlocks.SilverwolfsBlocksItemGroup.instance)));
    public static final RegistryObject<Item> BLUE_DARK_CLAY_BALL = ITEMS.register("blue_dark_clay_ball", () -> new Item(new Item.Properties().group(SilverwolfsBuildingBlocks.SilverwolfsBlocksItemGroup.instance)));
    public static final RegistryObject<Item> BROWN_DARK_CLAY_BALL = ITEMS.register("brown_dark_clay_ball", () -> new Item(new Item.Properties().group(SilverwolfsBuildingBlocks.SilverwolfsBlocksItemGroup.instance)));
    public static final RegistryObject<Item> CYAN_DARK_CLAY_BALL = ITEMS.register("cyan_dark_clay_ball", () -> new Item(new Item.Properties().group(SilverwolfsBuildingBlocks.SilverwolfsBlocksItemGroup.instance)));
    public static final RegistryObject<Item> GRAY_DARK_CLAY_BALL = ITEMS.register("gray_dark_clay_ball", () -> new Item(new Item.Properties().group(SilverwolfsBuildingBlocks.SilverwolfsBlocksItemGroup.instance)));
    public static final RegistryObject<Item> GREEN_DARK_CLAY_BALL = ITEMS.register("green_dark_clay_ball", () -> new Item(new Item.Properties().group(SilverwolfsBuildingBlocks.SilverwolfsBlocksItemGroup.instance)));
    public static final RegistryObject<Item> LIGHT_BLUE_DARK_CLAY_BALL = ITEMS.register("light_blue_dark_clay_ball", () -> new Item(new Item.Properties().group(SilverwolfsBuildingBlocks.SilverwolfsBlocksItemGroup.instance)));
    public static final RegistryObject<Item> LIGHT_GRAY_DARK_CLAY_BALL = ITEMS.register("light_gray_dark_clay_ball", () -> new Item(new Item.Properties().group(SilverwolfsBuildingBlocks.SilverwolfsBlocksItemGroup.instance)));
    public static final RegistryObject<Item> LIME_DARK_CLAY_BALL = ITEMS.register("lime_dark_clay_ball", () -> new Item(new Item.Properties().group(SilverwolfsBuildingBlocks.SilverwolfsBlocksItemGroup.instance)));
    public static final RegistryObject<Item> MAGENTA_DARK_CLAY_BALL = ITEMS.register("magenta_dark_clay_ball", () -> new Item(new Item.Properties().group(SilverwolfsBuildingBlocks.SilverwolfsBlocksItemGroup.instance)));
    public static final RegistryObject<Item> ORANGE_DARK_CLAY_BALL = ITEMS.register("orange_dark_clay_ball", () -> new Item(new Item.Properties().group(SilverwolfsBuildingBlocks.SilverwolfsBlocksItemGroup.instance)));
    public static final RegistryObject<Item> PINK_DARK_CLAY_BALL = ITEMS.register("pink_dark_clay_ball", () -> new Item(new Item.Properties().group(SilverwolfsBuildingBlocks.SilverwolfsBlocksItemGroup.instance)));
    public static final RegistryObject<Item> PURPLE_DARK_CLAY_BALL = ITEMS.register("purple_dark_clay_ball", () -> new Item(new Item.Properties().group(SilverwolfsBuildingBlocks.SilverwolfsBlocksItemGroup.instance)));
    public static final RegistryObject<Item> RED_DARK_CLAY_BALL = ITEMS.register("red_dark_clay_ball", () -> new Item(new Item.Properties().group(SilverwolfsBuildingBlocks.SilverwolfsBlocksItemGroup.instance)));
    public static final RegistryObject<Item> WHITE_DARK_CLAY_BALL = ITEMS.register("white_dark_clay_ball", () -> new Item(new Item.Properties().group(SilverwolfsBuildingBlocks.SilverwolfsBlocksItemGroup.instance)));
    public static final RegistryObject<Item> YELLOW_DARK_CLAY_BALL = ITEMS.register("yellow_dark_clay_ball", () -> new Item(new Item.Properties().group(SilverwolfsBuildingBlocks.SilverwolfsBlocksItemGroup.instance)));

    public static final RegistryObject<Item> BLACK_LIGHT_BRICK = ITEMS.register("black_light_brick", () -> new Item(new Item.Properties().group(SilverwolfsBuildingBlocks.SilverwolfsBlocksItemGroup.instance)));
    public static final RegistryObject<Item> BLUE_LIGHT_BRICK = ITEMS.register("blue_light_brick", () -> new Item(new Item.Properties().group(SilverwolfsBuildingBlocks.SilverwolfsBlocksItemGroup.instance)));
    public static final RegistryObject<Item> BROWN_LIGHT_BRICK = ITEMS.register("brown_light_brick", () -> new Item(new Item.Properties().group(SilverwolfsBuildingBlocks.SilverwolfsBlocksItemGroup.instance)));
    public static final RegistryObject<Item> CYAN_LIGHT_BRICK = ITEMS.register("cyan_light_brick", () -> new Item(new Item.Properties().group(SilverwolfsBuildingBlocks.SilverwolfsBlocksItemGroup.instance)));
    public static final RegistryObject<Item> GRAY_LIGHT_BRICK = ITEMS.register("gray_light_brick", () -> new Item(new Item.Properties().group(SilverwolfsBuildingBlocks.SilverwolfsBlocksItemGroup.instance)));
    public static final RegistryObject<Item> GREEN_LIGHT_BRICK = ITEMS.register("green_light_brick", () -> new Item(new Item.Properties().group(SilverwolfsBuildingBlocks.SilverwolfsBlocksItemGroup.instance)));
    public static final RegistryObject<Item> LIGHT_BLUE_LIGHT_BRICK = ITEMS.register("light_blue_light_brick", () -> new Item(new Item.Properties().group(SilverwolfsBuildingBlocks.SilverwolfsBlocksItemGroup.instance)));
    public static final RegistryObject<Item> LIGHT_GRAY_LIGHT_BRICK = ITEMS.register("light_gray_light_brick", () -> new Item(new Item.Properties().group(SilverwolfsBuildingBlocks.SilverwolfsBlocksItemGroup.instance)));
    public static final RegistryObject<Item> LIME_LIGHT_BRICK = ITEMS.register("lime_light_brick", () -> new Item(new Item.Properties().group(SilverwolfsBuildingBlocks.SilverwolfsBlocksItemGroup.instance)));
    public static final RegistryObject<Item> MAGENTA_LIGHT_BRICK = ITEMS.register("magenta_light_brick", () -> new Item(new Item.Properties().group(SilverwolfsBuildingBlocks.SilverwolfsBlocksItemGroup.instance)));
    public static final RegistryObject<Item> ORANGE_LIGHT_BRICK = ITEMS.register("orange_light_brick", () -> new Item(new Item.Properties().group(SilverwolfsBuildingBlocks.SilverwolfsBlocksItemGroup.instance)));
    public static final RegistryObject<Item> PINK_LIGHT_BRICK = ITEMS.register("pink_light_brick", () -> new Item(new Item.Properties().group(SilverwolfsBuildingBlocks.SilverwolfsBlocksItemGroup.instance)));
    public static final RegistryObject<Item> PURPLE_LIGHT_BRICK = ITEMS.register("purple_light_brick", () -> new Item(new Item.Properties().group(SilverwolfsBuildingBlocks.SilverwolfsBlocksItemGroup.instance)));
    public static final RegistryObject<Item> RED_LIGHT_BRICK = ITEMS.register("red_light_brick", () -> new Item(new Item.Properties().group(SilverwolfsBuildingBlocks.SilverwolfsBlocksItemGroup.instance)));
    public static final RegistryObject<Item> WHITE_LIGHT_BRICK = ITEMS.register("white_light_brick", () -> new Item(new Item.Properties().group(SilverwolfsBuildingBlocks.SilverwolfsBlocksItemGroup.instance)));
    public static final RegistryObject<Item> YELLOW_LIGHT_BRICK = ITEMS.register("yellow_light_brick", () -> new Item(new Item.Properties().group(SilverwolfsBuildingBlocks.SilverwolfsBlocksItemGroup.instance)));
    public static final RegistryObject<Item> BLACK_MEDIUM_BRICK = ITEMS.register("black_medium_brick", () -> new Item(new Item.Properties().group(SilverwolfsBuildingBlocks.SilverwolfsBlocksItemGroup.instance)));
    public static final RegistryObject<Item> BLUE_MEDIUM_BRICK = ITEMS.register("blue_medium_brick", () -> new Item(new Item.Properties().group(SilverwolfsBuildingBlocks.SilverwolfsBlocksItemGroup.instance)));
    public static final RegistryObject<Item> BROWN_MEDIUM_BRICK = ITEMS.register("brown_medium_brick", () -> new Item(new Item.Properties().group(SilverwolfsBuildingBlocks.SilverwolfsBlocksItemGroup.instance)));
    public static final RegistryObject<Item> CYAN_MEDIUM_BRICK = ITEMS.register("cyan_medium_brick", () -> new Item(new Item.Properties().group(SilverwolfsBuildingBlocks.SilverwolfsBlocksItemGroup.instance)));
    public static final RegistryObject<Item> GRAY_MEDIUM_BRICK = ITEMS.register("gray_medium_brick", () -> new Item(new Item.Properties().group(SilverwolfsBuildingBlocks.SilverwolfsBlocksItemGroup.instance)));
    public static final RegistryObject<Item> GREEN_MEDIUM_BRICK = ITEMS.register("green_medium_brick", () -> new Item(new Item.Properties().group(SilverwolfsBuildingBlocks.SilverwolfsBlocksItemGroup.instance)));
    public static final RegistryObject<Item> LIGHT_BLUE_MEDIUM_BRICK = ITEMS.register("light_blue_medium_brick", () -> new Item(new Item.Properties().group(SilverwolfsBuildingBlocks.SilverwolfsBlocksItemGroup.instance)));
    public static final RegistryObject<Item> LIGHT_GRAY_MEDIUM_BRICK = ITEMS.register("light_gray_medium_brick", () -> new Item(new Item.Properties().group(SilverwolfsBuildingBlocks.SilverwolfsBlocksItemGroup.instance)));
    public static final RegistryObject<Item> LIME_MEDIUM_BRICK = ITEMS.register("lime_medium_brick", () -> new Item(new Item.Properties().group(SilverwolfsBuildingBlocks.SilverwolfsBlocksItemGroup.instance)));
    public static final RegistryObject<Item> MAGENTA_MEDIUM_BRICK = ITEMS.register("magenta_medium_brick", () -> new Item(new Item.Properties().group(SilverwolfsBuildingBlocks.SilverwolfsBlocksItemGroup.instance)));
    public static final RegistryObject<Item> ORANGE_MEDIUM_BRICK = ITEMS.register("orange_medium_brick", () -> new Item(new Item.Properties().group(SilverwolfsBuildingBlocks.SilverwolfsBlocksItemGroup.instance)));
    public static final RegistryObject<Item> PINK_MEDIUM_BRICK = ITEMS.register("pink_medium_brick", () -> new Item(new Item.Properties().group(SilverwolfsBuildingBlocks.SilverwolfsBlocksItemGroup.instance)));
    public static final RegistryObject<Item> PURPLE_MEDIUM_BRICK = ITEMS.register("purple_medium_brick", () -> new Item(new Item.Properties().group(SilverwolfsBuildingBlocks.SilverwolfsBlocksItemGroup.instance)));
    public static final RegistryObject<Item> RED_MEDIUM_BRICK = ITEMS.register("red_medium_brick", () -> new Item(new Item.Properties().group(SilverwolfsBuildingBlocks.SilverwolfsBlocksItemGroup.instance)));
    public static final RegistryObject<Item> WHITE_MEDIUM_BRICK = ITEMS.register("white_medium_brick", () -> new Item(new Item.Properties().group(SilverwolfsBuildingBlocks.SilverwolfsBlocksItemGroup.instance)));
    public static final RegistryObject<Item> YELLOW_MEDIUM_BRICK = ITEMS.register("yellow_medium_brick", () -> new Item(new Item.Properties().group(SilverwolfsBuildingBlocks.SilverwolfsBlocksItemGroup.instance)));
    public static final RegistryObject<Item> BLACK_DARK_BRICK = ITEMS.register("black_dark_brick", () -> new Item(new Item.Properties().group(SilverwolfsBuildingBlocks.SilverwolfsBlocksItemGroup.instance)));
    public static final RegistryObject<Item> BLUE_DARK_BRICK = ITEMS.register("blue_dark_brick", () -> new Item(new Item.Properties().group(SilverwolfsBuildingBlocks.SilverwolfsBlocksItemGroup.instance)));
    public static final RegistryObject<Item> BROWN_DARK_BRICK = ITEMS.register("brown_dark_brick", () -> new Item(new Item.Properties().group(SilverwolfsBuildingBlocks.SilverwolfsBlocksItemGroup.instance)));
    public static final RegistryObject<Item> CYAN_DARK_BRICK = ITEMS.register("cyan_dark_brick", () -> new Item(new Item.Properties().group(SilverwolfsBuildingBlocks.SilverwolfsBlocksItemGroup.instance)));
    public static final RegistryObject<Item> GRAY_DARK_BRICK = ITEMS.register("gray_dark_brick", () -> new Item(new Item.Properties().group(SilverwolfsBuildingBlocks.SilverwolfsBlocksItemGroup.instance)));
    public static final RegistryObject<Item> GREEN_DARK_BRICK = ITEMS.register("green_dark_brick", () -> new Item(new Item.Properties().group(SilverwolfsBuildingBlocks.SilverwolfsBlocksItemGroup.instance)));
    public static final RegistryObject<Item> LIGHT_BLUE_DARK_BRICK = ITEMS.register("light_blue_dark_brick", () -> new Item(new Item.Properties().group(SilverwolfsBuildingBlocks.SilverwolfsBlocksItemGroup.instance)));
    public static final RegistryObject<Item> LIGHT_GRAY_DARK_BRICK = ITEMS.register("light_gray_dark_brick", () -> new Item(new Item.Properties().group(SilverwolfsBuildingBlocks.SilverwolfsBlocksItemGroup.instance)));
    public static final RegistryObject<Item> LIME_DARK_BRICK = ITEMS.register("lime_dark_brick", () -> new Item(new Item.Properties().group(SilverwolfsBuildingBlocks.SilverwolfsBlocksItemGroup.instance)));
    public static final RegistryObject<Item> MAGENTA_DARK_BRICK = ITEMS.register("magenta_dark_brick", () -> new Item(new Item.Properties().group(SilverwolfsBuildingBlocks.SilverwolfsBlocksItemGroup.instance)));
    public static final RegistryObject<Item> ORANGE_DARK_BRICK = ITEMS.register("orange_dark_brick", () -> new Item(new Item.Properties().group(SilverwolfsBuildingBlocks.SilverwolfsBlocksItemGroup.instance)));
    public static final RegistryObject<Item> PINK_DARK_BRICK = ITEMS.register("pink_dark_brick", () -> new Item(new Item.Properties().group(SilverwolfsBuildingBlocks.SilverwolfsBlocksItemGroup.instance)));
    public static final RegistryObject<Item> PURPLE_DARK_BRICK = ITEMS.register("purple_dark_brick", () -> new Item(new Item.Properties().group(SilverwolfsBuildingBlocks.SilverwolfsBlocksItemGroup.instance)));
    public static final RegistryObject<Item> RED_DARK_BRICK = ITEMS.register("red_dark_brick", () -> new Item(new Item.Properties().group(SilverwolfsBuildingBlocks.SilverwolfsBlocksItemGroup.instance)));
    public static final RegistryObject<Item> WHITE_DARK_BRICK = ITEMS.register("white_dark_brick", () -> new Item(new Item.Properties().group(SilverwolfsBuildingBlocks.SilverwolfsBlocksItemGroup.instance)));
    public static final RegistryObject<Item> YELLOW_DARK_BRICK = ITEMS.register("yellow_dark_brick", () -> new Item(new Item.Properties().group(SilverwolfsBuildingBlocks.SilverwolfsBlocksItemGroup.instance)));

    public static final RegistryObject<Item> ACACIA_STICK = ITEMS.register("acacia_stick", () -> new Item(new Item.Properties().group(SilverwolfsBuildingBlocks.SilverwolfsBlocksItemGroup.instance)));
    public static final RegistryObject<Item> BIRCH_STICK = ITEMS.register("birch_stick", () -> new Item(new Item.Properties().group(SilverwolfsBuildingBlocks.SilverwolfsBlocksItemGroup.instance)));
    public static final RegistryObject<Item> DARK_OAK_STICK = ITEMS.register("dark_oak_stick", () -> new Item(new Item.Properties().group(SilverwolfsBuildingBlocks.SilverwolfsBlocksItemGroup.instance)));
    public static final RegistryObject<Item> JUNGLE_STICK = ITEMS.register("jungle_stick", () -> new Item(new Item.Properties().group(SilverwolfsBuildingBlocks.SilverwolfsBlocksItemGroup.instance)));
    public static final RegistryObject<Item> OAK_STICK = ITEMS.register("oak_stick", () -> new Item(new Item.Properties().group(SilverwolfsBuildingBlocks.SilverwolfsBlocksItemGroup.instance)));
    public static final RegistryObject<Item> SPRUCE_STICK = ITEMS.register("spruce_stick", () -> new Item(new Item.Properties().group(SilverwolfsBuildingBlocks.SilverwolfsBlocksItemGroup.instance)));

    public static final RegistryObject<Item> BLACK_LIGHT_STICK = ITEMS.register("black_light_stick", () -> new Item(new Item.Properties().group(SilverwolfsBuildingBlocks.SilverwolfsBlocksItemGroup.instance)));
    public static final RegistryObject<Item> BLUE_LIGHT_STICK = ITEMS.register("blue_light_stick", () -> new Item(new Item.Properties().group(SilverwolfsBuildingBlocks.SilverwolfsBlocksItemGroup.instance)));
    public static final RegistryObject<Item> BROWN_LIGHT_STICK = ITEMS.register("brown_light_stick", () -> new Item(new Item.Properties().group(SilverwolfsBuildingBlocks.SilverwolfsBlocksItemGroup.instance)));
    public static final RegistryObject<Item> CYAN_LIGHT_STICK = ITEMS.register("cyan_light_stick", () -> new Item(new Item.Properties().group(SilverwolfsBuildingBlocks.SilverwolfsBlocksItemGroup.instance)));
    public static final RegistryObject<Item> GRAY_LIGHT_STICK = ITEMS.register("gray_light_stick", () -> new Item(new Item.Properties().group(SilverwolfsBuildingBlocks.SilverwolfsBlocksItemGroup.instance)));
    public static final RegistryObject<Item> GREEN_LIGHT_STICK = ITEMS.register("green_light_stick", () -> new Item(new Item.Properties().group(SilverwolfsBuildingBlocks.SilverwolfsBlocksItemGroup.instance)));
    public static final RegistryObject<Item> LIGHT_BLUE_LIGHT_STICK = ITEMS.register("light_blue_light_stick", () -> new Item(new Item.Properties().group(SilverwolfsBuildingBlocks.SilverwolfsBlocksItemGroup.instance)));
    public static final RegistryObject<Item> LIGHT_GRAY_LIGHT_STICK = ITEMS.register("light_gray_light_stick", () -> new Item(new Item.Properties().group(SilverwolfsBuildingBlocks.SilverwolfsBlocksItemGroup.instance)));
    public static final RegistryObject<Item> LIME_LIGHT_STICK = ITEMS.register("lime_light_stick", () -> new Item(new Item.Properties().group(SilverwolfsBuildingBlocks.SilverwolfsBlocksItemGroup.instance)));
    public static final RegistryObject<Item> MAGENTA_LIGHT_STICK = ITEMS.register("magenta_light_stick", () -> new Item(new Item.Properties().group(SilverwolfsBuildingBlocks.SilverwolfsBlocksItemGroup.instance)));
    public static final RegistryObject<Item> ORANGE_LIGHT_STICK = ITEMS.register("orange_light_stick", () -> new Item(new Item.Properties().group(SilverwolfsBuildingBlocks.SilverwolfsBlocksItemGroup.instance)));
    public static final RegistryObject<Item> PINK_LIGHT_STICK = ITEMS.register("pink_light_stick", () -> new Item(new Item.Properties().group(SilverwolfsBuildingBlocks.SilverwolfsBlocksItemGroup.instance)));
    public static final RegistryObject<Item> PURPLE_LIGHT_STICK = ITEMS.register("purple_light_stick", () -> new Item(new Item.Properties().group(SilverwolfsBuildingBlocks.SilverwolfsBlocksItemGroup.instance)));
    public static final RegistryObject<Item> RED_LIGHT_STICK = ITEMS.register("red_light_stick", () -> new Item(new Item.Properties().group(SilverwolfsBuildingBlocks.SilverwolfsBlocksItemGroup.instance)));
    public static final RegistryObject<Item> WHITE_LIGHT_STICK = ITEMS.register("white_light_stick", () -> new Item(new Item.Properties().group(SilverwolfsBuildingBlocks.SilverwolfsBlocksItemGroup.instance)));
    public static final RegistryObject<Item> YELLOW_LIGHT_STICK = ITEMS.register("yellow_light_stick", () -> new Item(new Item.Properties().group(SilverwolfsBuildingBlocks.SilverwolfsBlocksItemGroup.instance)));
    public static final RegistryObject<Item> BLACK_MEDIUM_STICK = ITEMS.register("black_medium_stick", () -> new Item(new Item.Properties().group(SilverwolfsBuildingBlocks.SilverwolfsBlocksItemGroup.instance)));
    public static final RegistryObject<Item> BLUE_MEDIUM_STICK = ITEMS.register("blue_medium_stick", () -> new Item(new Item.Properties().group(SilverwolfsBuildingBlocks.SilverwolfsBlocksItemGroup.instance)));
    public static final RegistryObject<Item> BROWN_MEDIUM_STICK = ITEMS.register("brown_medium_stick", () -> new Item(new Item.Properties().group(SilverwolfsBuildingBlocks.SilverwolfsBlocksItemGroup.instance)));
    public static final RegistryObject<Item> CYAN_MEDIUM_STICK = ITEMS.register("cyan_medium_stick", () -> new Item(new Item.Properties().group(SilverwolfsBuildingBlocks.SilverwolfsBlocksItemGroup.instance)));
    public static final RegistryObject<Item> GRAY_MEDIUM_STICK = ITEMS.register("gray_medium_stick", () -> new Item(new Item.Properties().group(SilverwolfsBuildingBlocks.SilverwolfsBlocksItemGroup.instance)));
    public static final RegistryObject<Item> GREEN_MEDIUM_STICK = ITEMS.register("green_medium_stick", () -> new Item(new Item.Properties().group(SilverwolfsBuildingBlocks.SilverwolfsBlocksItemGroup.instance)));
    public static final RegistryObject<Item> LIGHT_BLUE_MEDIUM_STICK = ITEMS.register("light_blue_medium_stick", () -> new Item(new Item.Properties().group(SilverwolfsBuildingBlocks.SilverwolfsBlocksItemGroup.instance)));
    public static final RegistryObject<Item> LIGHT_GRAY_MEDIUM_STICK = ITEMS.register("light_gray_medium_stick", () -> new Item(new Item.Properties().group(SilverwolfsBuildingBlocks.SilverwolfsBlocksItemGroup.instance)));
    public static final RegistryObject<Item> LIME_MEDIUM_STICK = ITEMS.register("lime_medium_stick", () -> new Item(new Item.Properties().group(SilverwolfsBuildingBlocks.SilverwolfsBlocksItemGroup.instance)));
    public static final RegistryObject<Item> MAGENTA_MEDIUM_STICK = ITEMS.register("magenta_medium_stick", () -> new Item(new Item.Properties().group(SilverwolfsBuildingBlocks.SilverwolfsBlocksItemGroup.instance)));
    public static final RegistryObject<Item> ORANGE_MEDIUM_STICK = ITEMS.register("orange_medium_stick", () -> new Item(new Item.Properties().group(SilverwolfsBuildingBlocks.SilverwolfsBlocksItemGroup.instance)));
    public static final RegistryObject<Item> PINK_MEDIUM_STICK = ITEMS.register("pink_medium_stick", () -> new Item(new Item.Properties().group(SilverwolfsBuildingBlocks.SilverwolfsBlocksItemGroup.instance)));
    public static final RegistryObject<Item> PURPLE_MEDIUM_STICK = ITEMS.register("purple_medium_stick", () -> new Item(new Item.Properties().group(SilverwolfsBuildingBlocks.SilverwolfsBlocksItemGroup.instance)));
    public static final RegistryObject<Item> RED_MEDIUM_STICK = ITEMS.register("red_medium_stick", () -> new Item(new Item.Properties().group(SilverwolfsBuildingBlocks.SilverwolfsBlocksItemGroup.instance)));
    public static final RegistryObject<Item> WHITE_MEDIUM_STICK = ITEMS.register("white_medium_stick", () -> new Item(new Item.Properties().group(SilverwolfsBuildingBlocks.SilverwolfsBlocksItemGroup.instance)));
    public static final RegistryObject<Item> YELLOW_MEDIUM_STICK = ITEMS.register("yellow_medium_stick", () -> new Item(new Item.Properties().group(SilverwolfsBuildingBlocks.SilverwolfsBlocksItemGroup.instance)));
    public static final RegistryObject<Item> BLACK_DARK_STICK = ITEMS.register("black_dark_stick", () -> new Item(new Item.Properties().group(SilverwolfsBuildingBlocks.SilverwolfsBlocksItemGroup.instance)));
    public static final RegistryObject<Item> BLUE_DARK_STICK = ITEMS.register("blue_dark_stick", () -> new Item(new Item.Properties().group(SilverwolfsBuildingBlocks.SilverwolfsBlocksItemGroup.instance)));
    public static final RegistryObject<Item> BROWN_DARK_STICK = ITEMS.register("brown_dark_stick", () -> new Item(new Item.Properties().group(SilverwolfsBuildingBlocks.SilverwolfsBlocksItemGroup.instance)));
    public static final RegistryObject<Item> CYAN_DARK_STICK = ITEMS.register("cyan_dark_stick", () -> new Item(new Item.Properties().group(SilverwolfsBuildingBlocks.SilverwolfsBlocksItemGroup.instance)));
    public static final RegistryObject<Item> GRAY_DARK_STICK = ITEMS.register("gray_dark_stick", () -> new Item(new Item.Properties().group(SilverwolfsBuildingBlocks.SilverwolfsBlocksItemGroup.instance)));
    public static final RegistryObject<Item> GREEN_DARK_STICK = ITEMS.register("green_dark_stick", () -> new Item(new Item.Properties().group(SilverwolfsBuildingBlocks.SilverwolfsBlocksItemGroup.instance)));
    public static final RegistryObject<Item> LIGHT_BLUE_DARK_STICK = ITEMS.register("light_blue_dark_stick", () -> new Item(new Item.Properties().group(SilverwolfsBuildingBlocks.SilverwolfsBlocksItemGroup.instance)));
    public static final RegistryObject<Item> LIGHT_GRAY_DARK_STICK = ITEMS.register("light_gray_dark_stick", () -> new Item(new Item.Properties().group(SilverwolfsBuildingBlocks.SilverwolfsBlocksItemGroup.instance)));
    public static final RegistryObject<Item> LIME_DARK_STICK = ITEMS.register("lime_dark_stick", () -> new Item(new Item.Properties().group(SilverwolfsBuildingBlocks.SilverwolfsBlocksItemGroup.instance)));
    public static final RegistryObject<Item> MAGENTA_DARK_STICK = ITEMS.register("magenta_dark_stick", () -> new Item(new Item.Properties().group(SilverwolfsBuildingBlocks.SilverwolfsBlocksItemGroup.instance)));
    public static final RegistryObject<Item> ORANGE_DARK_STICK = ITEMS.register("orange_dark_stick", () -> new Item(new Item.Properties().group(SilverwolfsBuildingBlocks.SilverwolfsBlocksItemGroup.instance)));
    public static final RegistryObject<Item> PINK_DARK_STICK = ITEMS.register("pink_dark_stick", () -> new Item(new Item.Properties().group(SilverwolfsBuildingBlocks.SilverwolfsBlocksItemGroup.instance)));
    public static final RegistryObject<Item> PURPLE_DARK_STICK = ITEMS.register("purple_dark_stick", () -> new Item(new Item.Properties().group(SilverwolfsBuildingBlocks.SilverwolfsBlocksItemGroup.instance)));
    public static final RegistryObject<Item> RED_DARK_STICK = ITEMS.register("red_dark_stick", () -> new Item(new Item.Properties().group(SilverwolfsBuildingBlocks.SilverwolfsBlocksItemGroup.instance)));
    public static final RegistryObject<Item> WHITE_DARK_STICK = ITEMS.register("white_dark_stick", () -> new Item(new Item.Properties().group(SilverwolfsBuildingBlocks.SilverwolfsBlocksItemGroup.instance)));
    public static final RegistryObject<Item> YELLOW_DARK_STICK = ITEMS.register("yellow_dark_stick", () -> new Item(new Item.Properties().group(SilverwolfsBuildingBlocks.SilverwolfsBlocksItemGroup.instance)));



}

