package mod.silverwolf.silverwolfsbuildingblocks.init;

import mod.silverwolf.silverwolfsbuildingblocks.SilverwolfsBuildingBlocks;
import net.minecraft.core.particles.ParticleTypes;
import net.minecraft.world.item.BlockItem;
import net.minecraft.world.item.Item;
import net.minecraft.world.level.block.*;
import net.minecraft.world.level.block.state.BlockBehaviour;
import net.minecraft.world.level.block.state.properties.BlockSetType;
import net.minecraft.world.level.block.state.properties.WoodType;
import net.minecraftforge.eventbus.api.IEventBus;
import net.minecraftforge.registries.DeferredRegister;
import net.minecraftforge.registries.ForgeRegistries;
import net.minecraftforge.registries.RegistryObject;

import java.util.function.Supplier;

public class BlockInit {
    public static final DeferredRegister<Block> BLOCKS = DeferredRegister.create(ForgeRegistries.BLOCKS, SilverwolfsBuildingBlocks.MODID);

    private static <T extends Block> RegistryObject<T> registerBlock(String name, Supplier<T> block) {
        RegistryObject<T> toReturn = BLOCKS.register(name, block);
        registerBlockItem(name, toReturn);
        return toReturn;
    }

    private static <T extends Block> void registerBlockItem(String name, RegistryObject<T> block) {
        ItemInit.ITEMS.register(name, () -> new BlockItem(block.get(), new Item.Properties()));
    }

    public static void register(IEventBus eventBus) {
        BLOCKS.register(eventBus);
    }
    public static final RegistryObject<Block> BAMBOO_BLOCK = registerBlock("bamboo_block", () -> new RotatedPillarBlock(BlockBehaviour.Properties.ofFullCopy(Blocks.HAY_BLOCK).strength(0.5f).sound(SoundType.BAMBOO)));
    public static final RegistryObject<ButtonBlock> BAMBOO_BUTTON = registerBlock("bamboo_button", () -> new ButtonBlock(BlockSetType.OAK, 30, BlockBehaviour.Properties.ofFullCopy(BAMBOO_BLOCK.get()).strength(0.5f).sound(SoundType.BAMBOO).noCollission()));
    public static final RegistryObject<DoorBlock> BAMBOO_DOOR = registerBlock("bamboo_door", () -> new DoorBlock(new BlockSetType("oak"), BlockBehaviour.Properties.ofFullCopy(BAMBOO_BLOCK.get()).strength(0.5f).sound(SoundType.BAMBOO).noOcclusion()));
    public static final RegistryObject<FenceBlock> BAMBOO_FENCE = registerBlock("bamboo_fence", () -> new FenceBlock(BlockBehaviour.Properties.ofFullCopy(BAMBOO_BLOCK.get()).strength(0.5f).sound(SoundType.BAMBOO)));
    public static final RegistryObject<FenceGateBlock> BAMBOO_FENCE_GATE = registerBlock("bamboo_fence_gate", () -> new FenceGateBlock(WoodType.OAK, BlockBehaviour.Properties.ofFullCopy(BAMBOO_BLOCK.get()).strength(0.5f).sound(SoundType.BAMBOO)));
    public static final RegistryObject<LadderBlock> BAMBOO_LADDER = registerBlock("bamboo_ladder", () -> new LadderBlock(BlockBehaviour.Properties.ofFullCopy(BAMBOO_BLOCK.get()).strength(0.5f).sound(SoundType.BAMBOO).noOcclusion()));
    public static final RegistryObject<PressurePlateBlock>  BAMBOO_PRESSURE_PLATE = registerBlock("bamboo_pressure_plate", () -> new PressurePlateBlock(new BlockSetType("oak"), BlockBehaviour.Properties.ofFullCopy(BAMBOO_BLOCK.get()).strength(0.5f).sound(SoundType.BAMBOO).noCollission()));
    public static final RegistryObject<SlabBlock>  BAMBOO_SLAB = registerBlock("bamboo_slab", () -> new SlabBlock(BlockBehaviour.Properties.ofFullCopy(BAMBOO_BLOCK.get()).strength(0.5f).sound(SoundType.BAMBOO)));
    public static final RegistryObject<StairBlock> BAMBOO_STAIRS = registerBlock("bamboo_stairs", () -> new StairBlock(BlockInit.BAMBOO_BLOCK.get().defaultBlockState(), BlockBehaviour.Properties.ofFullCopy(BAMBOO_BLOCK.get()).strength(0.5f).sound(SoundType.BAMBOO)));
    public static final RegistryObject<TrapDoorBlock> BAMBOO_TRAPDOOR = registerBlock("bamboo_trapdoor", () -> new TrapDoorBlock(BlockSetType.OAK, BlockBehaviour.Properties.ofFullCopy(BAMBOO_BLOCK.get()).strength(0.5f).sound(SoundType.BAMBOO).noOcclusion()));

    public static final RegistryObject<Block> THATCH_BLOCK = registerBlock("thatch_block", () -> new RotatedPillarBlock(BlockBehaviour.Properties.ofFullCopy(Blocks.HAY_BLOCK).strength(0.5f).sound(SoundType.CROP)));
    public static final RegistryObject<ButtonBlock> THATCH_BUTTON = registerBlock("thatch_button", () -> new ButtonBlock(BlockSetType.OAK, 30, BlockBehaviour.Properties.ofFullCopy(THATCH_BLOCK.get()).strength(0.5f).sound(SoundType.CROP).noCollission()));
    public static final RegistryObject<DoorBlock> THATCH_DOOR = registerBlock("thatch_door", () -> new DoorBlock(new BlockSetType("oak"), BlockBehaviour.Properties.ofFullCopy(THATCH_BLOCK.get()).strength(0.5f).sound(SoundType.CROP).noOcclusion()));
    public static final RegistryObject<FenceBlock> THATCH_FENCE = registerBlock("thatch_fence", () -> new FenceBlock(BlockBehaviour.Properties.ofFullCopy(THATCH_BLOCK.get()).strength(0.5f).sound(SoundType.CROP)));
    public static final RegistryObject<FenceGateBlock> THATCH_FENCE_GATE = registerBlock("thatch_fence_gate", () -> new FenceGateBlock(WoodType.OAK, BlockBehaviour.Properties.ofFullCopy(THATCH_BLOCK.get()).strength(0.5f).sound(SoundType.CROP)));
    public static final RegistryObject<LadderBlock> THATCH_LADDER = registerBlock("thatch_ladder", () -> new LadderBlock(BlockBehaviour.Properties.ofFullCopy(THATCH_BLOCK.get()).strength(0.5f).sound(SoundType.CROP).noOcclusion()));
    public static final RegistryObject<PressurePlateBlock>  THATCH_PRESSURE_PLATE = registerBlock("thatch_pressure_plate", () -> new PressurePlateBlock(new BlockSetType("oak"), BlockBehaviour.Properties.ofFullCopy(THATCH_BLOCK.get()).strength(0.5f).sound(SoundType.CROP).noCollission()));
    public static final RegistryObject<SlabBlock>  THATCH_SLAB = registerBlock("thatch_slab", () -> new SlabBlock(BlockBehaviour.Properties.ofFullCopy(THATCH_BLOCK.get()).strength(0.5f).sound(SoundType.CROP)));
    public static final RegistryObject<StairBlock> THATCH_STAIRS = registerBlock("thatch_stairs", () -> new StairBlock(BlockInit.THATCH_BLOCK.get().defaultBlockState(), BlockBehaviour.Properties.ofFullCopy(THATCH_BLOCK.get()).strength(0.5f).sound(SoundType.CROP)));
    public static final RegistryObject<TrapDoorBlock> THATCH_TRAPDOOR = registerBlock("thatch_trapdoor", () -> new TrapDoorBlock(BlockSetType.OAK, BlockBehaviour.Properties.ofFullCopy(THATCH_BLOCK.get()).strength(0.5f).sound(SoundType.CROP).noOcclusion()));

    public static final RegistryObject<Block> ACACIA_BEAM_UP = registerBlock("acacia_beam_up", () -> new RotatedPillarBlock(BlockBehaviour.Properties.ofFullCopy(Blocks.ACACIA_WOOD).strength(2.0f, 3.0f).sound(SoundType.WOOD)));
    public static final RegistryObject<Block> ACACIA_BEAM_MIDDLE = registerBlock("acacia_beam_middle", () -> new RotatedPillarBlock(BlockBehaviour.Properties.ofFullCopy(Blocks.ACACIA_WOOD).strength(2.0f, 3.0f).sound(SoundType.WOOD)));
    public static final RegistryObject<Block> ACACIA_BEAM_DOWN = registerBlock("acacia_beam_down", () -> new RotatedPillarBlock(BlockBehaviour.Properties.ofFullCopy(Blocks.ACACIA_WOOD).strength(2.0f, 3.0f).sound(SoundType.WOOD)));
    public static final RegistryObject<Block> BIRCH_BEAM_UP = registerBlock("birch_beam_up", () -> new RotatedPillarBlock(BlockBehaviour.Properties.ofFullCopy(Blocks.BIRCH_WOOD).strength(2.0f, 3.0f).sound(SoundType.WOOD)));
    public static final RegistryObject<Block> BIRCH_BEAM_MIDDLE = registerBlock("birch_beam_middle", () -> new RotatedPillarBlock(BlockBehaviour.Properties.ofFullCopy(Blocks.BIRCH_WOOD).strength(2.0f, 3.0f).sound(SoundType.WOOD)));
    public static final RegistryObject<Block> BIRCH_BEAM_DOWN = registerBlock("birch_beam_down", () -> new RotatedPillarBlock(BlockBehaviour.Properties.ofFullCopy(Blocks.BIRCH_WOOD).strength(2.0f, 3.0f).sound(SoundType.WOOD)));
    public static final RegistryObject<Block> CHERRY_BEAM_UP = registerBlock("cherry_beam_up", () -> new RotatedPillarBlock(BlockBehaviour.Properties.ofFullCopy(Blocks.CHERRY_WOOD).strength(2.0f, 3.0f).sound(SoundType.WOOD)));
    public static final RegistryObject<Block> CHERRY_BEAM_MIDDLE = registerBlock("cherry_beam_middle", () -> new RotatedPillarBlock(BlockBehaviour.Properties.ofFullCopy(Blocks.CHERRY_WOOD).strength(2.0f, 3.0f).sound(SoundType.WOOD)));
    public static final RegistryObject<Block> CHERRY_BEAM_DOWN = registerBlock("cherry_beam_down", () -> new RotatedPillarBlock(BlockBehaviour.Properties.ofFullCopy(Blocks.CHERRY_WOOD).strength(2.0f, 3.0f).sound(SoundType.WOOD)));
    public static final RegistryObject<Block> CRIMSON_BEAM_UP = registerBlock("crimson_beam_up", () -> new RotatedPillarBlock(BlockBehaviour.Properties.ofFullCopy(Blocks.CRIMSON_HYPHAE).strength(2.0f, 3.0f).sound(SoundType.WOOD)));
    public static final RegistryObject<Block> CRIMSON_BEAM_MIDDLE = registerBlock("crimson_beam_middle", () -> new RotatedPillarBlock(BlockBehaviour.Properties.ofFullCopy(Blocks.CRIMSON_HYPHAE).strength(2.0f, 3.0f).sound(SoundType.WOOD)));
    public static final RegistryObject<Block> CRIMSON_BEAM_DOWN = registerBlock("crimson_beam_down", () -> new RotatedPillarBlock(BlockBehaviour.Properties.ofFullCopy(Blocks.CRIMSON_HYPHAE).strength(2.0f, 3.0f).sound(SoundType.WOOD)));
    public static final RegistryObject<Block> DARK_OAK_BEAM_UP = registerBlock("dark_oak_beam_up", () -> new RotatedPillarBlock(BlockBehaviour.Properties.ofFullCopy(Blocks.DARK_OAK_WOOD).strength(2.0f, 3.0f).sound(SoundType.WOOD)));
    public static final RegistryObject<Block> DARK_OAK_BEAM_MIDDLE = registerBlock("dark_oak_beam_middle", () -> new RotatedPillarBlock(BlockBehaviour.Properties.ofFullCopy(Blocks.DARK_OAK_WOOD).strength(2.0f, 3.0f).sound(SoundType.WOOD)));
    public static final RegistryObject<Block> DARK_OAK_BEAM_DOWN = registerBlock("dark_oak_beam_down", () -> new RotatedPillarBlock(BlockBehaviour.Properties.ofFullCopy(Blocks.DARK_OAK_WOOD).strength(2.0f, 3.0f).sound(SoundType.WOOD)));
    public static final RegistryObject<Block> JUNGLE_BEAM_UP = registerBlock("jungle_beam_up", () -> new RotatedPillarBlock(BlockBehaviour.Properties.ofFullCopy(Blocks.JUNGLE_WOOD).strength(2.0f, 3.0f).sound(SoundType.WOOD)));
    public static final RegistryObject<Block> JUNGLE_BEAM_MIDDLE = registerBlock("jungle_beam_middle", () -> new RotatedPillarBlock(BlockBehaviour.Properties.ofFullCopy(Blocks.JUNGLE_WOOD).strength(2.0f, 3.0f).sound(SoundType.WOOD)));
    public static final RegistryObject<Block> JUNGLE_BEAM_DOWN = registerBlock("jungle_beam_down", () -> new RotatedPillarBlock(BlockBehaviour.Properties.ofFullCopy(Blocks.JUNGLE_WOOD).strength(2.0f, 3.0f).sound(SoundType.WOOD)));
    public static final RegistryObject<Block> MANGROVE_BEAM_UP = registerBlock("mangrove_beam_up", () -> new RotatedPillarBlock(BlockBehaviour.Properties.ofFullCopy(Blocks.MANGROVE_WOOD).strength(2.0f, 3.0f).sound(SoundType.WOOD)));
    public static final RegistryObject<Block> MANGROVE_BEAM_MIDDLE = registerBlock("mangrove_beam_middle", () -> new RotatedPillarBlock(BlockBehaviour.Properties.ofFullCopy(Blocks.MANGROVE_WOOD).strength(2.0f, 3.0f).sound(SoundType.WOOD)));
    public static final RegistryObject<Block> MANGROVE_BEAM_DOWN = registerBlock("mangrove_beam_down", () -> new RotatedPillarBlock(BlockBehaviour.Properties.ofFullCopy(Blocks.MANGROVE_WOOD).strength(2.0f, 3.0f).sound(SoundType.WOOD)));
    public static final RegistryObject<Block> OAK_BEAM_UP = registerBlock("oak_beam_up", () -> new RotatedPillarBlock(BlockBehaviour.Properties.ofFullCopy(Blocks.OAK_WOOD).strength(2.0f, 3.0f).sound(SoundType.WOOD)));
    public static final RegistryObject<Block> OAK_BEAM_MIDDLE = registerBlock("oak_beam_middle", () -> new RotatedPillarBlock(BlockBehaviour.Properties.ofFullCopy(Blocks.OAK_WOOD).strength(2.0f, 3.0f).sound(SoundType.WOOD)));
    public static final RegistryObject<Block> OAK_BEAM_DOWN = registerBlock("oak_beam_down", () -> new RotatedPillarBlock(BlockBehaviour.Properties.ofFullCopy(Blocks.OAK_WOOD).strength(2.0f, 3.0f).sound(SoundType.WOOD)));
    public static final RegistryObject<Block> SPRUCE_BEAM_UP = registerBlock("spruce_beam_up", () -> new RotatedPillarBlock(BlockBehaviour.Properties.ofFullCopy(Blocks.SPRUCE_WOOD).strength(2.0f, 3.0f).sound(SoundType.WOOD)));
    public static final RegistryObject<Block> SPRUCE_BEAM_MIDDLE = registerBlock("spruce_beam_middle", () -> new RotatedPillarBlock(BlockBehaviour.Properties.ofFullCopy(Blocks.SPRUCE_WOOD).strength(2.0f, 3.0f).sound(SoundType.WOOD)));
    public static final RegistryObject<Block> SPRUCE_BEAM_DOWN = registerBlock("spruce_beam_down", () -> new RotatedPillarBlock(BlockBehaviour.Properties.ofFullCopy(Blocks.SPRUCE_WOOD).strength(2.0f, 3.0f).sound(SoundType.WOOD)));
    public static final RegistryObject<Block> WARPED_BEAM_UP = registerBlock("warped_beam_up", () -> new RotatedPillarBlock(BlockBehaviour.Properties.ofFullCopy(Blocks.WARPED_HYPHAE).strength(2.0f, 3.0f).sound(SoundType.WOOD)));
    public static final RegistryObject<Block> WARPED_BEAM_MIDDLE = registerBlock("warped_beam_middle", () -> new RotatedPillarBlock(BlockBehaviour.Properties.ofFullCopy(Blocks.WARPED_HYPHAE).strength(2.0f, 3.0f).sound(SoundType.WOOD)));
    public static final RegistryObject<Block> WARPED_BEAM_DOWN = registerBlock("warped_beam_down", () -> new RotatedPillarBlock(BlockBehaviour.Properties.ofFullCopy(Blocks.WARPED_HYPHAE).strength(2.0f, 3.0f).sound(SoundType.WOOD)));

    public static final RegistryObject<LadderBlock> ACACIA_LADDER = registerBlock("acacia_ladder", () -> new LadderBlock(BlockBehaviour.Properties.ofFullCopy(Blocks.LADDER).strength(0.5f).sound(SoundType.LADDER).noOcclusion()));
    public static final RegistryObject<LadderBlock> BIRCH_LADDER = registerBlock("birch_ladder", () -> new LadderBlock(BlockBehaviour.Properties.ofFullCopy(Blocks.LADDER).strength(0.5f).sound(SoundType.LADDER).noOcclusion()));
    public static final RegistryObject<LadderBlock> CHERRY_LADDER = registerBlock("cherry_ladder", () -> new LadderBlock(BlockBehaviour.Properties.ofFullCopy(Blocks.LADDER).strength(0.5f).sound(SoundType.LADDER).noOcclusion()));
    public static final RegistryObject<LadderBlock> CRIMSON_LADDER = registerBlock("crimson_ladder", () -> new LadderBlock(BlockBehaviour.Properties.ofFullCopy(Blocks.LADDER).strength(0.5f).sound(SoundType.LADDER).noOcclusion()));
    public static final RegistryObject<LadderBlock> DARK_OAK_LADDER = registerBlock("dark_oak_ladder", () -> new LadderBlock(BlockBehaviour.Properties.ofFullCopy(Blocks.LADDER).strength(0.5f).sound(SoundType.LADDER).noOcclusion()));
    public static final RegistryObject<LadderBlock> JUNGLE_LADDER = registerBlock("jungle_ladder", () -> new LadderBlock(BlockBehaviour.Properties.ofFullCopy(Blocks.LADDER).strength(0.5f).sound(SoundType.LADDER).noOcclusion()));
    public static final RegistryObject<LadderBlock> MANGROVE_LADDER = registerBlock("mangrove_ladder", () -> new LadderBlock(BlockBehaviour.Properties.ofFullCopy(Blocks.LADDER).strength(0.5f).sound(SoundType.LADDER).noOcclusion()));
    public static final RegistryObject<LadderBlock> OAK_LADDER = registerBlock("oak_ladder", () -> new LadderBlock(BlockBehaviour.Properties.ofFullCopy(Blocks.LADDER).strength(0.5f).sound(SoundType.LADDER).noOcclusion()));
    public static final RegistryObject<LadderBlock> SPRUCE_LADDER = registerBlock("spruce_ladder", () -> new LadderBlock(BlockBehaviour.Properties.ofFullCopy(Blocks.LADDER).strength(0.5f).sound(SoundType.LADDER).noOcclusion()));
    public static final RegistryObject<LadderBlock> WARPED_LADDER = registerBlock("warped_ladder", () -> new LadderBlock(BlockBehaviour.Properties.ofFullCopy(Blocks.LADDER).strength(0.5f).sound(SoundType.LADDER).noOcclusion()));

    public static final RegistryObject<TorchBlock> ACACIA_TORCH = registerBlock("acacia_torch", () -> new TorchBlock(ParticleTypes.FLAME, BlockBehaviour.Properties.ofFullCopy(Blocks.TORCH).noCollission().instabreak().lightLevel((state) -> 14).sound(SoundType.WOOD)));
    public static final RegistryObject<WallTorchBlock> ACACIA_WALL_TORCH = registerBlock("acacia_wall_torch", () -> new WallTorchBlock(ParticleTypes.FLAME, BlockBehaviour.Properties.ofFullCopy(Blocks.WALL_TORCH).noCollission().instabreak().lightLevel((state) -> 14).sound(SoundType.WOOD).dropsLike(ACACIA_TORCH.get())));
    public static final RegistryObject<TorchBlock> BIRCH_TORCH = registerBlock("birch_torch", () -> new TorchBlock(ParticleTypes.FLAME, BlockBehaviour.Properties.ofFullCopy(Blocks.TORCH).noCollission().instabreak().lightLevel((state) -> 14).sound(SoundType.WOOD)));
    public static final RegistryObject<WallTorchBlock> BIRCH_WALL_TORCH = registerBlock("birch_wall_torch", () -> new WallTorchBlock(ParticleTypes.FLAME, BlockBehaviour.Properties.ofFullCopy(Blocks.WALL_TORCH).noCollission().instabreak().lightLevel((state) -> 14).sound(SoundType.WOOD).dropsLike(BIRCH_TORCH.get())));
    public static final RegistryObject<TorchBlock> CHERRY_TORCH = registerBlock("cherry_torch", () -> new TorchBlock(ParticleTypes.FLAME, BlockBehaviour.Properties.ofFullCopy(Blocks.TORCH).noCollission().instabreak().lightLevel((state) -> 14).sound(SoundType.WOOD)));
    public static final RegistryObject<WallTorchBlock> CHERRY_WALL_TORCH = registerBlock("cherry_wall_torch", () -> new WallTorchBlock(ParticleTypes.FLAME, BlockBehaviour.Properties.ofFullCopy(Blocks.WALL_TORCH).noCollission().instabreak().lightLevel((state) -> 14).sound(SoundType.WOOD).dropsLike(CHERRY_TORCH.get())));
    public static final RegistryObject<TorchBlock> CRIMSON_TORCH = registerBlock("crimson_torch", () -> new TorchBlock(ParticleTypes.FLAME, BlockBehaviour.Properties.ofFullCopy(Blocks.TORCH).noCollission().instabreak().lightLevel((state) -> 14).sound(SoundType.WOOD)));
    public static final RegistryObject<WallTorchBlock> CRIMSON_WALL_TORCH = registerBlock("crimson_wall_torch", () -> new WallTorchBlock(ParticleTypes.FLAME, BlockBehaviour.Properties.ofFullCopy(Blocks.WALL_TORCH).noCollission().instabreak().lightLevel((state) -> 14).sound(SoundType.WOOD).dropsLike(CRIMSON_TORCH.get())));
    public static final RegistryObject<TorchBlock> DARK_OAK_TORCH = registerBlock("dark_oak_torch", () -> new TorchBlock(ParticleTypes.FLAME, BlockBehaviour.Properties.ofFullCopy(Blocks.TORCH).noCollission().instabreak().lightLevel((state) -> 14).sound(SoundType.WOOD)));
    public static final RegistryObject<WallTorchBlock> DARK_OAK_WALL_TORCH = registerBlock("dark_oak_wall_torch", () -> new WallTorchBlock(ParticleTypes.FLAME, BlockBehaviour.Properties.ofFullCopy(Blocks.WALL_TORCH).noCollission().instabreak().lightLevel((state) -> 14).sound(SoundType.WOOD).dropsLike(DARK_OAK_TORCH.get())));
    public static final RegistryObject<TorchBlock> JUNGLE_TORCH = registerBlock("jungle_torch", () -> new TorchBlock(ParticleTypes.FLAME, BlockBehaviour.Properties.ofFullCopy(Blocks.TORCH).noCollission().instabreak().lightLevel((state) -> 14).sound(SoundType.WOOD)));
    public static final RegistryObject<WallTorchBlock> JUNGLE_WALL_TORCH = registerBlock("jungle_wall_torch", () -> new WallTorchBlock(ParticleTypes.FLAME, BlockBehaviour.Properties.ofFullCopy(Blocks.WALL_TORCH).noCollission().instabreak().lightLevel((state) -> 14).sound(SoundType.WOOD).dropsLike(JUNGLE_TORCH.get())));
    public static final RegistryObject<TorchBlock> MANGROVE_TORCH = registerBlock("mangrove_torch", () -> new TorchBlock(ParticleTypes.FLAME, BlockBehaviour.Properties.ofFullCopy(Blocks.TORCH).noCollission().instabreak().lightLevel((state) -> 14).sound(SoundType.WOOD)));
    public static final RegistryObject<WallTorchBlock> MANGROVE_WALL_TORCH = registerBlock("mangrove_wall_torch", () -> new WallTorchBlock(ParticleTypes.FLAME, BlockBehaviour.Properties.ofFullCopy(Blocks.WALL_TORCH).noCollission().instabreak().lightLevel((state) -> 14).sound(SoundType.WOOD).dropsLike(MANGROVE_TORCH.get())));
    public static final RegistryObject<TorchBlock> OAK_TORCH = registerBlock("oak_torch", () -> new TorchBlock(ParticleTypes.FLAME, BlockBehaviour.Properties.ofFullCopy(Blocks.TORCH).noCollission().instabreak().lightLevel((state) -> 14).sound(SoundType.WOOD)));
    public static final RegistryObject<WallTorchBlock> OAK_WALL_TORCH = registerBlock("oak_wall_torch", () -> new WallTorchBlock(ParticleTypes.FLAME, BlockBehaviour.Properties.ofFullCopy(Blocks.WALL_TORCH).noCollission().instabreak().lightLevel((state) -> 14).sound(SoundType.WOOD).dropsLike(OAK_TORCH.get())));
    public static final RegistryObject<TorchBlock> SPRUCE_TORCH = registerBlock("spruce_torch", () -> new TorchBlock(ParticleTypes.FLAME, BlockBehaviour.Properties.ofFullCopy(Blocks.TORCH).noCollission().instabreak().lightLevel((state) -> 14).sound(SoundType.WOOD)));
    public static final RegistryObject<WallTorchBlock> SPRUCE_WALL_TORCH = registerBlock("spruce_wall_torch", () -> new WallTorchBlock(ParticleTypes.FLAME, BlockBehaviour.Properties.ofFullCopy(Blocks.WALL_TORCH).noCollission().instabreak().lightLevel((state) -> 14).sound(SoundType.WOOD).dropsLike(SPRUCE_TORCH.get())));
    public static final RegistryObject<TorchBlock> WARPED_TORCH = registerBlock("warped_torch", () -> new TorchBlock(ParticleTypes.FLAME, BlockBehaviour.Properties.ofFullCopy(Blocks.TORCH).noCollission().instabreak().lightLevel((state) -> 14).sound(SoundType.WOOD)));
    public static final RegistryObject<WallTorchBlock> WARPED_WALL_TORCH = registerBlock("warped_wall_torch", () -> new WallTorchBlock(ParticleTypes.FLAME, BlockBehaviour.Properties.ofFullCopy(Blocks.WALL_TORCH).noCollission().instabreak().lightLevel((state) -> 14).sound(SoundType.WOOD).dropsLike(WARPED_TORCH.get())));

    public static final RegistryObject<TorchBlock> ACACIA_SOUL_TORCH = registerBlock("acacia_soul_torch", () -> new TorchBlock(ParticleTypes.SOUL_FIRE_FLAME, BlockBehaviour.Properties.ofFullCopy(Blocks.TORCH).noCollission().instabreak().lightLevel((state) -> 10).sound(SoundType.WOOD)));
    public static final RegistryObject<WallTorchBlock> ACACIA_WALL_SOUL_TORCH = registerBlock("acacia_wall_soul_torch", () -> new WallTorchBlock(ParticleTypes.SOUL_FIRE_FLAME, BlockBehaviour.Properties.ofFullCopy(Blocks.WALL_TORCH).noCollission().instabreak().lightLevel((state) -> 10).sound(SoundType.WOOD).dropsLike(ACACIA_SOUL_TORCH.get())));
    public static final RegistryObject<TorchBlock> BIRCH_SOUL_TORCH = registerBlock("birch_soul_torch", () -> new TorchBlock(ParticleTypes.SOUL_FIRE_FLAME, BlockBehaviour.Properties.ofFullCopy(Blocks.TORCH).noCollission().instabreak().lightLevel((state) -> 10).sound(SoundType.WOOD)));
    public static final RegistryObject<WallTorchBlock> BIRCH_WALL_SOUL_TORCH = registerBlock("birch_wall_soul_torch", () -> new WallTorchBlock(ParticleTypes.SOUL_FIRE_FLAME, BlockBehaviour.Properties.ofFullCopy(Blocks.WALL_TORCH).noCollission().instabreak().lightLevel((state) -> 10).sound(SoundType.WOOD).dropsLike(BIRCH_SOUL_TORCH.get())));
    public static final RegistryObject<TorchBlock> CHERRY_SOUL_TORCH = registerBlock("cherry_soul_torch", () -> new TorchBlock(ParticleTypes.SOUL_FIRE_FLAME, BlockBehaviour.Properties.ofFullCopy(Blocks.TORCH).noCollission().instabreak().lightLevel((state) -> 10).sound(SoundType.WOOD)));
    public static final RegistryObject<WallTorchBlock> CHERRY_WALL_SOUL_TORCH = registerBlock("cherry_wall_soul_torch", () -> new WallTorchBlock(ParticleTypes.SOUL_FIRE_FLAME, BlockBehaviour.Properties.ofFullCopy(Blocks.WALL_TORCH).noCollission().instabreak().lightLevel((state) -> 10).sound(SoundType.WOOD).dropsLike(CHERRY_SOUL_TORCH.get())));
    public static final RegistryObject<TorchBlock> CRIMSON_SOUL_TORCH = registerBlock("crimson_soul_torch", () -> new TorchBlock(ParticleTypes.SOUL_FIRE_FLAME, BlockBehaviour.Properties.ofFullCopy(Blocks.TORCH).noCollission().instabreak().lightLevel((state) -> 10).sound(SoundType.WOOD)));
    public static final RegistryObject<WallTorchBlock> CRIMSON_WALL_SOUL_TORCH = registerBlock("crimson_wall_soul_torch", () -> new WallTorchBlock(ParticleTypes.SOUL_FIRE_FLAME, BlockBehaviour.Properties.ofFullCopy(Blocks.WALL_TORCH).noCollission().instabreak().lightLevel((state) -> 10).sound(SoundType.WOOD).dropsLike(CRIMSON_SOUL_TORCH.get())));
    public static final RegistryObject<TorchBlock> DARK_OAK_SOUL_TORCH = registerBlock("dark_oak_soul_torch", () -> new TorchBlock(ParticleTypes.SOUL_FIRE_FLAME, BlockBehaviour.Properties.ofFullCopy(Blocks.TORCH).noCollission().instabreak().lightLevel((state) -> 10).sound(SoundType.WOOD)));
    public static final RegistryObject<WallTorchBlock> DARK_OAK_WALL_SOUL_TORCH = registerBlock("dark_oak_wall_soul_torch", () -> new WallTorchBlock(ParticleTypes.SOUL_FIRE_FLAME, BlockBehaviour.Properties.ofFullCopy(Blocks.WALL_TORCH).noCollission().instabreak().lightLevel((state) -> 10).sound(SoundType.WOOD).dropsLike(DARK_OAK_SOUL_TORCH.get())));
    public static final RegistryObject<TorchBlock> JUNGLE_SOUL_TORCH = registerBlock("jungle_soul_torch", () -> new TorchBlock(ParticleTypes.SOUL_FIRE_FLAME, BlockBehaviour.Properties.ofFullCopy(Blocks.TORCH).noCollission().instabreak().lightLevel((state) -> 10).sound(SoundType.WOOD)));
    public static final RegistryObject<WallTorchBlock> JUNGLE_WALL_SOUL_TORCH = registerBlock("jungle_wall_soul_torch", () -> new WallTorchBlock(ParticleTypes.SOUL_FIRE_FLAME, BlockBehaviour.Properties.ofFullCopy(Blocks.WALL_TORCH).noCollission().instabreak().lightLevel((state) -> 10).sound(SoundType.WOOD).dropsLike(JUNGLE_SOUL_TORCH.get())));
    public static final RegistryObject<TorchBlock> MANGROVE_SOUL_TORCH = registerBlock("mangrove_soul_torch", () -> new TorchBlock(ParticleTypes.SOUL_FIRE_FLAME, BlockBehaviour.Properties.ofFullCopy(Blocks.TORCH).noCollission().instabreak().lightLevel((state) -> 10).sound(SoundType.WOOD)));
    public static final RegistryObject<WallTorchBlock> MANGROVE_WALL_SOUL_TORCH = registerBlock("mangrove_wall_soul_torch", () -> new WallTorchBlock(ParticleTypes.SOUL_FIRE_FLAME, BlockBehaviour.Properties.ofFullCopy(Blocks.WALL_TORCH).noCollission().instabreak().lightLevel((state) -> 10).sound(SoundType.WOOD).dropsLike(MANGROVE_SOUL_TORCH.get())));
    public static final RegistryObject<TorchBlock> OAK_SOUL_TORCH = registerBlock("oak_soul_torch", () -> new TorchBlock(ParticleTypes.SOUL_FIRE_FLAME, BlockBehaviour.Properties.ofFullCopy(Blocks.TORCH).noCollission().instabreak().lightLevel((state) -> 10).sound(SoundType.WOOD)));
    public static final RegistryObject<WallTorchBlock> OAK_WALL_SOUL_TORCH = registerBlock("oak_wall_soul_torch", () -> new WallTorchBlock(ParticleTypes.SOUL_FIRE_FLAME, BlockBehaviour.Properties.ofFullCopy(Blocks.WALL_TORCH).noCollission().instabreak().lightLevel((state) -> 10).sound(SoundType.WOOD).dropsLike(OAK_SOUL_TORCH.get())));
    public static final RegistryObject<TorchBlock> SPRUCE_SOUL_TORCH = registerBlock("spruce_soul_torch", () -> new TorchBlock(ParticleTypes.SOUL_FIRE_FLAME, BlockBehaviour.Properties.ofFullCopy(Blocks.TORCH).noCollission().instabreak().lightLevel((state) -> 10).sound(SoundType.WOOD)));
    public static final RegistryObject<WallTorchBlock> SPRUCE_WALL_SOUL_TORCH = registerBlock("spruce_wall_soul_torch", () -> new WallTorchBlock(ParticleTypes.SOUL_FIRE_FLAME, BlockBehaviour.Properties.ofFullCopy(Blocks.WALL_TORCH).noCollission().instabreak().lightLevel((state) -> 10).sound(SoundType.WOOD).dropsLike(SPRUCE_SOUL_TORCH.get())));
    public static final RegistryObject<TorchBlock> WARPED_SOUL_TORCH = registerBlock("warped_soul_torch", () -> new TorchBlock(ParticleTypes.SOUL_FIRE_FLAME, BlockBehaviour.Properties.ofFullCopy(Blocks.TORCH).noCollission().instabreak().lightLevel((state) -> 10).sound(SoundType.WOOD)));
    public static final RegistryObject<WallTorchBlock> WARPED_WALL_SOUL_TORCH = registerBlock("warped_wall_soul_torch", () -> new WallTorchBlock(ParticleTypes.SOUL_FIRE_FLAME, BlockBehaviour.Properties.ofFullCopy(Blocks.WALL_TORCH).noCollission().instabreak().lightLevel((state) -> 10).sound(SoundType.WOOD).dropsLike(WARPED_SOUL_TORCH.get())));

    public static final RegistryObject<Block> MOSSY_STONE = registerBlock("mossy_stone", () -> new Block(BlockBehaviour.Properties.ofFullCopy(Blocks.STONE).strength(1.5F, 6.0F).sound(SoundType.STONE).requiresCorrectToolForDrops()));
    public static final RegistryObject<ButtonBlock> MOSSY_STONE_BUTTON = registerBlock("mossy_stone_button", () -> new ButtonBlock(BlockSetType.STONE, 20, BlockBehaviour.Properties.ofFullCopy(Blocks.STONE).strength(0.5F).sound(SoundType.STONE).noCollission().requiresCorrectToolForDrops()));
    public static final RegistryObject<PressurePlateBlock> MOSSY_STONE_PRESSURE_PLATE = registerBlock("mossy_stone_pressure_plate", () -> new PressurePlateBlock(new BlockSetType("stone") ,BlockBehaviour.Properties.ofFullCopy(Blocks.STONE).strength(0.5F).sound(SoundType.STONE).noCollission().requiresCorrectToolForDrops()));
    public static final RegistryObject<SlabBlock> MOSSY_STONE_SLAB = registerBlock("mossy_stone_slab", () -> new SlabBlock(BlockBehaviour.Properties.ofFullCopy(Blocks.STONE).strength(1.5F, 6.0F).sound(SoundType.STONE).requiresCorrectToolForDrops()));
    public static final RegistryObject<StairBlock> MOSSY_STONE_STAIRS = registerBlock("mossy_stone_stairs", () -> new StairBlock(MOSSY_STONE.get().defaultBlockState(), BlockBehaviour.Properties.ofFullCopy(Blocks.STONE).strength(1.5F, 6.0F).sound(SoundType.STONE).requiresCorrectToolForDrops()));
    public static final RegistryObject<WallBlock> MOSSY_STONE_WALL = registerBlock("mossy_stone_wall", () -> new WallBlock(BlockBehaviour.Properties.ofFullCopy(Blocks.STONE).strength(1.5F, 6.0F).sound(SoundType.STONE).requiresCorrectToolForDrops()));

    public static final RegistryObject<Block> MORE_MOSSY_STONE = registerBlock("more_mossy_stone", () -> new Block(BlockBehaviour.Properties.ofFullCopy(Blocks.STONE).strength(1.5F, 6.0F).sound(SoundType.STONE).requiresCorrectToolForDrops()));
    public static final RegistryObject<ButtonBlock> MORE_MOSSY_STONE_BUTTON = registerBlock("more_mossy_stone_button", () -> new ButtonBlock(BlockSetType.STONE, 20, BlockBehaviour.Properties.ofFullCopy(Blocks.STONE).strength(0.5F).sound(SoundType.STONE).noCollission().requiresCorrectToolForDrops()));
    public static final RegistryObject<PressurePlateBlock> MORE_MOSSY_STONE_PRESSURE_PLATE = registerBlock("more_mossy_stone_pressure_plate", () -> new PressurePlateBlock(new BlockSetType("stone") ,BlockBehaviour.Properties.ofFullCopy(Blocks.STONE).strength(0.5F).sound(SoundType.STONE).noCollission().requiresCorrectToolForDrops()));
    public static final RegistryObject<SlabBlock> MORE_MOSSY_STONE_SLAB = registerBlock("more_mossy_stone_slab", () -> new SlabBlock(BlockBehaviour.Properties.ofFullCopy(Blocks.STONE).strength(1.5F, 6.0F).sound(SoundType.STONE).requiresCorrectToolForDrops()));
    public static final RegistryObject<StairBlock> MORE_MOSSY_STONE_STAIRS = registerBlock("more_mossy_stone_stairs", () -> new StairBlock(MORE_MOSSY_STONE.get().defaultBlockState(), BlockBehaviour.Properties.ofFullCopy(Blocks.STONE).strength(1.5F, 6.0F).sound(SoundType.STONE).requiresCorrectToolForDrops()));
    public static final RegistryObject<WallBlock> MORE_MOSSY_STONE_WALL = registerBlock("more_mossy_stone_wall", () -> new WallBlock(BlockBehaviour.Properties.ofFullCopy(Blocks.STONE).strength(1.5F, 6.0F).sound(SoundType.STONE).requiresCorrectToolForDrops()));

}