package mod.silverwolf.silverwolfsbuildingblocks.init;

import mod.silverwolf.silverwolfsbuildingblocks.SilverwolfsBuildingBlocks;
import net.minecraft.core.particles.ParticleTypes;
import net.minecraft.world.level.block.*;
import net.minecraft.world.level.block.state.BlockBehaviour;
import net.minecraft.world.level.block.state.properties.BlockSetType;
import net.minecraft.world.level.block.state.properties.WoodType;
import net.minecraftforge.registries.DeferredRegister;
import net.minecraftforge.registries.ForgeRegistries;
import net.minecraftforge.registries.RegistryObject;

public class BlockInit {
    public static final DeferredRegister<Block> BLOCKS = DeferredRegister.create(ForgeRegistries.BLOCKS, SilverwolfsBuildingBlocks.MODID);

    public static final RegistryObject<Block> BAMBOO_BLOCK = BLOCKS.register("bamboo_block", () -> new RotatedPillarBlock(BlockBehaviour.Properties.ofFullCopy(Blocks.HAY_BLOCK).strength(0.5f).sound(SoundType.BAMBOO)));
    public static final RegistryObject<ButtonBlock> BAMBOO_BUTTON = BLOCKS.register("bamboo_button", () -> new ButtonBlock(BlockSetType.OAK, 30, BlockBehaviour.Properties.ofFullCopy(BAMBOO_BLOCK.get()).strength(0.5f).sound(SoundType.BAMBOO).noCollission()));
    public static final RegistryObject<DoorBlock> BAMBOO_DOOR = BLOCKS.register("bamboo_door", () -> new DoorBlock(new BlockSetType("oak"), BlockBehaviour.Properties.ofFullCopy(BAMBOO_BLOCK.get()).strength(0.5f).sound(SoundType.BAMBOO).noOcclusion()));
    public static final RegistryObject<FenceBlock> BAMBOO_FENCE = BLOCKS.register("bamboo_fence", () -> new FenceBlock(BlockBehaviour.Properties.ofFullCopy(BAMBOO_BLOCK.get()).strength(0.5f).sound(SoundType.BAMBOO)));
    public static final RegistryObject<FenceGateBlock> BAMBOO_FENCE_GATE = BLOCKS.register("bamboo_fence_gate", () -> new FenceGateBlock(WoodType.OAK, BlockBehaviour.Properties.ofFullCopy(BAMBOO_BLOCK.get()).strength(0.5f).sound(SoundType.BAMBOO)));
    public static final RegistryObject<LadderBlock> BAMBOO_LADDER = BLOCKS.register("bamboo_ladder", () -> new LadderBlock(BlockBehaviour.Properties.ofFullCopy(BAMBOO_BLOCK.get()).strength(0.5f).sound(SoundType.BAMBOO).noOcclusion()));
    public static final RegistryObject<PressurePlateBlock>  BAMBOO_PRESSURE_PLATE = BLOCKS.register("bamboo_pressure_plate", () -> new PressurePlateBlock(new BlockSetType("oak"), BlockBehaviour.Properties.ofFullCopy(BAMBOO_BLOCK.get()).strength(0.5f).sound(SoundType.BAMBOO).noCollission()));
    public static final RegistryObject<SlabBlock>  BAMBOO_SLAB = BLOCKS.register("bamboo_slab", () -> new SlabBlock(BlockBehaviour.Properties.ofFullCopy(BAMBOO_BLOCK.get()).strength(0.5f).sound(SoundType.BAMBOO)));
    public static final RegistryObject<StairBlock> BAMBOO_STAIRS = BLOCKS.register("bamboo_stairs", () -> new StairBlock(BlockInit.BAMBOO_BLOCK.get().defaultBlockState(), BlockBehaviour.Properties.ofFullCopy(BAMBOO_BLOCK.get()).strength(0.5f).sound(SoundType.BAMBOO)));
    public static final RegistryObject<TrapDoorBlock> BAMBOO_TRAPDOOR = BLOCKS.register("bamboo_trapdoor", () -> new TrapDoorBlock(BlockSetType.OAK, BlockBehaviour.Properties.ofFullCopy(BAMBOO_BLOCK.get()).strength(0.5f).sound(SoundType.BAMBOO).noOcclusion()));

    public static final RegistryObject<Block> THATCH_BLOCK = BLOCKS.register("thatch_block", () -> new RotatedPillarBlock(BlockBehaviour.Properties.ofFullCopy(Blocks.HAY_BLOCK).strength(0.5f).sound(SoundType.CROP)));
    public static final RegistryObject<ButtonBlock> THATCH_BUTTON = BLOCKS.register("thatch_button", () -> new ButtonBlock(BlockSetType.OAK, 30, BlockBehaviour.Properties.ofFullCopy(THATCH_BLOCK.get()).strength(0.5f).sound(SoundType.CROP).noCollission()));
    public static final RegistryObject<DoorBlock> THATCH_DOOR = BLOCKS.register("thatch_door", () -> new DoorBlock(new BlockSetType("oak"), BlockBehaviour.Properties.ofFullCopy(THATCH_BLOCK.get()).strength(0.5f).sound(SoundType.CROP).noOcclusion()));
    public static final RegistryObject<FenceBlock> THATCH_FENCE = BLOCKS.register("thatch_fence", () -> new FenceBlock(BlockBehaviour.Properties.ofFullCopy(THATCH_BLOCK.get()).strength(0.5f).sound(SoundType.CROP)));
    public static final RegistryObject<FenceGateBlock> THATCH_FENCE_GATE = BLOCKS.register("thatch_fence_gate", () -> new FenceGateBlock(WoodType.OAK, BlockBehaviour.Properties.ofFullCopy(THATCH_BLOCK.get()).strength(0.5f).sound(SoundType.CROP)));
    public static final RegistryObject<LadderBlock> THATCH_LADDER = BLOCKS.register("thatch_ladder", () -> new LadderBlock(BlockBehaviour.Properties.ofFullCopy(THATCH_BLOCK.get()).strength(0.5f).sound(SoundType.CROP).noOcclusion()));
    public static final RegistryObject<PressurePlateBlock>  THATCH_PRESSURE_PLATE = BLOCKS.register("thatch_pressure_plate", () -> new PressurePlateBlock(new BlockSetType("oak"), BlockBehaviour.Properties.ofFullCopy(THATCH_BLOCK.get()).strength(0.5f).sound(SoundType.CROP).noCollission()));
    public static final RegistryObject<SlabBlock>  THATCH_SLAB = BLOCKS.register("thatch_slab", () -> new SlabBlock(BlockBehaviour.Properties.ofFullCopy(THATCH_BLOCK.get()).strength(0.5f).sound(SoundType.CROP)));
    public static final RegistryObject<StairBlock> THATCH_STAIRS = BLOCKS.register("thatch_stairs", () -> new StairBlock(BlockInit.THATCH_BLOCK.get().defaultBlockState(), BlockBehaviour.Properties.ofFullCopy(THATCH_BLOCK.get()).strength(0.5f).sound(SoundType.CROP)));
    public static final RegistryObject<TrapDoorBlock> THATCH_TRAPDOOR = BLOCKS.register("thatch_trapdoor", () -> new TrapDoorBlock(BlockSetType.OAK, BlockBehaviour.Properties.ofFullCopy(THATCH_BLOCK.get()).strength(0.5f).sound(SoundType.CROP).noOcclusion()));

    public static final RegistryObject<Block> ACACIA_BEAM_UP = BLOCKS.register("acacia_beam_up", () -> new RotatedPillarBlock(BlockBehaviour.Properties.ofFullCopy(Blocks.ACACIA_WOOD).strength(2.0f, 3.0f).sound(SoundType.WOOD)));
    public static final RegistryObject<Block> ACACIA_BEAM_MIDDLE = BLOCKS.register("acacia_beam_middle", () -> new RotatedPillarBlock(BlockBehaviour.Properties.ofFullCopy(Blocks.ACACIA_WOOD).strength(2.0f, 3.0f).sound(SoundType.WOOD)));
    public static final RegistryObject<Block> ACACIA_BEAM_DOWN = BLOCKS.register("acacia_beam_down", () -> new RotatedPillarBlock(BlockBehaviour.Properties.ofFullCopy(Blocks.ACACIA_WOOD).strength(2.0f, 3.0f).sound(SoundType.WOOD)));
    public static final RegistryObject<Block> BIRCH_BEAM_UP = BLOCKS.register("birch_beam_up", () -> new RotatedPillarBlock(BlockBehaviour.Properties.ofFullCopy(Blocks.BIRCH_WOOD).strength(2.0f, 3.0f).sound(SoundType.WOOD)));
    public static final RegistryObject<Block> BIRCH_BEAM_MIDDLE = BLOCKS.register("birch_beam_middle", () -> new RotatedPillarBlock(BlockBehaviour.Properties.ofFullCopy(Blocks.BIRCH_WOOD).strength(2.0f, 3.0f).sound(SoundType.WOOD)));
    public static final RegistryObject<Block> BIRCH_BEAM_DOWN = BLOCKS.register("birch_beam_down", () -> new RotatedPillarBlock(BlockBehaviour.Properties.ofFullCopy(Blocks.BIRCH_WOOD).strength(2.0f, 3.0f).sound(SoundType.WOOD)));
    public static final RegistryObject<Block> CHERRY_BEAM_UP = BLOCKS.register("cherry_beam_up", () -> new RotatedPillarBlock(BlockBehaviour.Properties.ofFullCopy(Blocks.CHERRY_WOOD).strength(2.0f, 3.0f).sound(SoundType.WOOD)));
    public static final RegistryObject<Block> CHERRY_BEAM_MIDDLE = BLOCKS.register("cherry_beam_middle", () -> new RotatedPillarBlock(BlockBehaviour.Properties.ofFullCopy(Blocks.CHERRY_WOOD).strength(2.0f, 3.0f).sound(SoundType.WOOD)));
    public static final RegistryObject<Block> CHERRY_BEAM_DOWN = BLOCKS.register("cherry_beam_down", () -> new RotatedPillarBlock(BlockBehaviour.Properties.ofFullCopy(Blocks.CHERRY_WOOD).strength(2.0f, 3.0f).sound(SoundType.WOOD)));
    public static final RegistryObject<Block> CRIMSON_BEAM_UP = BLOCKS.register("crimson_beam_up", () -> new RotatedPillarBlock(BlockBehaviour.Properties.ofFullCopy(Blocks.CRIMSON_HYPHAE).strength(2.0f, 3.0f).sound(SoundType.WOOD)));
    public static final RegistryObject<Block> CRIMSON_BEAM_MIDDLE = BLOCKS.register("crimson_beam_middle", () -> new RotatedPillarBlock(BlockBehaviour.Properties.ofFullCopy(Blocks.CRIMSON_HYPHAE).strength(2.0f, 3.0f).sound(SoundType.WOOD)));
    public static final RegistryObject<Block> CRIMSON_BEAM_DOWN = BLOCKS.register("crimson_beam_down", () -> new RotatedPillarBlock(BlockBehaviour.Properties.ofFullCopy(Blocks.CRIMSON_HYPHAE).strength(2.0f, 3.0f).sound(SoundType.WOOD)));
    public static final RegistryObject<Block> DARK_OAK_BEAM_UP = BLOCKS.register("dark_oak_beam_up", () -> new RotatedPillarBlock(BlockBehaviour.Properties.ofFullCopy(Blocks.DARK_OAK_WOOD).strength(2.0f, 3.0f).sound(SoundType.WOOD)));
    public static final RegistryObject<Block> DARK_OAK_BEAM_MIDDLE = BLOCKS.register("dark_oak_beam_middle", () -> new RotatedPillarBlock(BlockBehaviour.Properties.ofFullCopy(Blocks.DARK_OAK_WOOD).strength(2.0f, 3.0f).sound(SoundType.WOOD)));
    public static final RegistryObject<Block> DARK_OAK_BEAM_DOWN = BLOCKS.register("dark_oak_beam_down", () -> new RotatedPillarBlock(BlockBehaviour.Properties.ofFullCopy(Blocks.DARK_OAK_WOOD).strength(2.0f, 3.0f).sound(SoundType.WOOD)));
    public static final RegistryObject<Block> JUNGLE_BEAM_UP = BLOCKS.register("jungle_beam_up", () -> new RotatedPillarBlock(BlockBehaviour.Properties.ofFullCopy(Blocks.JUNGLE_WOOD).strength(2.0f, 3.0f).sound(SoundType.WOOD)));
    public static final RegistryObject<Block> JUNGLE_BEAM_MIDDLE = BLOCKS.register("jungle_beam_middle", () -> new RotatedPillarBlock(BlockBehaviour.Properties.ofFullCopy(Blocks.JUNGLE_WOOD).strength(2.0f, 3.0f).sound(SoundType.WOOD)));
    public static final RegistryObject<Block> JUNGLE_BEAM_DOWN = BLOCKS.register("jungle_beam_down", () -> new RotatedPillarBlock(BlockBehaviour.Properties.ofFullCopy(Blocks.JUNGLE_WOOD).strength(2.0f, 3.0f).sound(SoundType.WOOD)));
    public static final RegistryObject<Block> MANGROVE_BEAM_UP = BLOCKS.register("mangrove_beam_up", () -> new RotatedPillarBlock(BlockBehaviour.Properties.ofFullCopy(Blocks.MANGROVE_WOOD).strength(2.0f, 3.0f).sound(SoundType.WOOD)));
    public static final RegistryObject<Block> MANGROVE_BEAM_MIDDLE = BLOCKS.register("mangrove_beam_middle", () -> new RotatedPillarBlock(BlockBehaviour.Properties.ofFullCopy(Blocks.MANGROVE_WOOD).strength(2.0f, 3.0f).sound(SoundType.WOOD)));
    public static final RegistryObject<Block> MANGROVE_BEAM_DOWN = BLOCKS.register("mangrove_beam_down", () -> new RotatedPillarBlock(BlockBehaviour.Properties.ofFullCopy(Blocks.MANGROVE_WOOD).strength(2.0f, 3.0f).sound(SoundType.WOOD)));
    public static final RegistryObject<Block> OAK_BEAM_UP = BLOCKS.register("oak_beam_up", () -> new RotatedPillarBlock(BlockBehaviour.Properties.ofFullCopy(Blocks.OAK_WOOD).strength(2.0f, 3.0f).sound(SoundType.WOOD)));
    public static final RegistryObject<Block> OAK_BEAM_MIDDLE = BLOCKS.register("oak_beam_middle", () -> new RotatedPillarBlock(BlockBehaviour.Properties.ofFullCopy(Blocks.OAK_WOOD).strength(2.0f, 3.0f).sound(SoundType.WOOD)));
    public static final RegistryObject<Block> OAK_BEAM_DOWN = BLOCKS.register("oak_beam_down", () -> new RotatedPillarBlock(BlockBehaviour.Properties.ofFullCopy(Blocks.OAK_WOOD).strength(2.0f, 3.0f).sound(SoundType.WOOD)));
    public static final RegistryObject<Block> SPRUCE_BEAM_UP = BLOCKS.register("spruce_beam_up", () -> new RotatedPillarBlock(BlockBehaviour.Properties.ofFullCopy(Blocks.SPRUCE_WOOD).strength(2.0f, 3.0f).sound(SoundType.WOOD)));
    public static final RegistryObject<Block> SPRUCE_BEAM_MIDDLE = BLOCKS.register("spruce_beam_middle", () -> new RotatedPillarBlock(BlockBehaviour.Properties.ofFullCopy(Blocks.SPRUCE_WOOD).strength(2.0f, 3.0f).sound(SoundType.WOOD)));
    public static final RegistryObject<Block> SPRUCE_BEAM_DOWN = BLOCKS.register("spruce_beam_down", () -> new RotatedPillarBlock(BlockBehaviour.Properties.ofFullCopy(Blocks.SPRUCE_WOOD).strength(2.0f, 3.0f).sound(SoundType.WOOD)));
    public static final RegistryObject<Block> WARPED_BEAM_UP = BLOCKS.register("warped_beam_up", () -> new RotatedPillarBlock(BlockBehaviour.Properties.ofFullCopy(Blocks.WARPED_HYPHAE).strength(2.0f, 3.0f).sound(SoundType.WOOD)));
    public static final RegistryObject<Block> WARPED_BEAM_MIDDLE = BLOCKS.register("warped_beam_middle", () -> new RotatedPillarBlock(BlockBehaviour.Properties.ofFullCopy(Blocks.WARPED_HYPHAE).strength(2.0f, 3.0f).sound(SoundType.WOOD)));
    public static final RegistryObject<Block> WARPED_BEAM_DOWN = BLOCKS.register("warped_beam_down", () -> new RotatedPillarBlock(BlockBehaviour.Properties.ofFullCopy(Blocks.WARPED_HYPHAE).strength(2.0f, 3.0f).sound(SoundType.WOOD)));

    public static final RegistryObject<LadderBlock> ACACIA_LADDER = BLOCKS.register("acacia_ladder", () -> new LadderBlock(BlockBehaviour.Properties.ofFullCopy(Blocks.LADDER).strength(0.5f).sound(SoundType.LADDER).noOcclusion()));
    public static final RegistryObject<LadderBlock> BIRCH_LADDER = BLOCKS.register("birch_ladder", () -> new LadderBlock(BlockBehaviour.Properties.ofFullCopy(Blocks.LADDER).strength(0.5f).sound(SoundType.LADDER).noOcclusion()));
    public static final RegistryObject<LadderBlock> CHERRY_LADDER = BLOCKS.register("cherry_ladder", () -> new LadderBlock(BlockBehaviour.Properties.ofFullCopy(Blocks.LADDER).strength(0.5f).sound(SoundType.LADDER).noOcclusion()));
    public static final RegistryObject<LadderBlock> CRIMSON_LADDER = BLOCKS.register("crimson_ladder", () -> new LadderBlock(BlockBehaviour.Properties.ofFullCopy(Blocks.LADDER).strength(0.5f).sound(SoundType.LADDER).noOcclusion()));
    public static final RegistryObject<LadderBlock> DARK_OAK_LADDER = BLOCKS.register("dark_oak_ladder", () -> new LadderBlock(BlockBehaviour.Properties.ofFullCopy(Blocks.LADDER).strength(0.5f).sound(SoundType.LADDER).noOcclusion()));
    public static final RegistryObject<LadderBlock> JUNGLE_LADDER = BLOCKS.register("jungle_ladder", () -> new LadderBlock(BlockBehaviour.Properties.ofFullCopy(Blocks.LADDER).strength(0.5f).sound(SoundType.LADDER).noOcclusion()));
    public static final RegistryObject<LadderBlock> MANGROVE_LADDER = BLOCKS.register("mangrove_ladder", () -> new LadderBlock(BlockBehaviour.Properties.ofFullCopy(Blocks.LADDER).strength(0.5f).sound(SoundType.LADDER).noOcclusion()));
    public static final RegistryObject<LadderBlock> OAK_LADDER = BLOCKS.register("oak_ladder", () -> new LadderBlock(BlockBehaviour.Properties.ofFullCopy(Blocks.LADDER).strength(0.5f).sound(SoundType.LADDER).noOcclusion()));
    public static final RegistryObject<LadderBlock> SPRUCE_LADDER = BLOCKS.register("spruce_ladder", () -> new LadderBlock(BlockBehaviour.Properties.ofFullCopy(Blocks.LADDER).strength(0.5f).sound(SoundType.LADDER).noOcclusion()));
    public static final RegistryObject<LadderBlock> WARPED_LADDER = BLOCKS.register("warped_ladder", () -> new LadderBlock(BlockBehaviour.Properties.ofFullCopy(Blocks.LADDER).strength(0.5f).sound(SoundType.LADDER).noOcclusion()));

    public static final RegistryObject<TorchBlock> ACACIA_TORCH = BLOCKS.register("acacia_torch", () -> new TorchBlock(ParticleTypes.FLAME, BlockBehaviour.Properties.ofFullCopy(Blocks.TORCH).noCollission().instabreak().lightLevel((state) -> 14).sound(SoundType.WOOD)));
    public static final RegistryObject<WallTorchBlock> ACACIA_WALL_TORCH = BLOCKS.register("acacia_wall_torch", () -> new WallTorchBlock(ParticleTypes.FLAME, BlockBehaviour.Properties.ofFullCopy(Blocks.WALL_TORCH).noCollission().instabreak().lightLevel((state) -> 14).sound(SoundType.WOOD).dropsLike(ACACIA_TORCH.get())));
    public static final RegistryObject<TorchBlock> BIRCH_TORCH = BLOCKS.register("birch_torch", () -> new TorchBlock(ParticleTypes.FLAME, BlockBehaviour.Properties.ofFullCopy(Blocks.TORCH).noCollission().instabreak().lightLevel((state) -> 14).sound(SoundType.WOOD)));
    public static final RegistryObject<WallTorchBlock> BIRCH_WALL_TORCH = BLOCKS.register("birch_wall_torch", () -> new WallTorchBlock(ParticleTypes.FLAME, BlockBehaviour.Properties.ofFullCopy(Blocks.WALL_TORCH).noCollission().instabreak().lightLevel((state) -> 14).sound(SoundType.WOOD).dropsLike(BIRCH_TORCH.get())));
    public static final RegistryObject<TorchBlock> CHERRY_TORCH = BLOCKS.register("cherry_torch", () -> new TorchBlock(ParticleTypes.FLAME, BlockBehaviour.Properties.ofFullCopy(Blocks.TORCH).noCollission().instabreak().lightLevel((state) -> 14).sound(SoundType.WOOD)));
    public static final RegistryObject<WallTorchBlock> CHERRY_WALL_TORCH = BLOCKS.register("cherry_wall_torch", () -> new WallTorchBlock(ParticleTypes.FLAME, BlockBehaviour.Properties.ofFullCopy(Blocks.WALL_TORCH).noCollission().instabreak().lightLevel((state) -> 14).sound(SoundType.WOOD).dropsLike(CHERRY_TORCH.get())));
    public static final RegistryObject<TorchBlock> CRIMSON_TORCH = BLOCKS.register("crimson_torch", () -> new TorchBlock(ParticleTypes.FLAME, BlockBehaviour.Properties.ofFullCopy(Blocks.TORCH).noCollission().instabreak().lightLevel((state) -> 14).sound(SoundType.WOOD)));
    public static final RegistryObject<WallTorchBlock> CRIMSON_WALL_TORCH = BLOCKS.register("crimson_wall_torch", () -> new WallTorchBlock(ParticleTypes.FLAME, BlockBehaviour.Properties.ofFullCopy(Blocks.WALL_TORCH).noCollission().instabreak().lightLevel((state) -> 14).sound(SoundType.WOOD).dropsLike(CRIMSON_TORCH.get())));
    public static final RegistryObject<TorchBlock> DARK_OAK_TORCH = BLOCKS.register("dark_oak_torch", () -> new TorchBlock(ParticleTypes.FLAME, BlockBehaviour.Properties.ofFullCopy(Blocks.TORCH).noCollission().instabreak().lightLevel((state) -> 14).sound(SoundType.WOOD)));
    public static final RegistryObject<WallTorchBlock> DARK_OAK_WALL_TORCH = BLOCKS.register("dark_oak_wall_torch", () -> new WallTorchBlock(ParticleTypes.FLAME, BlockBehaviour.Properties.ofFullCopy(Blocks.WALL_TORCH).noCollission().instabreak().lightLevel((state) -> 14).sound(SoundType.WOOD).dropsLike(DARK_OAK_TORCH.get())));
    public static final RegistryObject<TorchBlock> JUNGLE_TORCH = BLOCKS.register("jungle_torch", () -> new TorchBlock(ParticleTypes.FLAME, BlockBehaviour.Properties.ofFullCopy(Blocks.TORCH).noCollission().instabreak().lightLevel((state) -> 14).sound(SoundType.WOOD)));
    public static final RegistryObject<WallTorchBlock> JUNGLE_WALL_TORCH = BLOCKS.register("jungle_wall_torch", () -> new WallTorchBlock(ParticleTypes.FLAME, BlockBehaviour.Properties.ofFullCopy(Blocks.WALL_TORCH).noCollission().instabreak().lightLevel((state) -> 14).sound(SoundType.WOOD).dropsLike(JUNGLE_TORCH.get())));
    public static final RegistryObject<TorchBlock> MANGROVE_TORCH = BLOCKS.register("mangrove_torch", () -> new TorchBlock(ParticleTypes.FLAME, BlockBehaviour.Properties.ofFullCopy(Blocks.TORCH).noCollission().instabreak().lightLevel((state) -> 14).sound(SoundType.WOOD)));
    public static final RegistryObject<WallTorchBlock> MANGROVE_WALL_TORCH = BLOCKS.register("mangrove_wall_torch", () -> new WallTorchBlock(ParticleTypes.FLAME, BlockBehaviour.Properties.ofFullCopy(Blocks.WALL_TORCH).noCollission().instabreak().lightLevel((state) -> 14).sound(SoundType.WOOD).dropsLike(MANGROVE_TORCH.get())));
    public static final RegistryObject<TorchBlock> OAK_TORCH = BLOCKS.register("oak_torch", () -> new TorchBlock(ParticleTypes.FLAME, BlockBehaviour.Properties.ofFullCopy(Blocks.TORCH).noCollission().instabreak().lightLevel((state) -> 14).sound(SoundType.WOOD)));
    public static final RegistryObject<WallTorchBlock> OAK_WALL_TORCH = BLOCKS.register("oak_wall_torch", () -> new WallTorchBlock(ParticleTypes.FLAME, BlockBehaviour.Properties.ofFullCopy(Blocks.WALL_TORCH).noCollission().instabreak().lightLevel((state) -> 14).sound(SoundType.WOOD).dropsLike(OAK_TORCH.get())));
    public static final RegistryObject<TorchBlock> SPRUCE_TORCH = BLOCKS.register("spruce_torch", () -> new TorchBlock(ParticleTypes.FLAME, BlockBehaviour.Properties.ofFullCopy(Blocks.TORCH).noCollission().instabreak().lightLevel((state) -> 14).sound(SoundType.WOOD)));
    public static final RegistryObject<WallTorchBlock> SPRUCE_WALL_TORCH = BLOCKS.register("spruce_wall_torch", () -> new WallTorchBlock(ParticleTypes.FLAME, BlockBehaviour.Properties.ofFullCopy(Blocks.WALL_TORCH).noCollission().instabreak().lightLevel((state) -> 14).sound(SoundType.WOOD).dropsLike(SPRUCE_TORCH.get())));
    public static final RegistryObject<TorchBlock> WARPED_TORCH = BLOCKS.register("warped_torch", () -> new TorchBlock(ParticleTypes.FLAME, BlockBehaviour.Properties.ofFullCopy(Blocks.TORCH).noCollission().instabreak().lightLevel((state) -> 14).sound(SoundType.WOOD)));
    public static final RegistryObject<WallTorchBlock> WARPED_WALL_TORCH = BLOCKS.register("warped_wall_torch", () -> new WallTorchBlock(ParticleTypes.FLAME, BlockBehaviour.Properties.ofFullCopy(Blocks.WALL_TORCH).noCollission().instabreak().lightLevel((state) -> 14).sound(SoundType.WOOD).dropsLike(WARPED_TORCH.get())));

    public static final RegistryObject<TorchBlock> ACACIA_SOUL_TORCH = BLOCKS.register("acacia_soul_torch", () -> new TorchBlock(ParticleTypes.SOUL_FIRE_FLAME, BlockBehaviour.Properties.ofFullCopy(Blocks.TORCH).noCollission().instabreak().lightLevel((state) -> 10).sound(SoundType.WOOD)));
    public static final RegistryObject<WallTorchBlock> ACACIA_WALL_SOUL_TORCH = BLOCKS.register("acacia_wall_soul_torch", () -> new WallTorchBlock(ParticleTypes.SOUL_FIRE_FLAME, BlockBehaviour.Properties.ofFullCopy(Blocks.WALL_TORCH).noCollission().instabreak().lightLevel((state) -> 10).sound(SoundType.WOOD).dropsLike(ACACIA_SOUL_TORCH.get())));
    public static final RegistryObject<TorchBlock> BIRCH_SOUL_TORCH = BLOCKS.register("birch_soul_torch", () -> new TorchBlock(ParticleTypes.SOUL_FIRE_FLAME, BlockBehaviour.Properties.ofFullCopy(Blocks.TORCH).noCollission().instabreak().lightLevel((state) -> 10).sound(SoundType.WOOD)));
    public static final RegistryObject<WallTorchBlock> BIRCH_WALL_SOUL_TORCH = BLOCKS.register("birch_wall_soul_torch", () -> new WallTorchBlock(ParticleTypes.SOUL_FIRE_FLAME, BlockBehaviour.Properties.ofFullCopy(Blocks.WALL_TORCH).noCollission().instabreak().lightLevel((state) -> 10).sound(SoundType.WOOD).dropsLike(BIRCH_SOUL_TORCH.get())));
    public static final RegistryObject<TorchBlock> CHERRY_SOUL_TORCH = BLOCKS.register("cherry_soul_torch", () -> new TorchBlock(ParticleTypes.SOUL_FIRE_FLAME, BlockBehaviour.Properties.ofFullCopy(Blocks.TORCH).noCollission().instabreak().lightLevel((state) -> 10).sound(SoundType.WOOD)));
    public static final RegistryObject<WallTorchBlock> CHERRY_WALL_SOUL_TORCH = BLOCKS.register("cherry_wall_soul_torch", () -> new WallTorchBlock(ParticleTypes.SOUL_FIRE_FLAME, BlockBehaviour.Properties.ofFullCopy(Blocks.WALL_TORCH).noCollission().instabreak().lightLevel((state) -> 10).sound(SoundType.WOOD).dropsLike(CHERRY_SOUL_TORCH.get())));
    public static final RegistryObject<TorchBlock> CRIMSON_SOUL_TORCH = BLOCKS.register("crimson_soul_torch", () -> new TorchBlock(ParticleTypes.SOUL_FIRE_FLAME, BlockBehaviour.Properties.ofFullCopy(Blocks.TORCH).noCollission().instabreak().lightLevel((state) -> 10).sound(SoundType.WOOD)));
    public static final RegistryObject<WallTorchBlock> CRIMSON_WALL_SOUL_TORCH = BLOCKS.register("crimson_wall_soul_torch", () -> new WallTorchBlock(ParticleTypes.SOUL_FIRE_FLAME, BlockBehaviour.Properties.ofFullCopy(Blocks.WALL_TORCH).noCollission().instabreak().lightLevel((state) -> 10).sound(SoundType.WOOD).dropsLike(CRIMSON_SOUL_TORCH.get())));
    public static final RegistryObject<TorchBlock> DARK_OAK_SOUL_TORCH = BLOCKS.register("dark_oak_soul_torch", () -> new TorchBlock(ParticleTypes.SOUL_FIRE_FLAME, BlockBehaviour.Properties.ofFullCopy(Blocks.TORCH).noCollission().instabreak().lightLevel((state) -> 10).sound(SoundType.WOOD)));
    public static final RegistryObject<WallTorchBlock> DARK_OAK_WALL_SOUL_TORCH = BLOCKS.register("dark_oak_wall_soul_torch", () -> new WallTorchBlock(ParticleTypes.SOUL_FIRE_FLAME, BlockBehaviour.Properties.ofFullCopy(Blocks.WALL_TORCH).noCollission().instabreak().lightLevel((state) -> 10).sound(SoundType.WOOD).dropsLike(DARK_OAK_SOUL_TORCH.get())));
    public static final RegistryObject<TorchBlock> JUNGLE_SOUL_TORCH = BLOCKS.register("jungle_soul_torch", () -> new TorchBlock(ParticleTypes.SOUL_FIRE_FLAME, BlockBehaviour.Properties.ofFullCopy(Blocks.TORCH).noCollission().instabreak().lightLevel((state) -> 10).sound(SoundType.WOOD)));
    public static final RegistryObject<WallTorchBlock> JUNGLE_WALL_SOUL_TORCH = BLOCKS.register("jungle_wall_soul_torch", () -> new WallTorchBlock(ParticleTypes.SOUL_FIRE_FLAME, BlockBehaviour.Properties.ofFullCopy(Blocks.WALL_TORCH).noCollission().instabreak().lightLevel((state) -> 10).sound(SoundType.WOOD).dropsLike(JUNGLE_SOUL_TORCH.get())));
    public static final RegistryObject<TorchBlock> MANGROVE_SOUL_TORCH = BLOCKS.register("mangrove_soul_torch", () -> new TorchBlock(ParticleTypes.SOUL_FIRE_FLAME, BlockBehaviour.Properties.ofFullCopy(Blocks.TORCH).noCollission().instabreak().lightLevel((state) -> 10).sound(SoundType.WOOD)));
    public static final RegistryObject<WallTorchBlock> MANGROVE_WALL_SOUL_TORCH = BLOCKS.register("mangrove_wall_soul_torch", () -> new WallTorchBlock(ParticleTypes.SOUL_FIRE_FLAME, BlockBehaviour.Properties.ofFullCopy(Blocks.WALL_TORCH).noCollission().instabreak().lightLevel((state) -> 10).sound(SoundType.WOOD).dropsLike(MANGROVE_SOUL_TORCH.get())));
    public static final RegistryObject<TorchBlock> OAK_SOUL_TORCH = BLOCKS.register("oak_soul_torch", () -> new TorchBlock(ParticleTypes.SOUL_FIRE_FLAME, BlockBehaviour.Properties.ofFullCopy(Blocks.TORCH).noCollission().instabreak().lightLevel((state) -> 10).sound(SoundType.WOOD)));
    public static final RegistryObject<WallTorchBlock> OAK_WALL_SOUL_TORCH = BLOCKS.register("oak_wall_soul_torch", () -> new WallTorchBlock(ParticleTypes.SOUL_FIRE_FLAME, BlockBehaviour.Properties.ofFullCopy(Blocks.WALL_TORCH).noCollission().instabreak().lightLevel((state) -> 10).sound(SoundType.WOOD).dropsLike(OAK_SOUL_TORCH.get())));
    public static final RegistryObject<TorchBlock> SPRUCE_SOUL_TORCH = BLOCKS.register("spruce_soul_torch", () -> new TorchBlock(ParticleTypes.SOUL_FIRE_FLAME, BlockBehaviour.Properties.ofFullCopy(Blocks.TORCH).noCollission().instabreak().lightLevel((state) -> 10).sound(SoundType.WOOD)));
    public static final RegistryObject<WallTorchBlock> SPRUCE_WALL_SOUL_TORCH = BLOCKS.register("spruce_wall_soul_torch", () -> new WallTorchBlock(ParticleTypes.SOUL_FIRE_FLAME, BlockBehaviour.Properties.ofFullCopy(Blocks.WALL_TORCH).noCollission().instabreak().lightLevel((state) -> 10).sound(SoundType.WOOD).dropsLike(SPRUCE_SOUL_TORCH.get())));
    public static final RegistryObject<TorchBlock> WARPED_SOUL_TORCH = BLOCKS.register("warped_soul_torch", () -> new TorchBlock(ParticleTypes.SOUL_FIRE_FLAME, BlockBehaviour.Properties.ofFullCopy(Blocks.TORCH).noCollission().instabreak().lightLevel((state) -> 10).sound(SoundType.WOOD)));
    public static final RegistryObject<WallTorchBlock> WARPED_WALL_SOUL_TORCH = BLOCKS.register("warped_wall_soul_torch", () -> new WallTorchBlock(ParticleTypes.SOUL_FIRE_FLAME, BlockBehaviour.Properties.ofFullCopy(Blocks.WALL_TORCH).noCollission().instabreak().lightLevel((state) -> 10).sound(SoundType.WOOD).dropsLike(WARPED_SOUL_TORCH.get())));

    public static final RegistryObject<Block> MOSSY_STONE = BLOCKS.register("mossy_stone", () -> new Block(BlockBehaviour.Properties.ofFullCopy(Blocks.STONE).strength(1.5F, 6.0F).sound(SoundType.STONE).requiresCorrectToolForDrops()));
    public static final RegistryObject<ButtonBlock> MOSSY_STONE_BUTTON = BLOCKS.register("mossy_stone_button", () -> new ButtonBlock(BlockSetType.STONE, 20, BlockBehaviour.Properties.ofFullCopy(Blocks.STONE).strength(0.5F).sound(SoundType.STONE).noCollission().requiresCorrectToolForDrops()));
    public static final RegistryObject<PressurePlateBlock> MOSSY_STONE_PRESSURE_PLATE = BLOCKS.register("mossy_stone_pressure_plate", () -> new PressurePlateBlock(new BlockSetType("stone") ,BlockBehaviour.Properties.ofFullCopy(Blocks.STONE).strength(0.5F).sound(SoundType.STONE).noCollission().requiresCorrectToolForDrops()));
    public static final RegistryObject<SlabBlock> MOSSY_STONE_SLAB = BLOCKS.register("mossy_stone_slab", () -> new SlabBlock(BlockBehaviour.Properties.ofFullCopy(Blocks.STONE).strength(1.5F, 6.0F).sound(SoundType.STONE).requiresCorrectToolForDrops()));
    public static final RegistryObject<StairBlock> MOSSY_STONE_STAIRS = BLOCKS.register("mossy_stone_stairs", () -> new StairBlock(MOSSY_STONE.get().defaultBlockState(), BlockBehaviour.Properties.ofFullCopy(Blocks.STONE).strength(1.5F, 6.0F).sound(SoundType.STONE).requiresCorrectToolForDrops()));
    public static final RegistryObject<WallBlock> MOSSY_STONE_WALL = BLOCKS.register("mossy_stone_wall", () -> new WallBlock(BlockBehaviour.Properties.ofFullCopy(Blocks.STONE).strength(1.5F, 6.0F).sound(SoundType.STONE).requiresCorrectToolForDrops()));

    public static final RegistryObject<Block> MORE_MOSSY_STONE = BLOCKS.register("more_mossy_stone", () -> new Block(BlockBehaviour.Properties.ofFullCopy(Blocks.STONE).strength(1.5F, 6.0F).sound(SoundType.STONE).requiresCorrectToolForDrops()));
    public static final RegistryObject<ButtonBlock> MORE_MOSSY_STONE_BUTTON = BLOCKS.register("more_mossy_stone_button", () -> new ButtonBlock(BlockSetType.STONE, 20, BlockBehaviour.Properties.ofFullCopy(Blocks.STONE).strength(0.5F).sound(SoundType.STONE).noCollission().requiresCorrectToolForDrops()));
    public static final RegistryObject<PressurePlateBlock> MORE_MOSSY_STONE_PRESSURE_PLATE = BLOCKS.register("more_mossy_stone_pressure_plate", () -> new PressurePlateBlock(new BlockSetType("stone") ,BlockBehaviour.Properties.ofFullCopy(Blocks.STONE).strength(0.5F).sound(SoundType.STONE).noCollission().requiresCorrectToolForDrops()));
    public static final RegistryObject<SlabBlock> MORE_MOSSY_STONE_SLAB = BLOCKS.register("more_mossy_stone_slab", () -> new SlabBlock(BlockBehaviour.Properties.ofFullCopy(Blocks.STONE).strength(1.5F, 6.0F).sound(SoundType.STONE).requiresCorrectToolForDrops()));
    public static final RegistryObject<StairBlock> MORE_MOSSY_STONE_STAIRS = BLOCKS.register("more_mossy_stone_stairs", () -> new StairBlock(MORE_MOSSY_STONE.get().defaultBlockState(), BlockBehaviour.Properties.ofFullCopy(Blocks.STONE).strength(1.5F, 6.0F).sound(SoundType.STONE).requiresCorrectToolForDrops()));
    public static final RegistryObject<WallBlock> MORE_MOSSY_STONE_WALL = BLOCKS.register("more_mossy_stone_wall", () -> new WallBlock(BlockBehaviour.Properties.ofFullCopy(Blocks.STONE).strength(1.5F, 6.0F).sound(SoundType.STONE).requiresCorrectToolForDrops()));

}