package mod.silverwolf.silverwolfsbuildingblocks.init;

import mod.silverwolf.silverwolfsbuildingblocks.SilverwolfsBuildingBlocks;
import net.minecraft.core.Direction;
import net.minecraft.world.item.BlockItem;
import net.minecraft.world.item.Item;
import net.minecraft.world.item.StandingAndWallBlockItem;
import net.minecraftforge.registries.DeferredRegister;
import net.minecraftforge.registries.ForgeRegistries;
import net.minecraftforge.registries.RegistryObject;

import static mod.silverwolf.silverwolfsbuildingblocks.init.CreativeTabInit.addToTab;

public class ItemInit {
    public static final DeferredRegister<Item> ITEMS = DeferredRegister.create(ForgeRegistries.ITEMS, SilverwolfsBuildingBlocks.MODID);

    //Items
    public static final RegistryObject<Item> THATCH = addToTab(ITEMS.register("thatch", () -> new Item(new Item.Properties())));

    public static final RegistryObject<Item> ACACIA_STICK = addToTab(ITEMS.register("acacia_stick", () -> new Item(new Item.Properties())));
    public static final RegistryObject<Item> BIRCH_STICK = addToTab(ITEMS.register("birch_stick", () -> new Item(new Item.Properties())));
    public static final RegistryObject<Item> CHERRY_STICK = addToTab(ITEMS.register("cherry_stick", () -> new Item(new Item.Properties())));
    public static final RegistryObject<Item> CRIMSON_STICK = addToTab(ITEMS.register("crimson_stick", () -> new Item(new Item.Properties())));
    public static final RegistryObject<Item> DARK_OAK_STICK = addToTab(ITEMS.register("dark_oak_stick", () -> new Item(new Item.Properties())));
    public static final RegistryObject<Item> JUNGLE_STICK = addToTab(ITEMS.register("jungle_stick", () -> new Item(new Item.Properties())));
    public static final RegistryObject<Item> MANGROVE_STICK = addToTab(ITEMS.register("mangrove_stick", () -> new Item(new Item.Properties())));
    public static final RegistryObject<Item> OAK_STICK = addToTab(ITEMS.register("oak_stick", () -> new Item(new Item.Properties())));
    public static final RegistryObject<Item> SPRUCE_STICK = addToTab(ITEMS.register("spruce_stick", () -> new Item(new Item.Properties())));
    public static final RegistryObject<Item> WARPED_STICK = addToTab(ITEMS.register("warped_stick", () -> new Item(new Item.Properties())));

    public static final RegistryObject<Item> CLAY_BALL_BLACK_LIGHT = addToTab(ITEMS.register("clay_ball_black_light", () -> new Item(new Item.Properties())));
    public static final RegistryObject<Item> CLAY_BALL_BLACK_MEDIUM = addToTab(ITEMS.register("clay_ball_black_medium", () -> new Item(new Item.Properties())));
    public static final RegistryObject<Item> CLAY_BALL_BLACK_DARK = addToTab(ITEMS.register("clay_ball_black_dark", () -> new Item(new Item.Properties())));
    public static final RegistryObject<Item> CLAY_BALL_BLUE_LIGHT = addToTab(ITEMS.register("clay_ball_blue_light", () -> new Item(new Item.Properties())));
    public static final RegistryObject<Item> CLAY_BALL_BLUE_MEDIUM = addToTab(ITEMS.register("clay_ball_blue_medium", () -> new Item(new Item.Properties())));
    public static final RegistryObject<Item> CLAY_BALL_BLUE_DARK = addToTab(ITEMS.register("clay_ball_blue_dark", () -> new Item(new Item.Properties())));
    public static final RegistryObject<Item> CLAY_BALL_BROWN_LIGHT = addToTab(ITEMS.register("clay_ball_brown_light", () -> new Item(new Item.Properties())));
    public static final RegistryObject<Item> CLAY_BALL_BROWN_MEDIUM = addToTab(ITEMS.register("clay_ball_brown_medium", () -> new Item(new Item.Properties())));
    public static final RegistryObject<Item> CLAY_BALL_BROWN_DARK = addToTab(ITEMS.register("clay_ball_brown_dark", () -> new Item(new Item.Properties())));
    public static final RegistryObject<Item> CLAY_BALL_CYAN_LIGHT = addToTab(ITEMS.register("clay_ball_cyan_light", () -> new Item(new Item.Properties())));
    public static final RegistryObject<Item> CLAY_BALL_CYAN_MEDIUM = addToTab(ITEMS.register("clay_ball_cyan_medium", () -> new Item(new Item.Properties())));
    public static final RegistryObject<Item> CLAY_BALL_CYAN_DARK = addToTab(ITEMS.register("clay_ball_cyan_dark", () -> new Item(new Item.Properties())));
    public static final RegistryObject<Item> CLAY_BALL_GRAY_LIGHT = addToTab(ITEMS.register("clay_ball_gray_light", () -> new Item(new Item.Properties())));
    public static final RegistryObject<Item> CLAY_BALL_GRAY_MEDIUM = addToTab(ITEMS.register("clay_ball_gray_medium", () -> new Item(new Item.Properties())));
    public static final RegistryObject<Item> CLAY_BALL_GRAY_DARK = addToTab(ITEMS.register("clay_ball_gray_dark", () -> new Item(new Item.Properties())));
    public static final RegistryObject<Item> CLAY_BALL_GREEN_LIGHT = addToTab(ITEMS.register("clay_ball_green_light", () -> new Item(new Item.Properties())));
    public static final RegistryObject<Item> CLAY_BALL_GREEN_MEDIUM = addToTab(ITEMS.register("clay_ball_green_medium", () -> new Item(new Item.Properties())));
    public static final RegistryObject<Item> CLAY_BALL_GREEN_DARK = addToTab(ITEMS.register("clay_ball_green_dark", () -> new Item(new Item.Properties())));
    public static final RegistryObject<Item> CLAY_BALL_LIGHT_BLUE_LIGHT = addToTab(ITEMS.register("clay_ball_light_blue_light", () -> new Item(new Item.Properties())));
    public static final RegistryObject<Item> CLAY_BALL_LIGHT_BLUE_MEDIUM = addToTab(ITEMS.register("clay_ball_light_blue_medium", () -> new Item(new Item.Properties())));
    public static final RegistryObject<Item> CLAY_BALL_LIGHT_BLUE_DARK = addToTab(ITEMS.register("clay_ball_light_blue_dark", () -> new Item(new Item.Properties())));
    public static final RegistryObject<Item> CLAY_BALL_LIGHT_GRAY_LIGHT = addToTab(ITEMS.register("clay_ball_light_gray_light", () -> new Item(new Item.Properties())));
    public static final RegistryObject<Item> CLAY_BALL_LIGHT_GRAY_MEDIUM = addToTab(ITEMS.register("clay_ball_light_gray_medium", () -> new Item(new Item.Properties())));
    public static final RegistryObject<Item> CLAY_BALL_LIGHT_GRAY_DARK = addToTab(ITEMS.register("clay_ball_light_gray_dark", () -> new Item(new Item.Properties())));
    public static final RegistryObject<Item> CLAY_BALL_LIME_LIGHT = addToTab(ITEMS.register("clay_ball_lime_light", () -> new Item(new Item.Properties())));
    public static final RegistryObject<Item> CLAY_BALL_LIME_MEDIUM = addToTab(ITEMS.register("clay_ball_lime_medium", () -> new Item(new Item.Properties())));
    public static final RegistryObject<Item> CLAY_BALL_LIME_DARK = addToTab(ITEMS.register("clay_ball_lime_dark", () -> new Item(new Item.Properties())));
    public static final RegistryObject<Item> CLAY_BALL_MAGENTA_LIGHT = addToTab(ITEMS.register("clay_ball_magenta_light", () -> new Item(new Item.Properties())));
    public static final RegistryObject<Item> CLAY_BALL_MAGENTA_MEDIUM = addToTab(ITEMS.register("clay_ball_magenta_medium", () -> new Item(new Item.Properties())));
    public static final RegistryObject<Item> CLAY_BALL_MAGENTA_DARK = addToTab(ITEMS.register("clay_ball_magenta_dark", () -> new Item(new Item.Properties())));
    public static final RegistryObject<Item> CLAY_BALL_ORANGE_LIGHT = addToTab(ITEMS.register("clay_ball_orange_light", () -> new Item(new Item.Properties())));
    public static final RegistryObject<Item> CLAY_BALL_ORANGE_MEDIUM = addToTab(ITEMS.register("clay_ball_orange_medium", () -> new Item(new Item.Properties())));
    public static final RegistryObject<Item> CLAY_BALL_ORANGE_DARK = addToTab(ITEMS.register("clay_ball_orange_dark", () -> new Item(new Item.Properties())));
    public static final RegistryObject<Item> CLAY_BALL_PINK_LIGHT = addToTab(ITEMS.register("clay_ball_pink_light", () -> new Item(new Item.Properties())));
    public static final RegistryObject<Item> CLAY_BALL_PINK_MEDIUM = addToTab(ITEMS.register("clay_ball_pink_medium", () -> new Item(new Item.Properties())));
    public static final RegistryObject<Item> CLAY_BALL_PINK_DARK = addToTab(ITEMS.register("clay_ball_pink_dark", () -> new Item(new Item.Properties())));
    public static final RegistryObject<Item> CLAY_BALL_PURPLE_LIGHT = addToTab(ITEMS.register("clay_ball_purple_light", () -> new Item(new Item.Properties())));
    public static final RegistryObject<Item> CLAY_BALL_PURPLE_MEDIUM = addToTab(ITEMS.register("clay_ball_purple_medium", () -> new Item(new Item.Properties())));
    public static final RegistryObject<Item> CLAY_BALL_PURPLE_DARK = addToTab(ITEMS.register("clay_ball_purple_dark", () -> new Item(new Item.Properties())));
    public static final RegistryObject<Item> CLAY_BALL_RED_LIGHT = addToTab(ITEMS.register("clay_ball_red_light", () -> new Item(new Item.Properties())));
    public static final RegistryObject<Item> CLAY_BALL_RED_MEDIUM = addToTab(ITEMS.register("clay_ball_red_medium", () -> new Item(new Item.Properties())));
    public static final RegistryObject<Item> CLAY_BALL_RED_DARK = addToTab(ITEMS.register("clay_ball_red_dark", () -> new Item(new Item.Properties())));
    public static final RegistryObject<Item> CLAY_BALL_WHITE_LIGHT = addToTab(ITEMS.register("clay_ball_white_light", () -> new Item(new Item.Properties())));
    public static final RegistryObject<Item> CLAY_BALL_WHITE_MEDIUM = addToTab(ITEMS.register("clay_ball_white_medium", () -> new Item(new Item.Properties())));
    public static final RegistryObject<Item> CLAY_BALL_WHITE_DARK = addToTab(ITEMS.register("clay_ball_white_dark", () -> new Item(new Item.Properties())));
    public static final RegistryObject<Item> CLAY_BALL_YELLOW_LIGHT = addToTab(ITEMS.register("clay_ball_yellow_light", () -> new Item(new Item.Properties())));
    public static final RegistryObject<Item> CLAY_BALL_YELLOW_MEDIUM = addToTab(ITEMS.register("clay_ball_yellow_medium", () -> new Item(new Item.Properties())));
    public static final RegistryObject<Item> CLAY_BALL_YELLOW_DARK = addToTab(ITEMS.register("clay_ball_yellow_dark", () -> new Item(new Item.Properties())));

    public static final RegistryObject<Item> BRICK_BLACK_LIGHT = addToTab(ITEMS.register("brick_black_light", () -> new Item(new Item.Properties())));
    public static final RegistryObject<Item> BRICK_BLACK_MEDIUM = addToTab(ITEMS.register("brick_black_medium", () -> new Item(new Item.Properties())));
    public static final RegistryObject<Item> BRICK_BLACK_DARK = addToTab(ITEMS.register("brick_black_dark", () -> new Item(new Item.Properties())));
    public static final RegistryObject<Item> BRICK_BLUE_LIGHT = addToTab(ITEMS.register("brick_blue_light", () -> new Item(new Item.Properties())));
    public static final RegistryObject<Item> BRICK_BLUE_MEDIUM = addToTab(ITEMS.register("brick_blue_medium", () -> new Item(new Item.Properties())));
    public static final RegistryObject<Item> BRICK_BLUE_DARK = addToTab(ITEMS.register("brick_blue_dark", () -> new Item(new Item.Properties())));
    public static final RegistryObject<Item> BRICK_BROWN_LIGHT = addToTab(ITEMS.register("brick_brown_light", () -> new Item(new Item.Properties())));
    public static final RegistryObject<Item> BRICK_BROWN_MEDIUM = addToTab(ITEMS.register("brick_brown_medium", () -> new Item(new Item.Properties())));
    public static final RegistryObject<Item> BRICK_BROWN_DARK = addToTab(ITEMS.register("brick_brown_dark", () -> new Item(new Item.Properties())));
    public static final RegistryObject<Item> BRICK_CYAN_LIGHT = addToTab(ITEMS.register("brick_cyan_light", () -> new Item(new Item.Properties())));
    public static final RegistryObject<Item> BRICK_CYAN_MEDIUM = addToTab(ITEMS.register("brick_cyan_medium", () -> new Item(new Item.Properties())));
    public static final RegistryObject<Item> BRICK_CYAN_DARK = addToTab(ITEMS.register("brick_cyan_dark", () -> new Item(new Item.Properties())));
    public static final RegistryObject<Item> BRICK_GRAY_LIGHT = addToTab(ITEMS.register("brick_gray_light", () -> new Item(new Item.Properties())));
    public static final RegistryObject<Item> BRICK_GRAY_MEDIUM = addToTab(ITEMS.register("brick_gray_medium", () -> new Item(new Item.Properties())));
    public static final RegistryObject<Item> BRICK_GRAY_DARK = addToTab(ITEMS.register("brick_gray_dark", () -> new Item(new Item.Properties())));
    public static final RegistryObject<Item> BRICK_GREEN_LIGHT = addToTab(ITEMS.register("brick_green_light", () -> new Item(new Item.Properties())));
    public static final RegistryObject<Item> BRICK_GREEN_MEDIUM = addToTab(ITEMS.register("brick_green_medium", () -> new Item(new Item.Properties())));
    public static final RegistryObject<Item> BRICK_GREEN_DARK = addToTab(ITEMS.register("brick_green_dark", () -> new Item(new Item.Properties())));
    public static final RegistryObject<Item> BRICK_LIGHT_BLUE_LIGHT = addToTab(ITEMS.register("brick_light_blue_light", () -> new Item(new Item.Properties())));
    public static final RegistryObject<Item> BRICK_LIGHT_BLUE_MEDIUM = addToTab(ITEMS.register("brick_light_blue_medium", () -> new Item(new Item.Properties())));
    public static final RegistryObject<Item> BRICK_LIGHT_BLUE_DARK = addToTab(ITEMS.register("brick_light_blue_dark", () -> new Item(new Item.Properties())));
    public static final RegistryObject<Item> BRICK_LIGHT_GRAY_LIGHT = addToTab(ITEMS.register("brick_light_gray_light", () -> new Item(new Item.Properties())));
    public static final RegistryObject<Item> BRICK_LIGHT_GRAY_MEDIUM = addToTab(ITEMS.register("brick_light_gray_medium", () -> new Item(new Item.Properties())));
    public static final RegistryObject<Item> BRICK_LIGHT_GRAY_DARK = addToTab(ITEMS.register("brick_light_gray_dark", () -> new Item(new Item.Properties())));
    public static final RegistryObject<Item> BRICK_LIME_LIGHT = addToTab(ITEMS.register("brick_lime_light", () -> new Item(new Item.Properties())));
    public static final RegistryObject<Item> BRICK_LIME_MEDIUM = addToTab(ITEMS.register("brick_lime_medium", () -> new Item(new Item.Properties())));
    public static final RegistryObject<Item> BRICK_LIME_DARK = addToTab(ITEMS.register("brick_lime_dark", () -> new Item(new Item.Properties())));
    public static final RegistryObject<Item> BRICK_MAGENTA_LIGHT = addToTab(ITEMS.register("brick_magenta_light", () -> new Item(new Item.Properties())));
    public static final RegistryObject<Item> BRICK_MAGENTA_MEDIUM = addToTab(ITEMS.register("brick_magenta_medium", () -> new Item(new Item.Properties())));
    public static final RegistryObject<Item> BRICK_MAGENTA_DARK = addToTab(ITEMS.register("brick_magenta_dark", () -> new Item(new Item.Properties())));
    public static final RegistryObject<Item> BRICK_ORANGE_LIGHT = addToTab(ITEMS.register("brick_orange_light", () -> new Item(new Item.Properties())));
    public static final RegistryObject<Item> BRICK_ORANGE_MEDIUM = addToTab(ITEMS.register("brick_orange_medium", () -> new Item(new Item.Properties())));
    public static final RegistryObject<Item> BRICK_ORANGE_DARK = addToTab(ITEMS.register("brick_orange_dark", () -> new Item(new Item.Properties())));
    public static final RegistryObject<Item> BRICK_PINK_LIGHT = addToTab(ITEMS.register("brick_pink_light", () -> new Item(new Item.Properties())));
    public static final RegistryObject<Item> BRICK_PINK_MEDIUM = addToTab(ITEMS.register("brick_pink_medium", () -> new Item(new Item.Properties())));
    public static final RegistryObject<Item> BRICK_PINK_DARK = addToTab(ITEMS.register("brick_pink_dark", () -> new Item(new Item.Properties())));
    public static final RegistryObject<Item> BRICK_PURPLE_LIGHT = addToTab(ITEMS.register("brick_purple_light", () -> new Item(new Item.Properties())));
    public static final RegistryObject<Item> BRICK_PURPLE_MEDIUM = addToTab(ITEMS.register("brick_purple_medium", () -> new Item(new Item.Properties())));
    public static final RegistryObject<Item> BRICK_PURPLE_DARK = addToTab(ITEMS.register("brick_purple_dark", () -> new Item(new Item.Properties())));
    public static final RegistryObject<Item> BRICK_RED_LIGHT = addToTab(ITEMS.register("brick_red_light", () -> new Item(new Item.Properties())));
    public static final RegistryObject<Item> BRICK_RED_MEDIUM = addToTab(ITEMS.register("brick_red_medium", () -> new Item(new Item.Properties())));
    public static final RegistryObject<Item> BRICK_RED_DARK = addToTab(ITEMS.register("brick_red_dark", () -> new Item(new Item.Properties())));
    public static final RegistryObject<Item> BRICK_WHITE_LIGHT = addToTab(ITEMS.register("brick_white_light", () -> new Item(new Item.Properties())));
    public static final RegistryObject<Item> BRICK_WHITE_MEDIUM = addToTab(ITEMS.register("brick_white_medium", () -> new Item(new Item.Properties())));
    public static final RegistryObject<Item> BRICK_WHITE_DARK = addToTab(ITEMS.register("brick_white_dark", () -> new Item(new Item.Properties())));
    public static final RegistryObject<Item> BRICK_YELLOW_LIGHT = addToTab(ITEMS.register("brick_yellow_light", () -> new Item(new Item.Properties())));
    public static final RegistryObject<Item> BRICK_YELLOW_MEDIUM = addToTab(ITEMS.register("brick_yellow_medium", () -> new Item(new Item.Properties())));
    public static final RegistryObject<Item> BRICK_YELLOW_DARK = addToTab(ITEMS.register("brick_yellow_dark", () -> new Item(new Item.Properties())));

    public static final RegistryObject<Item> DYE_BLACK_LIGHT = addToTab(ITEMS.register("dye_black_light", () -> new Item(new Item.Properties())));
    public static final RegistryObject<Item> DYE_BLACK_DARK = addToTab(ITEMS.register("dye_black_dark", () -> new Item(new Item.Properties())));
    public static final RegistryObject<Item> DYE_BLUE_LIGHT = addToTab(ITEMS.register("dye_blue_light", () -> new Item(new Item.Properties())));
    public static final RegistryObject<Item> DYE_BLUE_DARK = addToTab(ITEMS.register("dye_blue_dark", () -> new Item(new Item.Properties())));
    public static final RegistryObject<Item> DYE_BROWN_LIGHT = addToTab(ITEMS.register("dye_brown_light", () -> new Item(new Item.Properties())));
    public static final RegistryObject<Item> DYE_BROWN_DARK = addToTab(ITEMS.register("dye_brown_dark", () -> new Item(new Item.Properties())));
    public static final RegistryObject<Item> DYE_CYAN_LIGHT = addToTab(ITEMS.register("dye_cyan_light", () -> new Item(new Item.Properties())));
    public static final RegistryObject<Item> DYE_CYAN_DARK = addToTab(ITEMS.register("dye_cyan_dark", () -> new Item(new Item.Properties())));
    public static final RegistryObject<Item> DYE_GRAY_LIGHT = addToTab(ITEMS.register("dye_gray_light", () -> new Item(new Item.Properties())));
    public static final RegistryObject<Item> DYE_GRAY_DARK = addToTab(ITEMS.register("dye_gray_dark", () -> new Item(new Item.Properties())));
    public static final RegistryObject<Item> DYE_GREEN_LIGHT = addToTab(ITEMS.register("dye_green_light", () -> new Item(new Item.Properties())));
    public static final RegistryObject<Item> DYE_GREEN_DARK = addToTab(ITEMS.register("dye_green_dark", () -> new Item(new Item.Properties())));
    public static final RegistryObject<Item> DYE_LIGHT_BLUE_LIGHT = addToTab(ITEMS.register("dye_light_blue_light", () -> new Item(new Item.Properties())));
    public static final RegistryObject<Item> DYE_LIGHT_BLUE_DARK = addToTab(ITEMS.register("dye_light_blue_dark", () -> new Item(new Item.Properties())));
    public static final RegistryObject<Item> DYE_LIGHT_GRAY_LIGHT = addToTab(ITEMS.register("dye_light_gray_light", () -> new Item(new Item.Properties())));
    public static final RegistryObject<Item> DYE_LIGHT_GRAY_DARK = addToTab(ITEMS.register("dye_light_gray_dark", () -> new Item(new Item.Properties())));
    public static final RegistryObject<Item> DYE_LIME_LIGHT = addToTab(ITEMS.register("dye_lime_light", () -> new Item(new Item.Properties())));
    public static final RegistryObject<Item> DYE_LIME_DARK = addToTab(ITEMS.register("dye_lime_dark", () -> new Item(new Item.Properties())));
    public static final RegistryObject<Item> DYE_MAGENTA_LIGHT = addToTab(ITEMS.register("dye_magenta_light", () -> new Item(new Item.Properties())));
    public static final RegistryObject<Item> DYE_MAGENTA_DARK = addToTab(ITEMS.register("dye_magenta_dark", () -> new Item(new Item.Properties())));
    public static final RegistryObject<Item> DYE_ORANGE_LIGHT = addToTab(ITEMS.register("dye_orange_light", () -> new Item(new Item.Properties())));
    public static final RegistryObject<Item> DYE_ORANGE_DARK = addToTab(ITEMS.register("dye_orange_dark", () -> new Item(new Item.Properties())));
    public static final RegistryObject<Item> DYE_PINK_LIGHT = addToTab(ITEMS.register("dye_pink_light", () -> new Item(new Item.Properties())));
    public static final RegistryObject<Item> DYE_PINK_DARK = addToTab(ITEMS.register("dye_pink_dark", () -> new Item(new Item.Properties())));
    public static final RegistryObject<Item> DYE_PURPLE_LIGHT = addToTab(ITEMS.register("dye_purple_light", () -> new Item(new Item.Properties())));
    public static final RegistryObject<Item> DYE_PURPLE_DARK = addToTab(ITEMS.register("dye_purple_dark", () -> new Item(new Item.Properties())));
    public static final RegistryObject<Item> DYE_RED_LIGHT = addToTab(ITEMS.register("dye_red_light", () -> new Item(new Item.Properties())));
    public static final RegistryObject<Item> DYE_RED_DARK = addToTab(ITEMS.register("dye_red_dark", () -> new Item(new Item.Properties())));
    public static final RegistryObject<Item> DYE_WHITE_LIGHT = addToTab(ITEMS.register("dye_white_light", () -> new Item(new Item.Properties())));
    public static final RegistryObject<Item> DYE_WHITE_DARK = addToTab(ITEMS.register("dye_white_dark", () -> new Item(new Item.Properties())));
    public static final RegistryObject<Item> DYE_YELLOW_LIGHT = addToTab(ITEMS.register("dye_yellow_light", () -> new Item(new Item.Properties())));
    public static final RegistryObject<Item> DYE_YELLOW_DARK = addToTab(ITEMS.register("dye_yellow_dark", () -> new Item(new Item.Properties())));

    //Block Items
    public static final RegistryObject<BlockItem> BAMBOO_BLOCK_ITEM = addToTab(ITEMS.register("bamboo_block", () -> new BlockItem(BlockInit.BAMBOO_BLOCK.get(), new Item.Properties())));
    public static final RegistryObject<BlockItem> BAMBOO_BUTTON_ITEM = addToTab(ITEMS.register("bamboo_button", () -> new BlockItem(BlockInit.BAMBOO_BUTTON.get(), new Item.Properties())));
    public static final RegistryObject<BlockItem> BAMBOO_DOOR_ITEM = addToTab(ITEMS.register("bamboo_door", () -> new BlockItem(BlockInit.BAMBOO_DOOR.get(), new Item.Properties())));
    public static final RegistryObject<BlockItem> BAMBOO_FENCE_ITEM = addToTab(ITEMS.register("bamboo_fence", () -> new BlockItem(BlockInit.BAMBOO_FENCE.get(), new Item.Properties())));
    public static final RegistryObject<BlockItem> BAMBOO_FENCE_GATE_ITEM = addToTab(ITEMS.register("bamboo_fence_gate", () -> new BlockItem(BlockInit.BAMBOO_FENCE_GATE.get(), new Item.Properties())));
    public static final RegistryObject<BlockItem> BAMBOO_LADDER_ITEM = addToTab(ITEMS.register("bamboo_ladder", () -> new BlockItem(BlockInit.BAMBOO_LADDER.get(), new Item.Properties())));
    public static final RegistryObject<BlockItem> BAMBOO_PRESSURE_PLATE_ITEM = addToTab(ITEMS.register("bamboo_pressure_plate", () -> new BlockItem(BlockInit.BAMBOO_PRESSURE_PLATE.get(), new Item.Properties())));
    public static final RegistryObject<BlockItem> BAMBOO_SLAB_ITEM = addToTab(ITEMS.register("bamboo_slab", () -> new BlockItem(BlockInit.BAMBOO_SLAB.get(), new Item.Properties())));
    public static final RegistryObject<BlockItem> BAMBOO_STAIRS_ITEM = addToTab(ITEMS.register("bamboo_stairs", () -> new BlockItem(BlockInit.BAMBOO_STAIRS.get(), new Item.Properties())));
    public static final RegistryObject<BlockItem> BAMBOO_TRAPDOOR_ITEM = addToTab(ITEMS.register("bamboo_trapdoor", () -> new BlockItem(BlockInit.BAMBOO_TRAPDOOR.get(), new Item.Properties())));

    public static final RegistryObject<BlockItem> THATCH_BLOCK_ITEM = addToTab(ITEMS.register("thatch_block", () -> new BlockItem(BlockInit.THATCH_BLOCK.get(), new Item.Properties())));
    public static final RegistryObject<BlockItem> THATCH_BUTTON_ITEM = addToTab(ITEMS.register("thatch_button", () -> new BlockItem(BlockInit.THATCH_BUTTON.get(), new Item.Properties())));
    public static final RegistryObject<BlockItem> THATCH_DOOR_ITEM = addToTab(ITEMS.register("thatch_door", () -> new BlockItem(BlockInit.THATCH_DOOR.get(), new Item.Properties())));
    public static final RegistryObject<BlockItem> THATCH_FENCE_ITEM = addToTab(ITEMS.register("thatch_fence", () -> new BlockItem(BlockInit.THATCH_FENCE.get(), new Item.Properties())));
    public static final RegistryObject<BlockItem> THATCH_FENCE_GATE_ITEM = addToTab(ITEMS.register("thatch_fence_gate", () -> new BlockItem(BlockInit.THATCH_FENCE_GATE.get(), new Item.Properties())));
    public static final RegistryObject<BlockItem> THATCH_LADDER_ITEM = addToTab(ITEMS.register("thatch_ladder", () -> new BlockItem(BlockInit.THATCH_LADDER.get(), new Item.Properties())));
    public static final RegistryObject<BlockItem> THATCH_PRESSURE_PLATE_ITEM = addToTab(ITEMS.register("thatch_pressure_plate", () -> new BlockItem(BlockInit.THATCH_PRESSURE_PLATE.get(), new Item.Properties())));
    public static final RegistryObject<BlockItem> THATCH_SLAB_ITEM = addToTab(ITEMS.register("thatch_slab", () -> new BlockItem(BlockInit.THATCH_SLAB.get(), new Item.Properties())));
    public static final RegistryObject<BlockItem> THATCH_STAIRS_ITEM = addToTab(ITEMS.register("thatch_stairs", () -> new BlockItem(BlockInit.THATCH_STAIRS.get(), new Item.Properties())));
    public static final RegistryObject<BlockItem> THATCH_TRAPDOOR_ITEM = addToTab(ITEMS.register("thatch_trapdoor", () -> new BlockItem(BlockInit.THATCH_TRAPDOOR.get(), new Item.Properties())));

    public static final RegistryObject<BlockItem> ACACIA_BEAM_UP_ITEM = addToTab(ITEMS.register("acacia_beam_up", () -> new BlockItem(BlockInit.ACACIA_BEAM_UP.get(), new Item.Properties())));
    public static final RegistryObject<BlockItem> ACACIA_BEAM_MIDDLE_ITEM = addToTab(ITEMS.register("acacia_beam_middle", () -> new BlockItem(BlockInit.ACACIA_BEAM_MIDDLE.get(), new Item.Properties())));
    public static final RegistryObject<BlockItem> ACACIA_BEAM_DOWN_ITEM = addToTab(ITEMS.register("acacia_beam_down", () -> new BlockItem(BlockInit.ACACIA_BEAM_DOWN.get(), new Item.Properties())));
    public static final RegistryObject<BlockItem> BIRCH_BEAM_UP_ITEM = addToTab(ITEMS.register("birch_beam_up", () -> new BlockItem(BlockInit.BIRCH_BEAM_UP.get(), new Item.Properties())));
    public static final RegistryObject<BlockItem> BIRCH_BEAM_MIDDLE_ITEM = addToTab(ITEMS.register("birch_beam_middle", () -> new BlockItem(BlockInit.BIRCH_BEAM_MIDDLE.get(), new Item.Properties())));
    public static final RegistryObject<BlockItem> BIRCH_BEAM_DOWN_ITEM = addToTab(ITEMS.register("birch_beam_down", () -> new BlockItem(BlockInit.BIRCH_BEAM_DOWN.get(), new Item.Properties())));
    public static final RegistryObject<BlockItem> CHERRY_BEAM_UP_ITEM = addToTab(ITEMS.register("cherry_beam_up", () -> new BlockItem(BlockInit.CHERRY_BEAM_UP.get(), new Item.Properties())));
    public static final RegistryObject<BlockItem> CHERRY_BEAM_MIDDLE_ITEM = addToTab(ITEMS.register("cherry_beam_middle", () -> new BlockItem(BlockInit.CHERRY_BEAM_MIDDLE.get(), new Item.Properties())));
    public static final RegistryObject<BlockItem> CHERRY_BEAM_DOWN_ITEM = addToTab(ITEMS.register("cherry_beam_down", () -> new BlockItem(BlockInit.CHERRY_BEAM_DOWN.get(), new Item.Properties())));
    public static final RegistryObject<BlockItem> CRIMSON_BEAM_UP_ITEM = addToTab(ITEMS.register("crimson_beam_up", () -> new BlockItem(BlockInit.CRIMSON_BEAM_UP.get(), new Item.Properties())));
    public static final RegistryObject<BlockItem> CRIMSON_BEAM_MIDDLE_ITEM = addToTab(ITEMS.register("crimson_beam_middle", () -> new BlockItem(BlockInit.CRIMSON_BEAM_MIDDLE.get(), new Item.Properties())));
    public static final RegistryObject<BlockItem> CRIMSON_BEAM_DOWN_ITEM = addToTab(ITEMS.register("crimson_beam_down", () -> new BlockItem(BlockInit.CRIMSON_BEAM_DOWN.get(), new Item.Properties())));
    public static final RegistryObject<BlockItem> DARK_OAK_BEAM_UP_ITEM = addToTab(ITEMS.register("dark_oak_beam_up", () -> new BlockItem(BlockInit.DARK_OAK_BEAM_UP.get(), new Item.Properties())));
    public static final RegistryObject<BlockItem> DARK_OAK_BEAM_MIDDLE_ITEM = addToTab(ITEMS.register("dark_oak_beam_middle", () -> new BlockItem(BlockInit.DARK_OAK_BEAM_MIDDLE.get(), new Item.Properties())));
    public static final RegistryObject<BlockItem> DARK_OAK_BEAM_DOWN_ITEM = addToTab(ITEMS.register("dark_oak_beam_down", () -> new BlockItem(BlockInit.DARK_OAK_BEAM_DOWN.get(), new Item.Properties())));
    public static final RegistryObject<BlockItem> JUNGLE_BEAM_UP_ITEM = addToTab(ITEMS.register("jungle_beam_up", () -> new BlockItem(BlockInit.JUNGLE_BEAM_UP.get(), new Item.Properties())));
    public static final RegistryObject<BlockItem> JUNGLE_BEAM_MIDDLE_ITEM = addToTab(ITEMS.register("jungle_beam_middle", () -> new BlockItem(BlockInit.JUNGLE_BEAM_MIDDLE.get(), new Item.Properties())));
    public static final RegistryObject<BlockItem> JUNGLE_BEAM_DOWN_ITEM = addToTab(ITEMS.register("jungle_beam_down", () -> new BlockItem(BlockInit.JUNGLE_BEAM_DOWN.get(), new Item.Properties())));
    public static final RegistryObject<BlockItem> MANGROVE_BEAM_UP_ITEM = addToTab(ITEMS.register("mangrove_beam_up", () -> new BlockItem(BlockInit.MANGROVE_BEAM_UP.get(), new Item.Properties())));
    public static final RegistryObject<BlockItem> MANGROVE_BEAM_MIDDLE_ITEM = addToTab(ITEMS.register("mangrove_beam_middle", () -> new BlockItem(BlockInit.MANGROVE_BEAM_MIDDLE.get(), new Item.Properties())));
    public static final RegistryObject<BlockItem> MANGROVE_BEAM_DOWN_ITEM = addToTab(ITEMS.register("mangrove_beam_down", () -> new BlockItem(BlockInit.MANGROVE_BEAM_DOWN.get(), new Item.Properties())));
    public static final RegistryObject<BlockItem> OAK_BEAM_UP_ITEM = addToTab(ITEMS.register("oak_beam_up", () -> new BlockItem(BlockInit.OAK_BEAM_UP.get(), new Item.Properties())));
    public static final RegistryObject<BlockItem> OAK_BEAM_MIDDLE_ITEM = addToTab(ITEMS.register("oak_beam_middle", () -> new BlockItem(BlockInit.OAK_BEAM_MIDDLE.get(), new Item.Properties())));
    public static final RegistryObject<BlockItem> OAK_BEAM_DOWN_ITEM = addToTab(ITEMS.register("oak_beam_down", () -> new BlockItem(BlockInit.OAK_BEAM_DOWN.get(), new Item.Properties())));
    public static final RegistryObject<BlockItem> SPRUCE_BEAM_UP_ITEM = addToTab(ITEMS.register("spruce_beam_up", () -> new BlockItem(BlockInit.SPRUCE_BEAM_UP.get(), new Item.Properties())));
    public static final RegistryObject<BlockItem> SPRUCE_BEAM_MIDDLE_ITEM = addToTab(ITEMS.register("spruce_beam_middle", () -> new BlockItem(BlockInit.SPRUCE_BEAM_MIDDLE.get(), new Item.Properties())));
    public static final RegistryObject<BlockItem> SPRUCE_BEAM_DOWN_ITEM = addToTab(ITEMS.register("spruce_beam_down", () -> new BlockItem(BlockInit.SPRUCE_BEAM_DOWN.get(), new Item.Properties())));
    public static final RegistryObject<BlockItem> WARPED_BEAM_UP_ITEM = addToTab(ITEMS.register("warped_beam_up", () -> new BlockItem(BlockInit.WARPED_BEAM_UP.get(), new Item.Properties())));
    public static final RegistryObject<BlockItem> WARPED_BEAM_MIDDLE_ITEM = addToTab(ITEMS.register("warped_beam_middle", () -> new BlockItem(BlockInit.WARPED_BEAM_MIDDLE.get(), new Item.Properties())));
    public static final RegistryObject<BlockItem> WARPED_BEAM_DOWN_ITEM = addToTab(ITEMS.register("warped_beam_down", () -> new BlockItem(BlockInit.WARPED_BEAM_DOWN.get(), new Item.Properties())));

    public static final RegistryObject<BlockItem> ACACIA_LADDER_ITEM = addToTab(ITEMS.register("acacia_ladder", () -> new BlockItem(BlockInit.ACACIA_LADDER.get(), new Item.Properties())));
    public static final RegistryObject<BlockItem> BIRCH_LADDER_ITEM = addToTab(ITEMS.register("birch_ladder", () -> new BlockItem(BlockInit.BIRCH_LADDER.get(), new Item.Properties())));
    public static final RegistryObject<BlockItem> CHERRY_LADDER_ITEM = addToTab(ITEMS.register("cherry_ladder", () -> new BlockItem(BlockInit.CHERRY_LADDER.get(), new Item.Properties())));
    public static final RegistryObject<BlockItem> CRIMSON_LADDER_ITEM = addToTab(ITEMS.register("crimson_ladder", () -> new BlockItem(BlockInit.CRIMSON_LADDER.get(), new Item.Properties())));
    public static final RegistryObject<BlockItem> DARK_OAK_LADDER_ITEM = addToTab(ITEMS.register("dark_oak_ladder", () -> new BlockItem(BlockInit.DARK_OAK_LADDER.get(), new Item.Properties())));
    public static final RegistryObject<BlockItem> JUNGLE_LADDER_ITEM = addToTab(ITEMS.register("jungle_ladder", () -> new BlockItem(BlockInit.JUNGLE_LADDER.get(), new Item.Properties())));
    public static final RegistryObject<BlockItem> MANGROVE_LADDER_ITEM = addToTab(ITEMS.register("mangrove_ladder", () -> new BlockItem(BlockInit.MANGROVE_LADDER.get(), new Item.Properties())));
    public static final RegistryObject<BlockItem> OAK_LADDER_ITEM = addToTab(ITEMS.register("oak_ladder", () -> new BlockItem(BlockInit.OAK_LADDER.get(), new Item.Properties())));
    public static final RegistryObject<BlockItem> SPRUCE_LADDER_ITEM = addToTab(ITEMS.register("spruce_ladder", () -> new BlockItem(BlockInit.SPRUCE_LADDER.get(), new Item.Properties())));
    public static final RegistryObject<BlockItem> WARPED_LADDER_ITEM = addToTab(ITEMS.register("warped_ladder", () -> new BlockItem(BlockInit.WARPED_LADDER.get(), new Item.Properties())));

    public static final RegistryObject<BlockItem> ACACIA_TORCH_ITEM = addToTab(ITEMS.register("acacia_torch", () -> new StandingAndWallBlockItem(BlockInit.ACACIA_TORCH.get(), BlockInit.ACACIA_WALL_TORCH.get(), new Item.Properties(), Direction.DOWN)));
    public static final RegistryObject<BlockItem> BIRCH_TORCH_ITEM = addToTab(ITEMS.register("birch_torch", () -> new StandingAndWallBlockItem(BlockInit.BIRCH_TORCH.get(), BlockInit.BIRCH_WALL_TORCH.get(), new Item.Properties(), Direction.DOWN)));
    public static final RegistryObject<BlockItem> CHERRY_TORCH_ITEM = addToTab(ITEMS.register("cherry_torch", () -> new StandingAndWallBlockItem(BlockInit.CHERRY_TORCH.get(), BlockInit.CHERRY_WALL_TORCH.get(), new Item.Properties(), Direction.DOWN)));
    public static final RegistryObject<BlockItem> CRIMSON_TORCH_ITEM = addToTab(ITEMS.register("crimson_torch", () -> new StandingAndWallBlockItem(BlockInit.CRIMSON_TORCH.get(), BlockInit.CRIMSON_WALL_TORCH.get(), new Item.Properties(), Direction.DOWN)));
    public static final RegistryObject<BlockItem> DARK_OAK_TORCH_ITEM = addToTab(ITEMS.register("dark_oak_torch", () -> new StandingAndWallBlockItem(BlockInit.DARK_OAK_TORCH.get(), BlockInit.DARK_OAK_WALL_TORCH.get(), new Item.Properties(), Direction.DOWN)));
    public static final RegistryObject<BlockItem> JUNGLE_TORCH_ITEM = addToTab(ITEMS.register("jungle_torch", () -> new StandingAndWallBlockItem(BlockInit.JUNGLE_TORCH.get(), BlockInit.JUNGLE_WALL_TORCH.get(), new Item.Properties(), Direction.DOWN)));
    public static final RegistryObject<BlockItem> MANGROVE_TORCH_ITEM = addToTab(ITEMS.register("mangrove_torch", () -> new StandingAndWallBlockItem(BlockInit.MANGROVE_TORCH.get(), BlockInit.MANGROVE_WALL_TORCH.get(), new Item.Properties(), Direction.DOWN)));
    public static final RegistryObject<BlockItem> OAK_TORCH_ITEM = addToTab(ITEMS.register("oak_torch", () -> new StandingAndWallBlockItem(BlockInit.OAK_TORCH.get(), BlockInit.OAK_WALL_TORCH.get(), new Item.Properties(), Direction.DOWN)));
    public static final RegistryObject<BlockItem> SPRUCE_TORCH_ITEM = addToTab(ITEMS.register("spruce_torch", () -> new StandingAndWallBlockItem(BlockInit.SPRUCE_TORCH.get(), BlockInit.SPRUCE_WALL_TORCH.get(), new Item.Properties(), Direction.DOWN)));
    public static final RegistryObject<BlockItem> WARPED_TORCH_ITEM = addToTab(ITEMS.register("warped_torch", () -> new StandingAndWallBlockItem(BlockInit.WARPED_TORCH.get(), BlockInit.WARPED_WALL_TORCH.get(), new Item.Properties(), Direction.DOWN)));

    public static final RegistryObject<BlockItem> ACACIA_SOUL_TORCH_ITEM = addToTab(ITEMS.register("acacia_soul_torch", () -> new StandingAndWallBlockItem(BlockInit.ACACIA_SOUL_TORCH.get(), BlockInit.ACACIA_WALL_SOUL_TORCH.get(), new Item.Properties(), Direction.DOWN)));
    public static final RegistryObject<BlockItem> BIRCH_SOUL_TORCH_ITEM = addToTab(ITEMS.register("birch_soul_torch", () -> new StandingAndWallBlockItem(BlockInit.BIRCH_SOUL_TORCH.get(), BlockInit.BIRCH_WALL_SOUL_TORCH.get(), new Item.Properties(), Direction.DOWN)));
    public static final RegistryObject<BlockItem> CHERRY_SOUL_TORCH_ITEM = addToTab(ITEMS.register("cherry_soul_torch", () -> new StandingAndWallBlockItem(BlockInit.CHERRY_SOUL_TORCH.get(), BlockInit.CHERRY_WALL_SOUL_TORCH.get(), new Item.Properties(), Direction.DOWN)));
    public static final RegistryObject<BlockItem> CRIMSON_SOUL_TORCH_ITEM = addToTab(ITEMS.register("crimson_soul_torch", () -> new StandingAndWallBlockItem(BlockInit.CRIMSON_SOUL_TORCH.get(), BlockInit.CRIMSON_WALL_SOUL_TORCH.get(), new Item.Properties(), Direction.DOWN)));
    public static final RegistryObject<BlockItem> DARK_OAK_SOUL_TORCH_ITEM = addToTab(ITEMS.register("dark_oak_soul_torch", () -> new StandingAndWallBlockItem(BlockInit.DARK_OAK_SOUL_TORCH.get(), BlockInit.DARK_OAK_WALL_SOUL_TORCH.get(), new Item.Properties(), Direction.DOWN)));
    public static final RegistryObject<BlockItem> JUNGLE_SOUL_TORCH_ITEM = addToTab(ITEMS.register("jungle_soul_torch", () -> new StandingAndWallBlockItem(BlockInit.JUNGLE_SOUL_TORCH.get(), BlockInit.JUNGLE_WALL_SOUL_TORCH.get(), new Item.Properties(), Direction.DOWN)));
    public static final RegistryObject<BlockItem> MANGROVE_SOUL_TORCH_ITEM = addToTab(ITEMS.register("mangrove_soul_torch", () -> new StandingAndWallBlockItem(BlockInit.MANGROVE_SOUL_TORCH.get(), BlockInit.MANGROVE_WALL_SOUL_TORCH.get(), new Item.Properties(), Direction.DOWN)));
    public static final RegistryObject<BlockItem> OAK_SOUL_TORCH_ITEM = addToTab(ITEMS.register("oak_soul_torch", () -> new StandingAndWallBlockItem(BlockInit.OAK_SOUL_TORCH.get(), BlockInit.OAK_WALL_SOUL_TORCH.get(), new Item.Properties(), Direction.DOWN)));
    public static final RegistryObject<BlockItem> SPRUCE_SOUL_TORCH_ITEM = addToTab(ITEMS.register("spruce_soul_torch", () -> new StandingAndWallBlockItem(BlockInit.SPRUCE_SOUL_TORCH.get(), BlockInit.SPRUCE_WALL_SOUL_TORCH.get(), new Item.Properties(), Direction.DOWN)));
    public static final RegistryObject<BlockItem> WARPED_SOUL_TORCH_ITEM = addToTab(ITEMS.register("warped_soul_torch", () -> new StandingAndWallBlockItem(BlockInit.WARPED_SOUL_TORCH.get(), BlockInit.WARPED_WALL_SOUL_TORCH.get(), new Item.Properties(), Direction.DOWN)));

    public static final RegistryObject<BlockItem> MOSSY_STONE_ITEM = addToTab(ITEMS.register("mossy_stone", () -> new BlockItem(BlockInit.MOSSY_STONE.get(), new Item.Properties())));
    public static final RegistryObject<BlockItem> MOSSY_STONE_BUTTON_ITEM = addToTab(ITEMS.register("mossy_stone_button", () -> new BlockItem(BlockInit.MOSSY_STONE_BUTTON.get(), new Item.Properties())));
    public static final RegistryObject<BlockItem> MOSSY_STONE_PRESSURE_PLATE_ITEM = addToTab(ITEMS.register("mossy_stone_pressure_plate", () -> new BlockItem(BlockInit.MOSSY_STONE_PRESSURE_PLATE.get(), new Item.Properties())));
    public static final RegistryObject<BlockItem> MOSSY_STONE_SLAB_ITEM = addToTab(ITEMS.register("mossy_stone_slab", () -> new BlockItem(BlockInit.MOSSY_STONE_SLAB.get(), new Item.Properties())));
    public static final RegistryObject<BlockItem> MOSSY_STONE_STAIRS_ITEM = addToTab(ITEMS.register("mossy_stone_stairs", () -> new BlockItem(BlockInit.MOSSY_STONE_STAIRS.get(), new Item.Properties())));
    public static final RegistryObject<BlockItem> MOSSY_STONE_WALL_ITEM = addToTab(ITEMS.register("mossy_stone_wall", () -> new BlockItem(BlockInit.MOSSY_STONE_WALL.get(), new Item.Properties())));

}