package mod.silverwolf.silverwolfsbuildingblocks.init;

import mod.silverwolf.silverwolfsbuildingblocks.SilverwolfsBuildingBlocks;
import net.minecraft.world.item.BlockItem;
import net.minecraft.world.item.Item;
import net.minecraftforge.registries.DeferredRegister;
import net.minecraftforge.registries.ForgeRegistries;
import net.minecraftforge.registries.RegistryObject;

import static mod.silverwolf.silverwolfsbuildingblocks.init.CreativeTabInit.addToTab;

public class ItemInit {
    public static final DeferredRegister<Item> ITEMS = DeferredRegister.create(ForgeRegistries.ITEMS, SilverwolfsBuildingBlocks.MODID);

    //Items
    public static final RegistryObject<Item> THATCH = addToTab(ITEMS.register("thatch", () -> new Item(new Item.Properties())));

    public static final RegistryObject<Item> ACACIA_STICK = addToTab(ITEMS.register("acacia_stick", () -> new Item(new Item.Properties())));
    public static final RegistryObject<Item> BIRCH_STICK = addToTab(ITEMS.register("birch_stick", () -> new Item(new Item.Properties())));
    public static final RegistryObject<Item> CHERRY_STICK = addToTab(ITEMS.register("cherry_stick", () -> new Item(new Item.Properties())));
    public static final RegistryObject<Item> CRIMSON_STICK = addToTab(ITEMS.register("crimson_stick", () -> new Item(new Item.Properties())));
    public static final RegistryObject<Item> DARK_OAK_STICK = addToTab(ITEMS.register("dark_oak_stick", () -> new Item(new Item.Properties())));
    public static final RegistryObject<Item> JUNGLE_STICK = addToTab(ITEMS.register("jungle_stick", () -> new Item(new Item.Properties())));
    public static final RegistryObject<Item> MANGROVE_STICK = addToTab(ITEMS.register("mangrove_stick", () -> new Item(new Item.Properties())));
    public static final RegistryObject<Item> OAK_STICK = addToTab(ITEMS.register("oak_stick", () -> new Item(new Item.Properties())));
    public static final RegistryObject<Item> SPRUCE_STICK = addToTab(ITEMS.register("spruce_stick", () -> new Item(new Item.Properties())));
    public static final RegistryObject<Item> WARPED_STICK = addToTab(ITEMS.register("warped_stick", () -> new Item(new Item.Properties())));

    public static final RegistryObject<Item> CLAY_BALL_BLACK_LIGHT = addToTab(ITEMS.register("clay_ball_black_light", () -> new Item(new Item.Properties())));
    public static final RegistryObject<Item> CLAY_BALL_BLACK_MEDIUM = addToTab(ITEMS.register("clay_ball_black_medium", () -> new Item(new Item.Properties())));
    public static final RegistryObject<Item> CLAY_BALL_BLACK_DARK = addToTab(ITEMS.register("clay_ball_black_dark", () -> new Item(new Item.Properties())));
    public static final RegistryObject<Item> CLAY_BALL_BLUE_LIGHT = addToTab(ITEMS.register("clay_ball_blue_light", () -> new Item(new Item.Properties())));
    public static final RegistryObject<Item> CLAY_BALL_BLUE_MEDIUM = addToTab(ITEMS.register("clay_ball_blue_medium", () -> new Item(new Item.Properties())));
    public static final RegistryObject<Item> CLAY_BALL_BLUE_DARK = addToTab(ITEMS.register("clay_ball_blue_dark", () -> new Item(new Item.Properties())));
    public static final RegistryObject<Item> CLAY_BALL_BROWN_LIGHT = addToTab(ITEMS.register("clay_ball_brown_light", () -> new Item(new Item.Properties())));
    public static final RegistryObject<Item> CLAY_BALL_BROWN_MEDIUM = addToTab(ITEMS.register("clay_ball_brown_medium", () -> new Item(new Item.Properties())));
    public static final RegistryObject<Item> CLAY_BALL_BROWN_DARK = addToTab(ITEMS.register("clay_ball_brown_dark", () -> new Item(new Item.Properties())));
    public static final RegistryObject<Item> CLAY_BALL_CYAN_LIGHT = addToTab(ITEMS.register("clay_ball_cyan_light", () -> new Item(new Item.Properties())));
    public static final RegistryObject<Item> CLAY_BALL_CYAN_MEDIUM = addToTab(ITEMS.register("clay_ball_cyan_medium", () -> new Item(new Item.Properties())));
    public static final RegistryObject<Item> CLAY_BALL_CYAN_DARK = addToTab(ITEMS.register("clay_ball_cyan_dark", () -> new Item(new Item.Properties())));
    public static final RegistryObject<Item> CLAY_BALL_GRAY_LIGHT = addToTab(ITEMS.register("clay_ball_gray_light", () -> new Item(new Item.Properties())));
    public static final RegistryObject<Item> CLAY_BALL_GRAY_MEDIUM = addToTab(ITEMS.register("clay_ball_gray_medium", () -> new Item(new Item.Properties())));
    public static final RegistryObject<Item> CLAY_BALL_GRAY_DARK = addToTab(ITEMS.register("clay_ball_gray_dark", () -> new Item(new Item.Properties())));
    public static final RegistryObject<Item> CLAY_BALL_GREEN_LIGHT = addToTab(ITEMS.register("clay_ball_green_light", () -> new Item(new Item.Properties())));
    public static final RegistryObject<Item> CLAY_BALL_GREEN_MEDIUM = addToTab(ITEMS.register("clay_ball_green_medium", () -> new Item(new Item.Properties())));
    public static final RegistryObject<Item> CLAY_BALL_GREEN_DARK = addToTab(ITEMS.register("clay_ball_green_dark", () -> new Item(new Item.Properties())));
    public static final RegistryObject<Item> CLAY_BALL_LIGHT_BLUE_LIGHT = addToTab(ITEMS.register("clay_ball_light_blue_light", () -> new Item(new Item.Properties())));
    public static final RegistryObject<Item> CLAY_BALL_LIGHT_BLUE_MEDIUM = addToTab(ITEMS.register("clay_ball_light_blue_medium", () -> new Item(new Item.Properties())));
    public static final RegistryObject<Item> CLAY_BALL_LIGHT_BLUE_DARK = addToTab(ITEMS.register("clay_ball_light_blue_dark", () -> new Item(new Item.Properties())));
    public static final RegistryObject<Item> CLAY_BALL_LIGHT_GRAY_LIGHT = addToTab(ITEMS.register("clay_ball_light_gray_light", () -> new Item(new Item.Properties())));
    public static final RegistryObject<Item> CLAY_BALL_LIGHT_GRAY_MEDIUM = addToTab(ITEMS.register("clay_ball_light_gray_medium", () -> new Item(new Item.Properties())));
    public static final RegistryObject<Item> CLAY_BALL_LIGHT_GRAY_DARK = addToTab(ITEMS.register("clay_ball_light_gray_dark", () -> new Item(new Item.Properties())));
    public static final RegistryObject<Item> CLAY_BALL_LIME_LIGHT = addToTab(ITEMS.register("clay_ball_lime_light", () -> new Item(new Item.Properties())));
    public static final RegistryObject<Item> CLAY_BALL_LIME_MEDIUM = addToTab(ITEMS.register("clay_ball_lime_medium", () -> new Item(new Item.Properties())));
    public static final RegistryObject<Item> CLAY_BALL_LIME_DARK = addToTab(ITEMS.register("clay_ball_lime_dark", () -> new Item(new Item.Properties())));
    public static final RegistryObject<Item> CLAY_BALL_MAGENTA_LIGHT = addToTab(ITEMS.register("clay_ball_magenta_light", () -> new Item(new Item.Properties())));
    public static final RegistryObject<Item> CLAY_BALL_MAGENTA_MEDIUM = addToTab(ITEMS.register("clay_ball_magenta_medium", () -> new Item(new Item.Properties())));
    public static final RegistryObject<Item> CLAY_BALL_MAGENTA_DARK = addToTab(ITEMS.register("clay_ball_magenta_dark", () -> new Item(new Item.Properties())));
    public static final RegistryObject<Item> CLAY_BALL_ORANGE_LIGHT = addToTab(ITEMS.register("clay_ball_orange_light", () -> new Item(new Item.Properties())));
    public static final RegistryObject<Item> CLAY_BALL_ORANGE_MEDIUM = addToTab(ITEMS.register("clay_ball_orange_medium", () -> new Item(new Item.Properties())));
    public static final RegistryObject<Item> CLAY_BALL_ORANGE_DARK = addToTab(ITEMS.register("clay_ball_orange_dark", () -> new Item(new Item.Properties())));
    public static final RegistryObject<Item> CLAY_BALL_PINK_LIGHT = addToTab(ITEMS.register("clay_ball_pink_light", () -> new Item(new Item.Properties())));
    public static final RegistryObject<Item> CLAY_BALL_PINK_MEDIUM = addToTab(ITEMS.register("clay_ball_pink_medium", () -> new Item(new Item.Properties())));
    public static final RegistryObject<Item> CLAY_BALL_PINK_DARK = addToTab(ITEMS.register("clay_ball_pink_dark", () -> new Item(new Item.Properties())));
    public static final RegistryObject<Item> CLAY_BALL_PURPLE_LIGHT = addToTab(ITEMS.register("clay_ball_purple_light", () -> new Item(new Item.Properties())));
    public static final RegistryObject<Item> CLAY_BALL_PURPLE_MEDIUM = addToTab(ITEMS.register("clay_ball_purple_medium", () -> new Item(new Item.Properties())));
    public static final RegistryObject<Item> CLAY_BALL_PURPLE_DARK = addToTab(ITEMS.register("clay_ball_purple_dark", () -> new Item(new Item.Properties())));
    public static final RegistryObject<Item> CLAY_BALL_RED_LIGHT = addToTab(ITEMS.register("clay_ball_red_light", () -> new Item(new Item.Properties())));
    public static final RegistryObject<Item> CLAY_BALL_RED_MEDIUM = addToTab(ITEMS.register("clay_ball_red_medium", () -> new Item(new Item.Properties())));
    public static final RegistryObject<Item> CLAY_BALL_RED_DARK = addToTab(ITEMS.register("clay_ball_red_dark", () -> new Item(new Item.Properties())));
    public static final RegistryObject<Item> CLAY_BALL_WHITE_LIGHT = addToTab(ITEMS.register("clay_ball_white_light", () -> new Item(new Item.Properties())));
    public static final RegistryObject<Item> CLAY_BALL_WHITE_MEDIUM = addToTab(ITEMS.register("clay_ball_white_medium", () -> new Item(new Item.Properties())));
    public static final RegistryObject<Item> CLAY_BALL_WHITE_DARK = addToTab(ITEMS.register("clay_ball_white_dark", () -> new Item(new Item.Properties())));
    public static final RegistryObject<Item> CLAY_BALL_YELLOW_LIGHT = addToTab(ITEMS.register("clay_ball_yellow_light", () -> new Item(new Item.Properties())));
    public static final RegistryObject<Item> CLAY_BALL_YELLOW_MEDIUM = addToTab(ITEMS.register("clay_ball_yellow_medium", () -> new Item(new Item.Properties())));
    public static final RegistryObject<Item> CLAY_BALL_YELLOW_DARK = addToTab(ITEMS.register("clay_ball_yellow_dark", () -> new Item(new Item.Properties())));

    public static final RegistryObject<Item> BRICK_BLACK_LIGHT = addToTab(ITEMS.register("brick_black_light", () -> new Item(new Item.Properties())));
    public static final RegistryObject<Item> BRICK_BLACK_MEDIUM = addToTab(ITEMS.register("brick_black_medium", () -> new Item(new Item.Properties())));
    public static final RegistryObject<Item> BRICK_BLACK_DARK = addToTab(ITEMS.register("brick_black_dark", () -> new Item(new Item.Properties())));
    public static final RegistryObject<Item> BRICK_BLUE_LIGHT = addToTab(ITEMS.register("brick_blue_light", () -> new Item(new Item.Properties())));
    public static final RegistryObject<Item> BRICK_BLUE_MEDIUM = addToTab(ITEMS.register("brick_blue_medium", () -> new Item(new Item.Properties())));
    public static final RegistryObject<Item> BRICK_BLUE_DARK = addToTab(ITEMS.register("brick_blue_dark", () -> new Item(new Item.Properties())));
    public static final RegistryObject<Item> BRICK_BROWN_LIGHT = addToTab(ITEMS.register("brick_brown_light", () -> new Item(new Item.Properties())));
    public static final RegistryObject<Item> BRICK_BROWN_MEDIUM = addToTab(ITEMS.register("brick_brown_medium", () -> new Item(new Item.Properties())));
    public static final RegistryObject<Item> BRICK_BROWN_DARK = addToTab(ITEMS.register("brick_brown_dark", () -> new Item(new Item.Properties())));
    public static final RegistryObject<Item> BRICK_CYAN_LIGHT = addToTab(ITEMS.register("brick_cyan_light", () -> new Item(new Item.Properties())));
    public static final RegistryObject<Item> BRICK_CYAN_MEDIUM = addToTab(ITEMS.register("brick_cyan_medium", () -> new Item(new Item.Properties())));
    public static final RegistryObject<Item> BRICK_CYAN_DARK = addToTab(ITEMS.register("brick_cyan_dark", () -> new Item(new Item.Properties())));
    public static final RegistryObject<Item> BRICK_GRAY_LIGHT = addToTab(ITEMS.register("brick_gray_light", () -> new Item(new Item.Properties())));
    public static final RegistryObject<Item> BRICK_GRAY_MEDIUM = addToTab(ITEMS.register("brick_gray_medium", () -> new Item(new Item.Properties())));
    public static final RegistryObject<Item> BRICK_GRAY_DARK = addToTab(ITEMS.register("brick_gray_dark", () -> new Item(new Item.Properties())));
    public static final RegistryObject<Item> BRICK_GREEN_LIGHT = addToTab(ITEMS.register("brick_green_light", () -> new Item(new Item.Properties())));
    public static final RegistryObject<Item> BRICK_GREEN_MEDIUM = addToTab(ITEMS.register("brick_green_medium", () -> new Item(new Item.Properties())));
    public static final RegistryObject<Item> BRICK_GREEN_DARK = addToTab(ITEMS.register("brick_green_dark", () -> new Item(new Item.Properties())));
    public static final RegistryObject<Item> BRICK_LIGHT_BLUE_LIGHT = addToTab(ITEMS.register("brick_light_blue_light", () -> new Item(new Item.Properties())));
    public static final RegistryObject<Item> BRICK_LIGHT_BLUE_MEDIUM = addToTab(ITEMS.register("brick_light_blue_medium", () -> new Item(new Item.Properties())));
    public static final RegistryObject<Item> BRICK_LIGHT_BLUE_DARK = addToTab(ITEMS.register("brick_light_blue_dark", () -> new Item(new Item.Properties())));
    public static final RegistryObject<Item> BRICK_LIGHT_GRAY_LIGHT = addToTab(ITEMS.register("brick_light_gray_light", () -> new Item(new Item.Properties())));
    public static final RegistryObject<Item> BRICK_LIGHT_GRAY_MEDIUM = addToTab(ITEMS.register("brick_light_gray_medium", () -> new Item(new Item.Properties())));
    public static final RegistryObject<Item> BRICK_LIGHT_GRAY_DARK = addToTab(ITEMS.register("brick_light_gray_dark", () -> new Item(new Item.Properties())));
    public static final RegistryObject<Item> BRICK_LIME_LIGHT = addToTab(ITEMS.register("brick_lime_light", () -> new Item(new Item.Properties())));
    public static final RegistryObject<Item> BRICK_LIME_MEDIUM = addToTab(ITEMS.register("brick_lime_medium", () -> new Item(new Item.Properties())));
    public static final RegistryObject<Item> BRICK_LIME_DARK = addToTab(ITEMS.register("brick_lime_dark", () -> new Item(new Item.Properties())));
    public static final RegistryObject<Item> BRICK_MAGENTA_LIGHT = addToTab(ITEMS.register("brick_magenta_light", () -> new Item(new Item.Properties())));
    public static final RegistryObject<Item> BRICK_MAGENTA_MEDIUM = addToTab(ITEMS.register("brick_magenta_medium", () -> new Item(new Item.Properties())));
    public static final RegistryObject<Item> BRICK_MAGENTA_DARK = addToTab(ITEMS.register("brick_magenta_dark", () -> new Item(new Item.Properties())));
    public static final RegistryObject<Item> BRICK_ORANGE_LIGHT = addToTab(ITEMS.register("brick_orange_light", () -> new Item(new Item.Properties())));
    public static final RegistryObject<Item> BRICK_ORANGE_MEDIUM = addToTab(ITEMS.register("brick_orange_medium", () -> new Item(new Item.Properties())));
    public static final RegistryObject<Item> BRICK_ORANGE_DARK = addToTab(ITEMS.register("brick_orange_dark", () -> new Item(new Item.Properties())));
    public static final RegistryObject<Item> BRICK_PINK_LIGHT = addToTab(ITEMS.register("brick_pink_light", () -> new Item(new Item.Properties())));
    public static final RegistryObject<Item> BRICK_PINK_MEDIUM = addToTab(ITEMS.register("brick_pink_medium", () -> new Item(new Item.Properties())));
    public static final RegistryObject<Item> BRICK_PINK_DARK = addToTab(ITEMS.register("brick_pink_dark", () -> new Item(new Item.Properties())));
    public static final RegistryObject<Item> BRICK_PURPLE_LIGHT = addToTab(ITEMS.register("brick_purple_light", () -> new Item(new Item.Properties())));
    public static final RegistryObject<Item> BRICK_PURPLE_MEDIUM = addToTab(ITEMS.register("brick_purple_medium", () -> new Item(new Item.Properties())));
    public static final RegistryObject<Item> BRICK_PURPLE_DARK = addToTab(ITEMS.register("brick_purple_dark", () -> new Item(new Item.Properties())));
    public static final RegistryObject<Item> BRICK_RED_LIGHT = addToTab(ITEMS.register("brick_red_light", () -> new Item(new Item.Properties())));
    public static final RegistryObject<Item> BRICK_RED_MEDIUM = addToTab(ITEMS.register("brick_red_medium", () -> new Item(new Item.Properties())));
    public static final RegistryObject<Item> BRICK_RED_DARK = addToTab(ITEMS.register("brick_red_dark", () -> new Item(new Item.Properties())));
    public static final RegistryObject<Item> BRICK_WHITE_LIGHT = addToTab(ITEMS.register("brick_white_light", () -> new Item(new Item.Properties())));
    public static final RegistryObject<Item> BRICK_WHITE_MEDIUM = addToTab(ITEMS.register("brick_white_medium", () -> new Item(new Item.Properties())));
    public static final RegistryObject<Item> BRICK_WHITE_DARK = addToTab(ITEMS.register("brick_white_dark", () -> new Item(new Item.Properties())));
    public static final RegistryObject<Item> BRICK_YELLOW_LIGHT = addToTab(ITEMS.register("brick_yellow_light", () -> new Item(new Item.Properties())));
    public static final RegistryObject<Item> BRICK_YELLOW_MEDIUM = addToTab(ITEMS.register("brick_yellow_medium", () -> new Item(new Item.Properties())));
    public static final RegistryObject<Item> BRICK_YELLOW_DARK = addToTab(ITEMS.register("brick_yellow_dark", () -> new Item(new Item.Properties())));

    public static final RegistryObject<Item> DYE_BLACK_LIGHT = addToTab(ITEMS.register("dye_black_light", () -> new Item(new Item.Properties())));
    public static final RegistryObject<Item> DYE_BLACK_DARK = addToTab(ITEMS.register("dye_black_dark", () -> new Item(new Item.Properties())));
    public static final RegistryObject<Item> DYE_BLUE_LIGHT = addToTab(ITEMS.register("dye_blue_light", () -> new Item(new Item.Properties())));
    public static final RegistryObject<Item> DYE_BLUE_DARK = addToTab(ITEMS.register("dye_blue_dark", () -> new Item(new Item.Properties())));
    public static final RegistryObject<Item> DYE_BROWN_LIGHT = addToTab(ITEMS.register("dye_brown_light", () -> new Item(new Item.Properties())));
    public static final RegistryObject<Item> DYE_BROWN_DARK = addToTab(ITEMS.register("dye_brown_dark", () -> new Item(new Item.Properties())));
    public static final RegistryObject<Item> DYE_CYAN_LIGHT = addToTab(ITEMS.register("dye_cyan_light", () -> new Item(new Item.Properties())));
    public static final RegistryObject<Item> DYE_CYAN_DARK = addToTab(ITEMS.register("dye_cyan_dark", () -> new Item(new Item.Properties())));
    public static final RegistryObject<Item> DYE_GRAY_LIGHT = addToTab(ITEMS.register("dye_gray_light", () -> new Item(new Item.Properties())));
    public static final RegistryObject<Item> DYE_GRAY_DARK = addToTab(ITEMS.register("dye_gray_dark", () -> new Item(new Item.Properties())));
    public static final RegistryObject<Item> DYE_GREEN_LIGHT = addToTab(ITEMS.register("dye_green_light", () -> new Item(new Item.Properties())));
    public static final RegistryObject<Item> DYE_GREEN_DARK = addToTab(ITEMS.register("dye_green_dark", () -> new Item(new Item.Properties())));
    public static final RegistryObject<Item> DYE_LIGHT_BLUE_LIGHT = addToTab(ITEMS.register("dye_light_blue_light", () -> new Item(new Item.Properties())));
    public static final RegistryObject<Item> DYE_LIGHT_BLUE_DARK = addToTab(ITEMS.register("dye_light_blue_dark", () -> new Item(new Item.Properties())));
    public static final RegistryObject<Item> DYE_LIGHT_GRAY_LIGHT = addToTab(ITEMS.register("dye_light_gray_light", () -> new Item(new Item.Properties())));
    public static final RegistryObject<Item> DYE_LIGHT_GRAY_DARK = addToTab(ITEMS.register("dye_light_gray_dark", () -> new Item(new Item.Properties())));
    public static final RegistryObject<Item> DYE_LIME_LIGHT = addToTab(ITEMS.register("dye_lime_light", () -> new Item(new Item.Properties())));
    public static final RegistryObject<Item> DYE_LIME_DARK = addToTab(ITEMS.register("dye_lime_dark", () -> new Item(new Item.Properties())));
    public static final RegistryObject<Item> DYE_MAGENTA_LIGHT = addToTab(ITEMS.register("dye_magenta_light", () -> new Item(new Item.Properties())));
    public static final RegistryObject<Item> DYE_MAGENTA_DARK = addToTab(ITEMS.register("dye_magenta_dark", () -> new Item(new Item.Properties())));
    public static final RegistryObject<Item> DYE_ORANGE_LIGHT = addToTab(ITEMS.register("dye_orange_light", () -> new Item(new Item.Properties())));
    public static final RegistryObject<Item> DYE_ORANGE_DARK = addToTab(ITEMS.register("dye_orange_dark", () -> new Item(new Item.Properties())));
    public static final RegistryObject<Item> DYE_PINK_LIGHT = addToTab(ITEMS.register("dye_pink_light", () -> new Item(new Item.Properties())));
    public static final RegistryObject<Item> DYE_PINK_DARK = addToTab(ITEMS.register("dye_pink_dark", () -> new Item(new Item.Properties())));
    public static final RegistryObject<Item> DYE_PURPLE_LIGHT = addToTab(ITEMS.register("dye_purple_light", () -> new Item(new Item.Properties())));
    public static final RegistryObject<Item> DYE_PURPLE_DARK = addToTab(ITEMS.register("dye_purple_dark", () -> new Item(new Item.Properties())));
    public static final RegistryObject<Item> DYE_RED_LIGHT = addToTab(ITEMS.register("dye_red_light", () -> new Item(new Item.Properties())));
    public static final RegistryObject<Item> DYE_RED_DARK = addToTab(ITEMS.register("dye_red_dark", () -> new Item(new Item.Properties())));
    public static final RegistryObject<Item> DYE_WHITE_LIGHT = addToTab(ITEMS.register("dye_white_light", () -> new Item(new Item.Properties())));
    public static final RegistryObject<Item> DYE_WHITE_DARK = addToTab(ITEMS.register("dye_white_dark", () -> new Item(new Item.Properties())));
    public static final RegistryObject<Item> DYE_YELLOW_LIGHT = addToTab(ITEMS.register("dye_yellow_light", () -> new Item(new Item.Properties())));
    public static final RegistryObject<Item> DYE_YELLOW_DARK = addToTab(ITEMS.register("dye_yellow_dark", () -> new Item(new Item.Properties())));

    //Block Items
    public static final RegistryObject<BlockItem> BAMBOO_BLOCK_ITEM = addToTab(ITEMS.register("bamboo_block", () -> new BlockItem(BlockInit.BAMBOO_BLOCK.get(), new Item.Properties())));
    public static final RegistryObject<BlockItem> BAMBOO_BUTTON_ITEM = addToTab(ITEMS.register("bamboo_button", () -> new BlockItem(BlockInit.BAMBOO_BUTTON.get(), new Item.Properties())));
    public static final RegistryObject<BlockItem> BAMBOO_DOOR_ITEM = addToTab(ITEMS.register("bamboo_door", () -> new BlockItem(BlockInit.BAMBOO_DOOR.get(), new Item.Properties())));
    public static final RegistryObject<BlockItem> BAMBOO_FENCE_ITEM = addToTab(ITEMS.register("bamboo_fence", () -> new BlockItem(BlockInit.BAMBOO_FENCE.get(), new Item.Properties())));
    public static final RegistryObject<BlockItem> BAMBOO_FENCE_GATE_ITEM = addToTab(ITEMS.register("bamboo_fence_gate", () -> new BlockItem(BlockInit.BAMBOO_FENCE_GATE.get(), new Item.Properties())));
    public static final RegistryObject<BlockItem> BAMBOO_LADDER_ITEM = addToTab(ITEMS.register("bamboo_ladder", () -> new BlockItem(BlockInit.BAMBOO_LADDER.get(), new Item.Properties())));
    public static final RegistryObject<BlockItem> BAMBOO_PRESSURE_PLATE_ITEM = addToTab(ITEMS.register("bamboo_pressure_plate", () -> new BlockItem(BlockInit.BAMBOO_PRESSURE_PLATE.get(), new Item.Properties())));
    public static final RegistryObject<BlockItem> BAMBOO_SLAB_ITEM = addToTab(ITEMS.register("bamboo_slab", () -> new BlockItem(BlockInit.BAMBOO_SLAB.get(), new Item.Properties())));
    public static final RegistryObject<BlockItem> BAMBOO_STAIRS_ITEM = addToTab(ITEMS.register("bamboo_stairs", () -> new BlockItem(BlockInit.BAMBOO_STAIRS.get(), new Item.Properties())));
    public static final RegistryObject<BlockItem> BAMBOO_TRAPDOOR_ITEM = addToTab(ITEMS.register("bamboo_trapdoor", () -> new BlockItem(BlockInit.BAMBOO_TRAPDOOR.get(), new Item.Properties())));

    public static final RegistryObject<BlockItem> THATCH_BLOCK_ITEM = addToTab(ITEMS.register("thatch_block", () -> new BlockItem(BlockInit.THATCH_BLOCK.get(), new Item.Properties())));
    public static final RegistryObject<BlockItem> THATCH_BUTTON_ITEM = addToTab(ITEMS.register("thatch_button", () -> new BlockItem(BlockInit.THATCH_BUTTON.get(), new Item.Properties())));
    public static final RegistryObject<BlockItem> THATCH_DOOR_ITEM = addToTab(ITEMS.register("thatch_door", () -> new BlockItem(BlockInit.THATCH_DOOR.get(), new Item.Properties())));
    public static final RegistryObject<BlockItem> THATCH_FENCE_ITEM = addToTab(ITEMS.register("thatch_fence", () -> new BlockItem(BlockInit.THATCH_FENCE.get(), new Item.Properties())));
    public static final RegistryObject<BlockItem> THATCH_FENCE_GATE_ITEM = addToTab(ITEMS.register("thatch_fence_gate", () -> new BlockItem(BlockInit.THATCH_FENCE_GATE.get(), new Item.Properties())));
    public static final RegistryObject<BlockItem> THATCH_LADDER_ITEM = addToTab(ITEMS.register("thatch_ladder", () -> new BlockItem(BlockInit.THATCH_LADDER.get(), new Item.Properties())));
    public static final RegistryObject<BlockItem> THATCH_PRESSURE_PLATE_ITEM = addToTab(ITEMS.register("thatch_pressure_plate", () -> new BlockItem(BlockInit.THATCH_PRESSURE_PLATE.get(), new Item.Properties())));
    public static final RegistryObject<BlockItem> THATCH_SLAB_ITEM = addToTab(ITEMS.register("thatch_slab", () -> new BlockItem(BlockInit.THATCH_SLAB.get(), new Item.Properties())));
    public static final RegistryObject<BlockItem> THATCH_STAIRS_ITEM = addToTab(ITEMS.register("thatch_stairs", () -> new BlockItem(BlockInit.THATCH_STAIRS.get(), new Item.Properties())));
    public static final RegistryObject<BlockItem> THATCH_TRAPDOOR_ITEM = addToTab(ITEMS.register("thatch_trapdoor", () -> new BlockItem(BlockInit.THATCH_TRAPDOOR.get(), new Item.Properties())));


}