package mod.silverwolf.silverwolfsbuildingblocks.init;

import mod.silverwolf.silverwolfsbuildingblocks.SilverwolfsBuildingBlocks;
import net.minecraft.core.Direction;
import net.minecraft.world.item.BlockItem;
import net.minecraft.world.item.Item;
import net.minecraft.world.item.StandingAndWallBlockItem;
import net.minecraftforge.eventbus.api.IEventBus;
import net.minecraftforge.registries.DeferredRegister;
import net.minecraftforge.registries.ForgeRegistries;
import net.minecraftforge.registries.RegistryObject;

import static mod.silverwolf.silverwolfsbuildingblocks.init.CreativeTabInit.addToTab;

public class ItemInit {
    public static final DeferredRegister<Item> ITEMS = DeferredRegister.create(ForgeRegistries.ITEMS, SilverwolfsBuildingBlocks.MODID);

    //Items
    public static final RegistryObject<Item> THATCH = addToTab(ITEMS.register("thatch", () -> new Item(new Item.Properties())));

    public static final RegistryObject<Item> ACACIA_STICK = addToTab(ITEMS.register("acacia_stick", () -> new Item(new Item.Properties())));
    public static final RegistryObject<Item> BIRCH_STICK = addToTab(ITEMS.register("birch_stick", () -> new Item(new Item.Properties())));
    public static final RegistryObject<Item> CHERRY_STICK = addToTab(ITEMS.register("cherry_stick", () -> new Item(new Item.Properties())));
    public static final RegistryObject<Item> CRIMSON_STICK = addToTab(ITEMS.register("crimson_stick", () -> new Item(new Item.Properties())));
    public static final RegistryObject<Item> DARK_OAK_STICK = addToTab(ITEMS.register("dark_oak_stick", () -> new Item(new Item.Properties())));
    public static final RegistryObject<Item> JUNGLE_STICK = addToTab(ITEMS.register("jungle_stick", () -> new Item(new Item.Properties())));
    public static final RegistryObject<Item> MANGROVE_STICK = addToTab(ITEMS.register("mangrove_stick", () -> new Item(new Item.Properties())));
    public static final RegistryObject<Item> OAK_STICK = addToTab(ITEMS.register("oak_stick", () -> new Item(new Item.Properties())));
    public static final RegistryObject<Item> SPRUCE_STICK = addToTab(ITEMS.register("spruce_stick", () -> new Item(new Item.Properties())));
    public static final RegistryObject<Item> WARPED_STICK = addToTab(ITEMS.register("warped_stick", () -> new Item(new Item.Properties())));

    public static final RegistryObject<Item> CLAY_BALL_BLACK_LIGHT = addToTab(ITEMS.register("clay_ball_black_light", () -> new Item(new Item.Properties())));
    public static final RegistryObject<Item> CLAY_BALL_BLACK_MEDIUM = addToTab(ITEMS.register("clay_ball_black_medium", () -> new Item(new Item.Properties())));
    public static final RegistryObject<Item> CLAY_BALL_BLACK_DARK = addToTab(ITEMS.register("clay_ball_black_dark", () -> new Item(new Item.Properties())));
    public static final RegistryObject<Item> CLAY_BALL_BLUE_LIGHT = addToTab(ITEMS.register("clay_ball_blue_light", () -> new Item(new Item.Properties())));
    public static final RegistryObject<Item> CLAY_BALL_BLUE_MEDIUM = addToTab(ITEMS.register("clay_ball_blue_medium", () -> new Item(new Item.Properties())));
    public static final RegistryObject<Item> CLAY_BALL_BLUE_DARK = addToTab(ITEMS.register("clay_ball_blue_dark", () -> new Item(new Item.Properties())));
    public static final RegistryObject<Item> CLAY_BALL_BROWN_LIGHT = addToTab(ITEMS.register("clay_ball_brown_light", () -> new Item(new Item.Properties())));
    public static final RegistryObject<Item> CLAY_BALL_BROWN_MEDIUM = addToTab(ITEMS.register("clay_ball_brown_medium", () -> new Item(new Item.Properties())));
    public static final RegistryObject<Item> CLAY_BALL_BROWN_DARK = addToTab(ITEMS.register("clay_ball_brown_dark", () -> new Item(new Item.Properties())));
    public static final RegistryObject<Item> CLAY_BALL_CYAN_LIGHT = addToTab(ITEMS.register("clay_ball_cyan_light", () -> new Item(new Item.Properties())));
    public static final RegistryObject<Item> CLAY_BALL_CYAN_MEDIUM = addToTab(ITEMS.register("clay_ball_cyan_medium", () -> new Item(new Item.Properties())));
    public static final RegistryObject<Item> CLAY_BALL_CYAN_DARK = addToTab(ITEMS.register("clay_ball_cyan_dark", () -> new Item(new Item.Properties())));
    public static final RegistryObject<Item> CLAY_BALL_GRAY_LIGHT = addToTab(ITEMS.register("clay_ball_gray_light", () -> new Item(new Item.Properties())));
    public static final RegistryObject<Item> CLAY_BALL_GRAY_MEDIUM = addToTab(ITEMS.register("clay_ball_gray_medium", () -> new Item(new Item.Properties())));
    public static final RegistryObject<Item> CLAY_BALL_GRAY_DARK = addToTab(ITEMS.register("clay_ball_gray_dark", () -> new Item(new Item.Properties())));
    public static final RegistryObject<Item> CLAY_BALL_GREEN_LIGHT = addToTab(ITEMS.register("clay_ball_green_light", () -> new Item(new Item.Properties())));
    public static final RegistryObject<Item> CLAY_BALL_GREEN_MEDIUM = addToTab(ITEMS.register("clay_ball_green_medium", () -> new Item(new Item.Properties())));
    public static final RegistryObject<Item> CLAY_BALL_GREEN_DARK = addToTab(ITEMS.register("clay_ball_green_dark", () -> new Item(new Item.Properties())));
    public static final RegistryObject<Item> CLAY_BALL_LIGHT_BLUE_LIGHT = addToTab(ITEMS.register("clay_ball_light_blue_light", () -> new Item(new Item.Properties())));
    public static final RegistryObject<Item> CLAY_BALL_LIGHT_BLUE_MEDIUM = addToTab(ITEMS.register("clay_ball_light_blue_medium", () -> new Item(new Item.Properties())));
    public static final RegistryObject<Item> CLAY_BALL_LIGHT_BLUE_DARK = addToTab(ITEMS.register("clay_ball_light_blue_dark", () -> new Item(new Item.Properties())));
    public static final RegistryObject<Item> CLAY_BALL_LIGHT_GRAY_LIGHT = addToTab(ITEMS.register("clay_ball_light_gray_light", () -> new Item(new Item.Properties())));
    public static final RegistryObject<Item> CLAY_BALL_LIGHT_GRAY_MEDIUM = addToTab(ITEMS.register("clay_ball_light_gray_medium", () -> new Item(new Item.Properties())));
    public static final RegistryObject<Item> CLAY_BALL_LIGHT_GRAY_DARK = addToTab(ITEMS.register("clay_ball_light_gray_dark", () -> new Item(new Item.Properties())));
    public static final RegistryObject<Item> CLAY_BALL_LIME_LIGHT = addToTab(ITEMS.register("clay_ball_lime_light", () -> new Item(new Item.Properties())));
    public static final RegistryObject<Item> CLAY_BALL_LIME_MEDIUM = addToTab(ITEMS.register("clay_ball_lime_medium", () -> new Item(new Item.Properties())));
    public static final RegistryObject<Item> CLAY_BALL_LIME_DARK = addToTab(ITEMS.register("clay_ball_lime_dark", () -> new Item(new Item.Properties())));
    public static final RegistryObject<Item> CLAY_BALL_MAGENTA_LIGHT = addToTab(ITEMS.register("clay_ball_magenta_light", () -> new Item(new Item.Properties())));
    public static final RegistryObject<Item> CLAY_BALL_MAGENTA_MEDIUM = addToTab(ITEMS.register("clay_ball_magenta_medium", () -> new Item(new Item.Properties())));
    public static final RegistryObject<Item> CLAY_BALL_MAGENTA_DARK = addToTab(ITEMS.register("clay_ball_magenta_dark", () -> new Item(new Item.Properties())));
    public static final RegistryObject<Item> CLAY_BALL_ORANGE_LIGHT = addToTab(ITEMS.register("clay_ball_orange_light", () -> new Item(new Item.Properties())));
    public static final RegistryObject<Item> CLAY_BALL_ORANGE_MEDIUM = addToTab(ITEMS.register("clay_ball_orange_medium", () -> new Item(new Item.Properties())));
    public static final RegistryObject<Item> CLAY_BALL_ORANGE_DARK = addToTab(ITEMS.register("clay_ball_orange_dark", () -> new Item(new Item.Properties())));
    public static final RegistryObject<Item> CLAY_BALL_PINK_LIGHT = addToTab(ITEMS.register("clay_ball_pink_light", () -> new Item(new Item.Properties())));
    public static final RegistryObject<Item> CLAY_BALL_PINK_MEDIUM = addToTab(ITEMS.register("clay_ball_pink_medium", () -> new Item(new Item.Properties())));
    public static final RegistryObject<Item> CLAY_BALL_PINK_DARK = addToTab(ITEMS.register("clay_ball_pink_dark", () -> new Item(new Item.Properties())));
    public static final RegistryObject<Item> CLAY_BALL_PURPLE_LIGHT = addToTab(ITEMS.register("clay_ball_purple_light", () -> new Item(new Item.Properties())));
    public static final RegistryObject<Item> CLAY_BALL_PURPLE_MEDIUM = addToTab(ITEMS.register("clay_ball_purple_medium", () -> new Item(new Item.Properties())));
    public static final RegistryObject<Item> CLAY_BALL_PURPLE_DARK = addToTab(ITEMS.register("clay_ball_purple_dark", () -> new Item(new Item.Properties())));
    public static final RegistryObject<Item> CLAY_BALL_RED_LIGHT = addToTab(ITEMS.register("clay_ball_red_light", () -> new Item(new Item.Properties())));
    public static final RegistryObject<Item> CLAY_BALL_RED_MEDIUM = addToTab(ITEMS.register("clay_ball_red_medium", () -> new Item(new Item.Properties())));
    public static final RegistryObject<Item> CLAY_BALL_RED_DARK = addToTab(ITEMS.register("clay_ball_red_dark", () -> new Item(new Item.Properties())));
    public static final RegistryObject<Item> CLAY_BALL_WHITE_LIGHT = addToTab(ITEMS.register("clay_ball_white_light", () -> new Item(new Item.Properties())));
    public static final RegistryObject<Item> CLAY_BALL_WHITE_MEDIUM = addToTab(ITEMS.register("clay_ball_white_medium", () -> new Item(new Item.Properties())));
    public static final RegistryObject<Item> CLAY_BALL_WHITE_DARK = addToTab(ITEMS.register("clay_ball_white_dark", () -> new Item(new Item.Properties())));
    public static final RegistryObject<Item> CLAY_BALL_YELLOW_LIGHT = addToTab(ITEMS.register("clay_ball_yellow_light", () -> new Item(new Item.Properties())));
    public static final RegistryObject<Item> CLAY_BALL_YELLOW_MEDIUM = addToTab(ITEMS.register("clay_ball_yellow_medium", () -> new Item(new Item.Properties())));
    public static final RegistryObject<Item> CLAY_BALL_YELLOW_DARK = addToTab(ITEMS.register("clay_ball_yellow_dark", () -> new Item(new Item.Properties())));

    public static final RegistryObject<Item> BRICK_BLACK_LIGHT = addToTab(ITEMS.register("brick_black_light", () -> new Item(new Item.Properties())));
    public static final RegistryObject<Item> BRICK_BLACK_MEDIUM = addToTab(ITEMS.register("brick_black_medium", () -> new Item(new Item.Properties())));
    public static final RegistryObject<Item> BRICK_BLACK_DARK = addToTab(ITEMS.register("brick_black_dark", () -> new Item(new Item.Properties())));
    public static final RegistryObject<Item> BRICK_BLUE_LIGHT = addToTab(ITEMS.register("brick_blue_light", () -> new Item(new Item.Properties())));
    public static final RegistryObject<Item> BRICK_BLUE_MEDIUM = addToTab(ITEMS.register("brick_blue_medium", () -> new Item(new Item.Properties())));
    public static final RegistryObject<Item> BRICK_BLUE_DARK = addToTab(ITEMS.register("brick_blue_dark", () -> new Item(new Item.Properties())));
    public static final RegistryObject<Item> BRICK_BROWN_LIGHT = addToTab(ITEMS.register("brick_brown_light", () -> new Item(new Item.Properties())));
    public static final RegistryObject<Item> BRICK_BROWN_MEDIUM = addToTab(ITEMS.register("brick_brown_medium", () -> new Item(new Item.Properties())));
    public static final RegistryObject<Item> BRICK_BROWN_DARK = addToTab(ITEMS.register("brick_brown_dark", () -> new Item(new Item.Properties())));
    public static final RegistryObject<Item> BRICK_CYAN_LIGHT = addToTab(ITEMS.register("brick_cyan_light", () -> new Item(new Item.Properties())));
    public static final RegistryObject<Item> BRICK_CYAN_MEDIUM = addToTab(ITEMS.register("brick_cyan_medium", () -> new Item(new Item.Properties())));
    public static final RegistryObject<Item> BRICK_CYAN_DARK = addToTab(ITEMS.register("brick_cyan_dark", () -> new Item(new Item.Properties())));
    public static final RegistryObject<Item> BRICK_GRAY_LIGHT = addToTab(ITEMS.register("brick_gray_light", () -> new Item(new Item.Properties())));
    public static final RegistryObject<Item> BRICK_GRAY_MEDIUM = addToTab(ITEMS.register("brick_gray_medium", () -> new Item(new Item.Properties())));
    public static final RegistryObject<Item> BRICK_GRAY_DARK = addToTab(ITEMS.register("brick_gray_dark", () -> new Item(new Item.Properties())));
    public static final RegistryObject<Item> BRICK_GREEN_LIGHT = addToTab(ITEMS.register("brick_green_light", () -> new Item(new Item.Properties())));
    public static final RegistryObject<Item> BRICK_GREEN_MEDIUM = addToTab(ITEMS.register("brick_green_medium", () -> new Item(new Item.Properties())));
    public static final RegistryObject<Item> BRICK_GREEN_DARK = addToTab(ITEMS.register("brick_green_dark", () -> new Item(new Item.Properties())));
    public static final RegistryObject<Item> BRICK_LIGHT_BLUE_LIGHT = addToTab(ITEMS.register("brick_light_blue_light", () -> new Item(new Item.Properties())));
    public static final RegistryObject<Item> BRICK_LIGHT_BLUE_MEDIUM = addToTab(ITEMS.register("brick_light_blue_medium", () -> new Item(new Item.Properties())));
    public static final RegistryObject<Item> BRICK_LIGHT_BLUE_DARK = addToTab(ITEMS.register("brick_light_blue_dark", () -> new Item(new Item.Properties())));
    public static final RegistryObject<Item> BRICK_LIGHT_GRAY_LIGHT = addToTab(ITEMS.register("brick_light_gray_light", () -> new Item(new Item.Properties())));
    public static final RegistryObject<Item> BRICK_LIGHT_GRAY_MEDIUM = addToTab(ITEMS.register("brick_light_gray_medium", () -> new Item(new Item.Properties())));
    public static final RegistryObject<Item> BRICK_LIGHT_GRAY_DARK = addToTab(ITEMS.register("brick_light_gray_dark", () -> new Item(new Item.Properties())));
    public static final RegistryObject<Item> BRICK_LIME_LIGHT = addToTab(ITEMS.register("brick_lime_light", () -> new Item(new Item.Properties())));
    public static final RegistryObject<Item> BRICK_LIME_MEDIUM = addToTab(ITEMS.register("brick_lime_medium", () -> new Item(new Item.Properties())));
    public static final RegistryObject<Item> BRICK_LIME_DARK = addToTab(ITEMS.register("brick_lime_dark", () -> new Item(new Item.Properties())));
    public static final RegistryObject<Item> BRICK_MAGENTA_LIGHT = addToTab(ITEMS.register("brick_magenta_light", () -> new Item(new Item.Properties())));
    public static final RegistryObject<Item> BRICK_MAGENTA_MEDIUM = addToTab(ITEMS.register("brick_magenta_medium", () -> new Item(new Item.Properties())));
    public static final RegistryObject<Item> BRICK_MAGENTA_DARK = addToTab(ITEMS.register("brick_magenta_dark", () -> new Item(new Item.Properties())));
    public static final RegistryObject<Item> BRICK_ORANGE_LIGHT = addToTab(ITEMS.register("brick_orange_light", () -> new Item(new Item.Properties())));
    public static final RegistryObject<Item> BRICK_ORANGE_MEDIUM = addToTab(ITEMS.register("brick_orange_medium", () -> new Item(new Item.Properties())));
    public static final RegistryObject<Item> BRICK_ORANGE_DARK = addToTab(ITEMS.register("brick_orange_dark", () -> new Item(new Item.Properties())));
    public static final RegistryObject<Item> BRICK_PINK_LIGHT = addToTab(ITEMS.register("brick_pink_light", () -> new Item(new Item.Properties())));
    public static final RegistryObject<Item> BRICK_PINK_MEDIUM = addToTab(ITEMS.register("brick_pink_medium", () -> new Item(new Item.Properties())));
    public static final RegistryObject<Item> BRICK_PINK_DARK = addToTab(ITEMS.register("brick_pink_dark", () -> new Item(new Item.Properties())));
    public static final RegistryObject<Item> BRICK_PURPLE_LIGHT = addToTab(ITEMS.register("brick_purple_light", () -> new Item(new Item.Properties())));
    public static final RegistryObject<Item> BRICK_PURPLE_MEDIUM = addToTab(ITEMS.register("brick_purple_medium", () -> new Item(new Item.Properties())));
    public static final RegistryObject<Item> BRICK_PURPLE_DARK = addToTab(ITEMS.register("brick_purple_dark", () -> new Item(new Item.Properties())));
    public static final RegistryObject<Item> BRICK_RED_LIGHT = addToTab(ITEMS.register("brick_red_light", () -> new Item(new Item.Properties())));
    public static final RegistryObject<Item> BRICK_RED_MEDIUM = addToTab(ITEMS.register("brick_red_medium", () -> new Item(new Item.Properties())));
    public static final RegistryObject<Item> BRICK_RED_DARK = addToTab(ITEMS.register("brick_red_dark", () -> new Item(new Item.Properties())));
    public static final RegistryObject<Item> BRICK_WHITE_LIGHT = addToTab(ITEMS.register("brick_white_light", () -> new Item(new Item.Properties())));
    public static final RegistryObject<Item> BRICK_WHITE_MEDIUM = addToTab(ITEMS.register("brick_white_medium", () -> new Item(new Item.Properties())));
    public static final RegistryObject<Item> BRICK_WHITE_DARK = addToTab(ITEMS.register("brick_white_dark", () -> new Item(new Item.Properties())));
    public static final RegistryObject<Item> BRICK_YELLOW_LIGHT = addToTab(ITEMS.register("brick_yellow_light", () -> new Item(new Item.Properties())));
    public static final RegistryObject<Item> BRICK_YELLOW_MEDIUM = addToTab(ITEMS.register("brick_yellow_medium", () -> new Item(new Item.Properties())));
    public static final RegistryObject<Item> BRICK_YELLOW_DARK = addToTab(ITEMS.register("brick_yellow_dark", () -> new Item(new Item.Properties())));

    public static final RegistryObject<Item> DYE_BLACK_LIGHT = addToTab(ITEMS.register("dye_black_light", () -> new Item(new Item.Properties())));
    public static final RegistryObject<Item> DYE_BLACK_DARK = addToTab(ITEMS.register("dye_black_dark", () -> new Item(new Item.Properties())));
    public static final RegistryObject<Item> DYE_BLUE_LIGHT = addToTab(ITEMS.register("dye_blue_light", () -> new Item(new Item.Properties())));
    public static final RegistryObject<Item> DYE_BLUE_DARK = addToTab(ITEMS.register("dye_blue_dark", () -> new Item(new Item.Properties())));
    public static final RegistryObject<Item> DYE_BROWN_LIGHT = addToTab(ITEMS.register("dye_brown_light", () -> new Item(new Item.Properties())));
    public static final RegistryObject<Item> DYE_BROWN_DARK = addToTab(ITEMS.register("dye_brown_dark", () -> new Item(new Item.Properties())));
    public static final RegistryObject<Item> DYE_CYAN_LIGHT = addToTab(ITEMS.register("dye_cyan_light", () -> new Item(new Item.Properties())));
    public static final RegistryObject<Item> DYE_CYAN_DARK = addToTab(ITEMS.register("dye_cyan_dark", () -> new Item(new Item.Properties())));
    public static final RegistryObject<Item> DYE_GRAY_LIGHT = addToTab(ITEMS.register("dye_gray_light", () -> new Item(new Item.Properties())));
    public static final RegistryObject<Item> DYE_GRAY_DARK = addToTab(ITEMS.register("dye_gray_dark", () -> new Item(new Item.Properties())));
    public static final RegistryObject<Item> DYE_GREEN_LIGHT = addToTab(ITEMS.register("dye_green_light", () -> new Item(new Item.Properties())));
    public static final RegistryObject<Item> DYE_GREEN_DARK = addToTab(ITEMS.register("dye_green_dark", () -> new Item(new Item.Properties())));
    public static final RegistryObject<Item> DYE_LIGHT_BLUE_LIGHT = addToTab(ITEMS.register("dye_light_blue_light", () -> new Item(new Item.Properties())));
    public static final RegistryObject<Item> DYE_LIGHT_BLUE_DARK = addToTab(ITEMS.register("dye_light_blue_dark", () -> new Item(new Item.Properties())));
    public static final RegistryObject<Item> DYE_LIGHT_GRAY_LIGHT = addToTab(ITEMS.register("dye_light_gray_light", () -> new Item(new Item.Properties())));
    public static final RegistryObject<Item> DYE_LIGHT_GRAY_DARK = addToTab(ITEMS.register("dye_light_gray_dark", () -> new Item(new Item.Properties())));
    public static final RegistryObject<Item> DYE_LIME_LIGHT = addToTab(ITEMS.register("dye_lime_light", () -> new Item(new Item.Properties())));
    public static final RegistryObject<Item> DYE_LIME_DARK = addToTab(ITEMS.register("dye_lime_dark", () -> new Item(new Item.Properties())));
    public static final RegistryObject<Item> DYE_MAGENTA_LIGHT = addToTab(ITEMS.register("dye_magenta_light", () -> new Item(new Item.Properties())));
    public static final RegistryObject<Item> DYE_MAGENTA_DARK = addToTab(ITEMS.register("dye_magenta_dark", () -> new Item(new Item.Properties())));
    public static final RegistryObject<Item> DYE_ORANGE_LIGHT = addToTab(ITEMS.register("dye_orange_light", () -> new Item(new Item.Properties())));
    public static final RegistryObject<Item> DYE_ORANGE_DARK = addToTab(ITEMS.register("dye_orange_dark", () -> new Item(new Item.Properties())));
    public static final RegistryObject<Item> DYE_PINK_LIGHT = addToTab(ITEMS.register("dye_pink_light", () -> new Item(new Item.Properties())));
    public static final RegistryObject<Item> DYE_PINK_DARK = addToTab(ITEMS.register("dye_pink_dark", () -> new Item(new Item.Properties())));
    public static final RegistryObject<Item> DYE_PURPLE_LIGHT = addToTab(ITEMS.register("dye_purple_light", () -> new Item(new Item.Properties())));
    public static final RegistryObject<Item> DYE_PURPLE_DARK = addToTab(ITEMS.register("dye_purple_dark", () -> new Item(new Item.Properties())));
    public static final RegistryObject<Item> DYE_RED_LIGHT = addToTab(ITEMS.register("dye_red_light", () -> new Item(new Item.Properties())));
    public static final RegistryObject<Item> DYE_RED_DARK = addToTab(ITEMS.register("dye_red_dark", () -> new Item(new Item.Properties())));
    public static final RegistryObject<Item> DYE_WHITE_LIGHT = addToTab(ITEMS.register("dye_white_light", () -> new Item(new Item.Properties())));
    public static final RegistryObject<Item> DYE_WHITE_DARK = addToTab(ITEMS.register("dye_white_dark", () -> new Item(new Item.Properties())));
    public static final RegistryObject<Item> DYE_YELLOW_LIGHT = addToTab(ITEMS.register("dye_yellow_light", () -> new Item(new Item.Properties())));
    public static final RegistryObject<Item> DYE_YELLOW_DARK = addToTab(ITEMS.register("dye_yellow_dark", () -> new Item(new Item.Properties())));

    //Block Items
    public static final RegistryObject<BlockItem> ACACIA_TORCH_ITEM = addToTab(ITEMS.register("acacia_torch", () -> new StandingAndWallBlockItem(BlockInit.ACACIA_TORCH.get(), BlockInit.ACACIA_WALL_TORCH.get(), new Item.Properties(), Direction.DOWN)));
    public static final RegistryObject<BlockItem> BIRCH_TORCH_ITEM = addToTab(ITEMS.register("birch_torch", () -> new StandingAndWallBlockItem(BlockInit.BIRCH_TORCH.get(), BlockInit.BIRCH_WALL_TORCH.get(), new Item.Properties(), Direction.DOWN)));
    public static final RegistryObject<BlockItem> CHERRY_TORCH_ITEM = addToTab(ITEMS.register("cherry_torch", () -> new StandingAndWallBlockItem(BlockInit.CHERRY_TORCH.get(), BlockInit.CHERRY_WALL_TORCH.get(), new Item.Properties(), Direction.DOWN)));
    public static final RegistryObject<BlockItem> CRIMSON_TORCH_ITEM = addToTab(ITEMS.register("crimson_torch", () -> new StandingAndWallBlockItem(BlockInit.CRIMSON_TORCH.get(), BlockInit.CRIMSON_WALL_TORCH.get(), new Item.Properties(), Direction.DOWN)));
    public static final RegistryObject<BlockItem> DARK_OAK_TORCH_ITEM = addToTab(ITEMS.register("dark_oak_torch", () -> new StandingAndWallBlockItem(BlockInit.DARK_OAK_TORCH.get(), BlockInit.DARK_OAK_WALL_TORCH.get(), new Item.Properties(), Direction.DOWN)));
    public static final RegistryObject<BlockItem> JUNGLE_TORCH_ITEM = addToTab(ITEMS.register("jungle_torch", () -> new StandingAndWallBlockItem(BlockInit.JUNGLE_TORCH.get(), BlockInit.JUNGLE_WALL_TORCH.get(), new Item.Properties(), Direction.DOWN)));
    public static final RegistryObject<BlockItem> MANGROVE_TORCH_ITEM = addToTab(ITEMS.register("mangrove_torch", () -> new StandingAndWallBlockItem(BlockInit.MANGROVE_TORCH.get(), BlockInit.MANGROVE_WALL_TORCH.get(), new Item.Properties(), Direction.DOWN)));
    public static final RegistryObject<BlockItem> OAK_TORCH_ITEM = addToTab(ITEMS.register("oak_torch", () -> new StandingAndWallBlockItem(BlockInit.OAK_TORCH.get(), BlockInit.OAK_WALL_TORCH.get(), new Item.Properties(), Direction.DOWN)));
    public static final RegistryObject<BlockItem> SPRUCE_TORCH_ITEM = addToTab(ITEMS.register("spruce_torch", () -> new StandingAndWallBlockItem(BlockInit.SPRUCE_TORCH.get(), BlockInit.SPRUCE_WALL_TORCH.get(), new Item.Properties(), Direction.DOWN)));
    public static final RegistryObject<BlockItem> WARPED_TORCH_ITEM = addToTab(ITEMS.register("warped_torch", () -> new StandingAndWallBlockItem(BlockInit.WARPED_TORCH.get(), BlockInit.WARPED_WALL_TORCH.get(), new Item.Properties(), Direction.DOWN)));

    public static final RegistryObject<BlockItem> ACACIA_SOUL_TORCH_ITEM = addToTab(ITEMS.register("acacia_soul_torch", () -> new StandingAndWallBlockItem(BlockInit.ACACIA_SOUL_TORCH.get(), BlockInit.ACACIA_WALL_SOUL_TORCH.get(), new Item.Properties(), Direction.DOWN)));
    public static final RegistryObject<BlockItem> BIRCH_SOUL_TORCH_ITEM = addToTab(ITEMS.register("birch_soul_torch", () -> new StandingAndWallBlockItem(BlockInit.BIRCH_SOUL_TORCH.get(), BlockInit.BIRCH_WALL_SOUL_TORCH.get(), new Item.Properties(), Direction.DOWN)));
    public static final RegistryObject<BlockItem> CHERRY_SOUL_TORCH_ITEM = addToTab(ITEMS.register("cherry_soul_torch", () -> new StandingAndWallBlockItem(BlockInit.CHERRY_SOUL_TORCH.get(), BlockInit.CHERRY_WALL_SOUL_TORCH.get(), new Item.Properties(), Direction.DOWN)));
    public static final RegistryObject<BlockItem> CRIMSON_SOUL_TORCH_ITEM = addToTab(ITEMS.register("crimson_soul_torch", () -> new StandingAndWallBlockItem(BlockInit.CRIMSON_SOUL_TORCH.get(), BlockInit.CRIMSON_WALL_SOUL_TORCH.get(), new Item.Properties(), Direction.DOWN)));
    public static final RegistryObject<BlockItem> DARK_OAK_SOUL_TORCH_ITEM = addToTab(ITEMS.register("dark_oak_soul_torch", () -> new StandingAndWallBlockItem(BlockInit.DARK_OAK_SOUL_TORCH.get(), BlockInit.DARK_OAK_WALL_SOUL_TORCH.get(), new Item.Properties(), Direction.DOWN)));
    public static final RegistryObject<BlockItem> JUNGLE_SOUL_TORCH_ITEM = addToTab(ITEMS.register("jungle_soul_torch", () -> new StandingAndWallBlockItem(BlockInit.JUNGLE_SOUL_TORCH.get(), BlockInit.JUNGLE_WALL_SOUL_TORCH.get(), new Item.Properties(), Direction.DOWN)));
    public static final RegistryObject<BlockItem> MANGROVE_SOUL_TORCH_ITEM = addToTab(ITEMS.register("mangrove_soul_torch", () -> new StandingAndWallBlockItem(BlockInit.MANGROVE_SOUL_TORCH.get(), BlockInit.MANGROVE_WALL_SOUL_TORCH.get(), new Item.Properties(), Direction.DOWN)));
    public static final RegistryObject<BlockItem> OAK_SOUL_TORCH_ITEM = addToTab(ITEMS.register("oak_soul_torch", () -> new StandingAndWallBlockItem(BlockInit.OAK_SOUL_TORCH.get(), BlockInit.OAK_WALL_SOUL_TORCH.get(), new Item.Properties(), Direction.DOWN)));
    public static final RegistryObject<BlockItem> SPRUCE_SOUL_TORCH_ITEM = addToTab(ITEMS.register("spruce_soul_torch", () -> new StandingAndWallBlockItem(BlockInit.SPRUCE_SOUL_TORCH.get(), BlockInit.SPRUCE_WALL_SOUL_TORCH.get(), new Item.Properties(), Direction.DOWN)));
    public static final RegistryObject<BlockItem> WARPED_SOUL_TORCH_ITEM = addToTab(ITEMS.register("warped_soul_torch", () -> new StandingAndWallBlockItem(BlockInit.WARPED_SOUL_TORCH.get(), BlockInit.WARPED_WALL_SOUL_TORCH.get(), new Item.Properties(), Direction.DOWN)));

    public static void register(IEventBus eventBus) {
        ITEMS.register(eventBus);
    }
}